import graphene

from core.schema import OpenIMISMutation


class WorkforceRepresentativeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    type = graphene.String(requred=True)
    name_bn = graphene.String(required=True)
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String(required=True)
    phone_number = graphene.String()
    email = graphene.String()
    nid = graphene.String()
    passport_no = graphene.String()
    birth_date = graphene.String(required=True)
    position = graphene.String(required=True)
    status = graphene.String()
    related_user_id = graphene.String()


class WorkforceOrganizationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    type = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String(required=True)
    website = graphene.String()
    status = graphene.String()
    parent_id = graphene.UUID(required=False)
    workforce_representative_id = graphene.UUID(required=True)


class WorkforceOrganizationUnitInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    organization_id = graphene.UUID(required=True)
    unit_level = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    phone_number = graphene.String()
    email = graphene.String()
    status = graphene.String()
    parent_id = graphene.UUID()


class WorkforceOrganizationUnitDesignationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    organization_id = graphene.UUID(required=True)
    unit_id = graphene.UUID(required=True)
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    status = graphene.String()
    parent = graphene.UUID()
    designation_level = graphene.Int(required=True)
    designation_sequence = graphene.Int(required=True)


class WorkforceOrganizationEmployeeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    name_bn = graphene.String(required=True)
    name_en = graphene.String(required=True)
    gender = graphene.String()
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    birth_date = graphene.String()
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    passport_no = graphene.String()
    first_joining_date = graphene.String()
    status = graphene.String()
    related_user_id = graphene.UUID(required=False)


class WorkforceOrganizationEmployeeDesignationInputType(OpenIMISMutation.Input):
    id = graphene.UUID(required=False)
    designation_id = graphene.UUID(required=True)
    employee_id = graphene.UUID(required=True)
    incharge_label = graphene.String(required=False)
    status = graphene.String(required=False)
    joining_date = graphene.String(required=False)
    release_date = graphene.String(required=False)


class WorkforceEmployerInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    employer_id = graphene.String(required=True, unique=True)
    employer_id_lima = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    website = graphene.String()
    licence_type = graphene.String(required=True)
    licence_number = graphene.String()
    business_sector = graphene.String(required=True)
    foundation_date = graphene.String()
    association_name = graphene.String()
    association_membership_number = graphene.String()
    establishment_Name = graphene.String()
    establishment_date = graphene.String()
    status = graphene.String()
    workforce_representative_id = graphene.UUID(required=True)


class WorkforceEmployerStatusInput(OpenIMISMutation.Input):
    id = graphene.String(required=True)
    status = graphene.String(required=True)


class WorkforceOfficeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_employer_id = graphene.UUID(required=True)
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    website = graphene.String()
    parent_id = graphene.UUID()
    status = graphene.String()
    is_same_company_representative = graphene.String()
    workforce_representative_id = graphene.UUID()


class WorkforceFactoryInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_employer_id = graphene.UUID(required=True)
    employer_id = graphene.String()
    employer_id_lima = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    website = graphene.String()
    status = graphene.String()
    is_same_company_representative = graphene.String()
    workforce_representative_id = graphene.UUID()


class WorkforceEmployeeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    employee_id = graphene.String(unique=True)
    employee_id_lima = graphene.String()
    insurance_number = graphene.String(required=True, unique=True)
    employee_type = graphene.String()
    global_id = graphene.String()
    present_location_id = graphene.String()
    permanent_location_id = graphene.String()
    first_name_bn = graphene.String()
    last_name_bn = graphene.String()
    other_name = graphene.String()
    first_name_en = graphene.String()
    last_name_en = graphene.String()
    father_name_bn = graphene.String()
    father_name_en = graphene.String()
    mother_name_bn = graphene.String()
    mother_name_en = graphene.String()
    spouse_name_bn = graphene.String()
    spouse_name_en = graphene.String()
    citizenship = graphene.String()
    privacy_law = graphene.String()
    marital_status = graphene.String()
    gender = graphene.String()
    photo_path = graphene.String()
    photo_date = graphene.String()
    position = graphene.String()
    monthly_earning = graphene.String()
    reference_salary = graphene.String()
    present_address = graphene.String()
    permanent_address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    birth_date = graphene.String()
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    passport_no = graphene.String()
    registration_date = graphene.String()
    life_status = graphene.String()
    disability_status = graphene.String()
    death_date = graphene.String()
    status = graphene.String()
    related_user_id = graphene.UUID()


class WorkforceEmployeeDesignationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    workforce_employee_id = graphene.String(required=True)
    workforce_company_id = graphene.String(required=True)
    workforce_factory_id = graphene.String()
    workforce_office_id = graphene.String()
    position = graphene.String()
    join_date = graphene.String()
    resignation_date = graphene.String()
    resignation_reason = graphene.String()
    monthly_salary = graphene.String()
    status = graphene.String()


class WorkforceDocumentInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    holder = graphene.String()
    holder_type = graphene.String(required=True)
    verifier_id = graphene.String()
    approver_id = graphene.String()
    document_type = graphene.String()
    path = graphene.String()
    submission_date = graphene.String()
    verification_date = graphene.String()
    approval_date = graphene.String()
    remarks = graphene.String()
    status = graphene.String()


class BankInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    name_en = graphene.String(required=True)
    name_bn = graphene.String()
    parent_id = graphene.UUID()
    headquarter_address = graphene.String()
    location_id = graphene.String(required=True)
    routing_number = graphene.String()
    contact_number = graphene.String()
    type = graphene.String()
    status = graphene.String()


class WorkforceEmployeeDependentInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    eis_insurance_no = graphene.String()
    first_name_bn = graphene.String(required=True)
    last_name_bn = graphene.String()
    first_name_en = graphene.String()
    last_name_en = graphene.String()
    father_name_bn = graphene.String()
    father_name_en = graphene.String()
    mother_name_bn = graphene.String()
    mother_name_en = graphene.String()
    marital_status = graphene.String(required=True)
    gender = graphene.String(required=True)
    occupation = graphene.String(required=True)
    email = graphene.String()
    phone_number = graphene.String(required=True)
    birth_date = graphene.String(required=True)
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    present_location_id = graphene.String()
    permanent_location_id = graphene.String()
    present_address = graphene.String()
    permanent_address = graphene.String()
    life_status = graphene.String(required=True)
    death_date = graphene.String()
    disability_status = graphene.String()
    relation_type = graphene.String(required=True)
    relation_with_worker = graphene.String(required=True)
    last_verification_date = graphene.String()
    status = graphene.String()


class WorkforceEmployeeAccidentInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    employee_id = graphene.String(required=True)
    injury_type = graphene.String(required=True)
    accident_date = graphene.String(required=True)
    accident_time = graphene.String(required=True)
    accident_type = graphene.String(required=True)
    duty_status = graphene.String(required=True)
    in_outside_factory = graphene.String(required=True)
    death_date = graphene.String()
    description = graphene.String()
    accident_location_id = graphene.String(required=True)
    rejoin_date = graphene.String()
    status = graphene.String()


class WorkforceEmployeeAccountInfoInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    beneficiary_type = graphene.String(required=True)
    beneficiary_id = graphene.String(required=True)
    on_behalf_of = graphene.String(required=True)
    present_location_id = graphene.String(required=True)
    permanent_location_id = graphene.String()
    bank_id = graphene.String(required=True)
    branch_id = graphene.String(required=True)
    account_holder_name = graphene.String(required=True)
    account_owner_name = graphene.String(required=True)
    account_number = graphene.String(required=True)
    status = graphene.String()


class WorkforceApplicationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_employee_id = graphene.String()
    employee_designation_info = graphene.String()
    employee_document_info = graphene.String()
    employee_bank_info = graphene.String()
    employee_dependent_info = graphene.String()
    employee_accident_info = graphene.String()
    organization_id = graphene.String()
    organization_type = graphene.String()
    employee_employer_id = graphene.String()
    employee_factory_id = graphene.String()
    application_type = graphene.String()
    status = graphene.String()