import graphene

from core.schema import OpenIMISMutation


class WorkforceRepresentativeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    type = graphene.String(requred=True)
    name_bn = graphene.String(required=True)
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String(required=True)
    phone_number = graphene.String()
    email = graphene.String()
    nid = graphene.String()
    passport_no = graphene.String()
    birth_date = graphene.String(required=True)
    position = graphene.String(required=True)
    status = graphene.String()
    related_user_id = graphene.String()


class WorkforceOrganizationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    type = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String(required=True)
    website = graphene.String()
    status = graphene.String()
    parent_id = graphene.UUID(required=False)
    workforce_representative_id = graphene.UUID(required=True)


class WorkforceOrganizationUnitInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    organization_id = graphene.UUID(required=True)
    unit_level = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    phone_number = graphene.String()
    email = graphene.String()
    status = graphene.String()
    parent_id = graphene.UUID()


class WorkforceOrganizationUnitDesignationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    organization_id = graphene.UUID(required=True)
    unit_id = graphene.UUID(required=True)
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    status = graphene.String()
    parent = graphene.UUID()
    designation_level = graphene.Int(required=True)
    designation_sequence = graphene.Int(required=True)


class WorkforceOrganizationEmployeeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    name_bn = graphene.String(required=True)
    name_en = graphene.String(required=True)
    gender = graphene.String()
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    birth_date = graphene.String()
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    passport_no = graphene.String()
    first_joining_date = graphene.String()
    status = graphene.String()
    related_user_id = graphene.UUID(required=False)
    association_id = graphene.UUID(required=False)
    all_association_id = graphene.UUID(required=False)
    workforce_employer_factory_id= graphene.UUID(required=False)
    role_id= graphene.Int(required=False)


class WorkforceOrganizationEmployeeDesignationInputType(OpenIMISMutation.Input):
    id = graphene.UUID(required=False)
    designation_id = graphene.UUID(required=True)
    employee_id = graphene.UUID(required=True)
    incharge_label = graphene.String(required=False)
    status = graphene.String(required=False)
    joining_date = graphene.String(required=False)
    release_date = graphene.String(required=False)


class WorkforceEmployerInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    employer_id = graphene.String(required=True, unique=True)
    employer_id_lima = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    website = graphene.String()
    licence_type = graphene.String(required=True)
    licence_number = graphene.String()
    business_sector = graphene.String(required=True)
    foundation_date = graphene.String()
    association_name = graphene.String()
    association_membership_number = graphene.String()
    establishment_Name = graphene.String()
    establishment_date = graphene.String()
    status = graphene.String()
    workforce_representative_id = graphene.UUID(required=True)


class WorkforceEmployerStatusInput(OpenIMISMutation.Input):
    id = graphene.String(required=True)
    status = graphene.String(required=True)


class WorkforceOfficeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_employer_id = graphene.UUID(required=True)
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    location_id = graphene.String(required=True)
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    website = graphene.String()
    parent_id = graphene.UUID()
    status = graphene.String()
    is_same_company_representative = graphene.String()
    workforce_representative_id = graphene.UUID()


class WorkforceFactoryInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_employer_id = graphene.UUID(required=False)
    employer_id = graphene.String()
    employer_id_lima = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String(required=True)
    group_name = graphene.String()
    license_type = graphene.String()
    location_id = graphene.String(required=True)
    office_location_id = graphene.String()
    future_date = graphene.String()
    date_of_eis_incorporation = graphene.String()
    date_of_factory_establishment = graphene.String()
    membership_no = graphene.String()
    business_sector = graphene.String()
    license_no = graphene.String()
    lima_registration_number = graphene.String()
    approximate_number_of_employee = graphene.String()
    office_address = graphene.String()
    address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    website = graphene.String()
    status = graphene.String()
    association_type = graphene.String()
    all_association_id = graphene.String()
    is_same_company_representative = graphene.String()
    workforce_representative_id = graphene.String()
    registration_date= graphene.String()
    registration_expiry_date= graphene.String()


class WorkforceFactoryRegistrationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    factory_id = graphene.String(required=False)
    workforce_employer_id = graphene.UUID(required=False)
    employer_id = graphene.String(required=False)
    employer_id_lima = graphene.String(required=False)
    name_bn = graphene.String(required=False)
    name_en = graphene.String(required=False)
    location_id = graphene.String(required=False)
    address = graphene.String(required=False)
    phone_number = graphene.String(required=False)
    email = graphene.String(required=False)
    website = graphene.String(required=False)
    status = graphene.String(required=False)
    association_type = graphene.String(required=False)
    representative_type = graphene.String(required=True)
    representative_name_bn = graphene.String(required=True)
    representative_name_en = graphene.String(required=True)
    representative_location_id = graphene.String(required=False)
    representative_address = graphene.String(required=True)
    representative_phone_number = graphene.String(required=True)
    representative_email = graphene.String(required=True)
    representative_nid = graphene.String(required=True)
    representative_passport_no = graphene.String(required=False)
    representative_birth_date = graphene.String(required=True)
    representative_position = graphene.String(required=True)


class WorkforceFactoryRegistrationApprovalInputType(OpenIMISMutation.Input):
    id = graphene.String(required=True)
    approval_status = graphene.String(required=True)
    approved_by = graphene.String(required=True)


class WorkforceEmployeeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    employee_id = graphene.String(unique=True)
    employee_id_lima = graphene.String()
    workforce_factory_id = graphene.String()
    # insurance_number = graphene.String(required=True, unique=True)
    insurance_number = graphene.String(required=False)
    employee_type = graphene.String()
    global_id = graphene.String()
    present_location_id = graphene.String()
    permanent_location_id = graphene.String()
    first_name_bn = graphene.String()
    last_name_bn = graphene.String()
    other_name = graphene.String()
    first_name_en = graphene.String()
    last_name_en = graphene.String()
    father_name_bn = graphene.String()
    father_name_en = graphene.String()
    mother_name_bn = graphene.String()
    mother_name_en = graphene.String()
    spouse_name_bn = graphene.String()
    spouse_name_en = graphene.String()
    citizenship = graphene.String()
    privacy_law = graphene.String()
    marital_status = graphene.String()
    gender = graphene.String()
    photo_path = graphene.String()
    photo_date = graphene.String()
    position = graphene.String()
    monthly_earning = graphene.String()
    reference_salary = graphene.String()
    present_address = graphene.String()
    permanent_address = graphene.String()
    phone_number = graphene.String()
    email = graphene.String()
    birth_date = graphene.String()
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    passport_no = graphene.String()
    registration_date = graphene.String()
    life_status = graphene.String()
    disability_status = graphene.String()
    death_date = graphene.String()
    status = graphene.String()
    related_user_id = graphene.UUID()
    role_id= graphene.Int()


class WorkforceEmployeeDesignationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    workforce_employee_id = graphene.String(required=True)
    workforce_company_id = graphene.String(required=True)
    workforce_factory_id = graphene.String()
    workforce_office_id = graphene.String()
    position = graphene.String()
    join_date = graphene.String()
    resignation_date = graphene.String()
    resignation_reason = graphene.String()
    monthly_salary = graphene.String()
    status = graphene.String()


class WorkforceDocumentInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    holder_id = graphene.String()
    holder_type = graphene.String(required=True)
    verifier_id = graphene.String()
    approver_id = graphene.String()
    factory_id = graphene.String()
    workforce_document_type_id = graphene.String()
    workforce_dependent_id = graphene.String()
    application_summary_id = graphene.String()
    workforce_employee_banking_info_id = graphene.String()
    note = graphene.String()
    document_type = graphene.String()
    path = graphene.String(required=False)
    url = graphene.String(required=False)
    submission_date = graphene.String()
    verification_date = graphene.String()
    approval_date = graphene.String()
    remarks = graphene.String()
    is_deleted = graphene.Boolean()
    status = graphene.String()


class WorkforceBankInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    name_en = graphene.String(required=True)
    name_bn = graphene.String()
    bank_code = graphene.String()
    branch_code = graphene.String()
    district_code = graphene.String()
    district_name_en = graphene.String()
    district_name_bn = graphene.String()
    routing_number = graphene.String()
    parent_id = graphene.UUID()
    contact_number = graphene.String()
    type = graphene.String()
    status = graphene.String()


class WorkforceEmployeeDependentInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    eis_insurance_no = graphene.String()
    name_en = graphene.String(required=True)
    name_bn = graphene.String()
    father_name_bn = graphene.String()
    father_name_en = graphene.String()
    mother_name_bn = graphene.String()
    mother_name_en = graphene.String()
    marital_status = graphene.String(required=True)
    gender = graphene.String(required=True)
    occupation = graphene.String(required=True)
    email = graphene.String()
    phone_number = graphene.String(required=True)
    birth_date = graphene.String(required=True)
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    bank = graphene.String()
    bank_account_no = graphene.String()
    bank_account_holder_name = graphene.String()
    eis_payment_type = graphene.String()
    eis_calculated_amount = graphene.String()
    eis_approved_amount = graphene.String()
    eis_initial_monthly_amount = graphene.String()
    eis_monthly_amount = graphene.String()
    pv_factor = graphene.String()
    initial_replacement_rate = graphene.String()
    parent_dependent = graphene.String()
    present_location_id = graphene.String()
    permanent_location_id = graphene.String()
    present_address = graphene.String()
    permanent_address = graphene.String()
    life_status = graphene.String(required=True)
    death_date = graphene.String()
    disability_status = graphene.String()
    disability_type = graphene.String()
    relation_with_worker = graphene.String(required=True)
    last_verification_date = graphene.String()
    percentage_of_cf_grant = graphene.String()
    banking_info_id = graphene.String()
    status = graphene.String()
    is_eligible = graphene.Boolean()
    account_holder_type = graphene.String()
    account_holder_relation_with_dependent = graphene.String()
    attachments = graphene.String()
    account_holder_dob = graphene.String()
    account_holder_nid = graphene.String()
    remarks = graphene.String()


class WorkforceEmployeeAccidentInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String()
    employee_id = graphene.String(required=True)
    injury_type = graphene.String(required=True)
    accident_date = graphene.String(required=True)
    accident_time = graphene.String(required=True)
    accident_type = graphene.String(required=True)
    duty_status = graphene.String(required=True)
    in_outside_factory = graphene.String(required=True)
    death_date = graphene.String()
    description = graphene.String()
    accident_location_id = graphene.String(required=True)
    rejoin_date = graphene.String()
    status = graphene.String()


class WorkforceEmployeeAccountInfoInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    beneficiary_type = graphene.String(required=True)
    beneficiary_id = graphene.String(required=True)
    on_behalf_of = graphene.String(required=True)
    present_location_id = graphene.String(required=True)
    permanent_location_id = graphene.String()
    bank_id = graphene.String(required=True)
    branch_id = graphene.String(required=True)
    account_holder_name = graphene.String(required=True)
    account_owner_name = graphene.String(required=True)
    account_number = graphene.String(required=True)
    status = graphene.String()


class WorkforceApplicationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_employee_id = graphene.String()
    workforce_employee_verification = graphene.String()
    workforce_employee_verification_remarks = graphene.String()
    employee_designation_info = graphene.String()
    employee_document_info = graphene.String()
    employee_bank_info = graphene.String()
    employee_bank_info_verification = graphene.String()
    employee_bank_info_verification_remarks = graphene.String()
    employee_dependent_info = graphene.String()
    employee_dependent_info_verification = graphene.String()
    employee_dependent_info_verification_remarks = graphene.String()
    employee_accident_info = graphene.String()
    employee_accident_info_verification = graphene.String()
    employee_accident_info_verification_remarks = graphene.String()
    employee_children_info = graphene.String()
    employee_children_info_verification = graphene.String()
    employee_children_info_verification_remarks = graphene.String()
    applicant_info = graphene.String()
    applicant_info_verification = graphene.String()
    applicant_info_verification_remarks = graphene.String()
    institution_info = graphene.String()
    institution_info_verification = graphene.String()
    institution_info_verification_remarks = graphene.String()
    doctors_entry = graphene.String()
    doctors_entry_verification = graphene.String()
    doctors_entry_verification_remarks = graphene.String()
    organization_id = graphene.String()
    organization_type = graphene.String()
    employee_employer_id = graphene.String()
    employee_factory_id = graphene.String()
    application_type = graphene.String()
    association_type = graphene.String()
    is_submitted = graphene.String()
    verified_by = graphene.Boolean()
    phone_number = graphene.String()
    cf_application_summary_id = graphene.String()
    eis_application_summary_id = graphene.String()
    blwf_application_summary_id = graphene.String()
    grant_money_id = graphene.String()
    metadata = graphene.String()
    metadata_verification = graphene.String()
    metadata_verification_remarks = graphene.String()
    grant_amount = graphene.String()
    submitted_by = graphene.String()
    application_for = graphene.String()
    last_base_salary = graphene.String()
    doctors_diagnosis = graphene.String()
    doctors_recommended_donation = graphene.String()
    doctors_flag = graphene.String()
    doctors_flag_note = graphene.String()
    eis_payment_type = graphene.String()
    eis_calculated_amount = graphene.String()
    eis_approved_amount = graphene.String()
    eis_initial_monthly_amount = graphene.String()
    eis_monthly_amount = graphene.String()
    pv_factor = graphene.String()
    initial_replacement_rate = graphene.String()
    deceased_worker_info = graphene.String()
    deceased_worker_info_verification = graphene.String()
    deceased_worker_info_verification_remarks = graphene.String()
    status = graphene.String()
    eis_approval_ids= graphene.String()
    eis_approved_by_ids= graphene.String()


class WorkforceDocumentTypeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    field_id = graphene.String()
    application_type = graphene.String()
    organization_type = graphene.String()
    application_for = graphene.String()
    document_type_no = graphene.Int()
    document_type = graphene.String()
    dependent_id = graphene.String()
    document_count = graphene.String()
    name_bn = graphene.String()
    name_en = graphene.String()
    workforce_disease = graphene.String()
    mandatory_for_applicant = graphene.Boolean()
    form_step_no = graphene.String()
    status = graphene.String()


class WorkforceDocumentMapInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_document_type_id = graphene.UUID()
    mapped_by_id = graphene.String()
    type = graphene.String()
    status = graphene.String()


class WorkforceUserInputType(OpenIMISMutation.Input):
    client_mutation_label = graphene.String(required=False)
    id = graphene.String(required=False)
    name_bn = graphene.String(required=True)
    first_name_en = graphene.String(required=True)
    last_name_en = graphene.String()
    nid = graphene.String(required=True)
    birth_certificate_no = graphene.String()
    phone_number = graphene.String(required=True)
    status = graphene.String()


class WorkforceOtpInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    status = graphene.String(required=True)
    name_bn = graphene.String()
    first_name_en = graphene.String()
    nid = graphene.String()
    birth_certificate_no = graphene.String()
    phone_number = graphene.String()


class WorkforceApplicationMovementInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    application_id = graphene.String(required=True)
    note = graphene.String()
    action = graphene.String()
    to_employee_record_id = graphene.String()
    from_employee_record_id = graphene.String()
    application_from_id = graphene.String()
    application_to_id = graphene.String()
    deadline_date = graphene.String()
    is_reverted = graphene.Boolean()
    reverting_date = graphene.String()
    reverted_by_id = graphene.String()
    from_office_designation_id = graphene.String()
    to_office_designation_id = graphene.String()
    from_role_id = graphene.String()
    to_role_id = graphene.String()
    revert_note = graphene.String()
    status = graphene.String()


class WorkforceApplicationSummaryInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    application_data = graphene.String()
    meeting_date = graphene.String()
    remarks = graphene.String()
    name = graphene.String()
    status = graphene.String()
    organization_type = graphene.String()
    section_type = graphene.String()
    year = graphene.Int()
    month = graphene.String()


class WorkforceApplicationSummaryMovementInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    application_summary_id = graphene.UUID()
    comment = graphene.String()
    action = graphene.String()
    from_workforce_organization_employee_id = graphene.UUID()
    to_workforce_organization_employee_id = graphene.UUID()
    is_current = graphene.Boolean()
    is_cc = graphene.Boolean()
    is_committee_head = graphene.Boolean()
    is_committee_member = graphene.Boolean()
    deadline_date = graphene.String()
    is_reverted = graphene.Boolean()
    reverting_date = graphene.String()
    reverted_by_id = graphene.String()
    revert_note = graphene.String()
    status = graphene.String()


class WorkforceGrantMoneyInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    organization_type = graphene.String()
    application_type = graphene.String()
    application_type_name_bn = graphene.String()
    application_type_name_en = graphene.String()
    grant_money = graphene.Float()
    application_type_no = graphene.String()
    status = graphene.String()


class WorkforceDiseasesInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    grade = graphene.String(required=True)
    disease_type = graphene.String()
    disease_name = graphene.String()
    disease_no = graphene.String(required=True)
    documents = graphene.String()
    minimum_donation_amount = graphene.Float(required=True)
    maximum_donation_amount = graphene.Float(required=True)
    status = graphene.String()


class WorkforceEducationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    application_id = graphene.String(required=True)
    workforce_employee_id = graphene.String(required=False)
    workforce_dependant_id = graphene.String(required=False)
    education_level = graphene.String(required=False)
    applicant_type = graphene.String(required=False)
    education_board = graphene.String(required=False)
    passing_year = graphene.String(required=False)
    roll_number = graphene.String(required=False)
    registration_number = graphene.String(required=False)
    result = graphene.String(required=False)
    institution = graphene.String(required=False)
    child_name_en = graphene.String(required=False)
    child_name_bn = graphene.String(required=False)
    child_birth_date = graphene.String(required=False)
    child_nid_no = graphene.String(required=False)
    child_birth_certificate_no = graphene.String(required=False)
    study_class = graphene.String(required=False)


class WorkforceEmployeeBankingInfoInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    name_bn = graphene.String(required=False)
    name_en = graphene.String(required=False)
    account_holder_name = graphene.String(required=False)
    employee_id = graphene.String(required=False)
    application_id = graphene.String(required=False)
    dependant_id = graphene.String(required=False)
    branch_id = graphene.String(required=False)
    type = graphene.String(required=False)
    amount = graphene.String(required=False)
    account_no = graphene.String(required=False)
    bank_account_type = graphene.String(required=False)
    nid = graphene.String(required=False)
    date_of_birth = graphene.String(required=False)
    relation_with_dependent = graphene.String(required=False)
    status = graphene.String()
    account_holder_type = graphene.String()
    parent_dependent_id = graphene.String()


class WorkforcePostofficeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    w_code = graphene.String(required=True)
    post_code = graphene.String()
    post_office = graphene.String()
    name_en = graphene.String()
    name_bn = graphene.String()
    status = graphene.String()


class WorkforceApplicationBulkUpdateInputType(graphene.InputObjectType):
    id = graphene.String(required=False)
    workforce_employee_id = graphene.String()
    employee_designation_info = graphene.String()
    employee_document_info = graphene.String()
    employee_bank_info = graphene.String()
    employee_dependent_info = graphene.String()
    employee_accident_info = graphene.String()
    employee_children_info = graphene.String()
    applicant_info = graphene.String()
    institution_info = graphene.String()
    organization_id = graphene.String()
    organization_type = graphene.String()
    employee_employer_id = graphene.String()
    employee_factory_id = graphene.String()
    application_type = graphene.String()
    association_type = graphene.String()
    is_submitted = graphene.String()
    verified_by = graphene.Boolean()
    phone_number = graphene.String()
    cf_application_summary_id = graphene.String()
    eis_application_summary_id = graphene.String()
    blwf_application_summary_id = graphene.String()
    grant_money_id = graphene.String()
    metadata = graphene.String()
    grant_amount = graphene.String()
    submitted_by = graphene.String()
    application_for = graphene.String()
    status = graphene.String()


class WorkforceInteractiveUserInputType(OpenIMISMutation.Input):
    id = graphene.String()
    last_name = graphene.String()
    other_names = graphene.String()
    phone = graphene.String()
    email_id = graphene.String()


class WorkforceEisPaymentProcessInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application = graphene.String()
    workforce_application_summary = graphene.String()
    workforce_employee_dependent = graphene.String()
    bank = graphene.String()
    bank_account_no = graphene.String()
    bank_account_holder_name = graphene.String()
    eis_payment_type = graphene.String()
    eis_calculated_amount = graphene.String()
    eis_approved_amount = graphene.String()
    eis_monthly_amount = graphene.String()
    month_index = graphene.String()
    year = graphene.String()
    processing_date = graphene.String()
    processed_by = graphene.String()
    is_disbursed = graphene.Boolean()


class WorkforceEisPaymentDisbursementInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application = graphene.String()
    workforce_application_summary = graphene.String()
    workforce_employee_dependent = graphene.String()
    bank = graphene.String()
    bank_account_no = graphene.String()
    bank_account_holder_name = graphene.String()
    eis_payment_type = graphene.String()
    eis_calculated_amount = graphene.String()
    eis_approved_amount = graphene.String()
    eis_monthly_amount = graphene.String()
    month_index = graphene.String()
    year = graphene.String()
    disbursement_date = graphene.String()
    disbursed_by = graphene.String()


class WorkforceAllAssociationInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    name_bn = graphene.String()
    name_en = graphene.String()
    address = graphene.String()
    email = graphene.String()
    phone = graphene.String()
    short_name_bn = graphene.String()
    short_name_en = graphene.String()
    web_address = graphene.String()
    status = graphene.String()
    minimum_salary = graphene.String()
    start_date= graphene.String()


class WorkforceOtherCompensationInfoInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    workforce_application_id = graphene.String(required=False)
    received_from_organization = graphene.String(required=False)
    entry_by = graphene.String(required=False)
    date_of_compensation = graphene.String(required=False)
    amount = graphene.String(required=False)
    status_of_payment = graphene.String(required=False)
    is_eis_benefit_adjustment_eligible = graphene.String(required=False)
    remarks = graphene.String(required=False)
    payment_type = graphene.String(required=False)



class WorkforceAssociationUserMapInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    all_association_id = graphene.String(required=False)
    user_id = graphene.Int(required=False)


class WorkforceEisBankAdviceInputType(OpenIMISMutation.Input):
    advice_date = graphene.String()
    is_confirmed = graphene.Boolean()
    remarks = graphene.String()
    month= graphene.String()
    year = graphene.String()


class WorkforceCommitteeInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    name_en = graphene.String(required=True)
    name_bn = graphene.String(required=False)
    associations = graphene.JSONString(required=False)


class WorkforceCommitteeAssociationMapInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    committee_id = graphene.UUID(required=True)
    all_association_id = graphene.UUID(required=True)


class WorkforceCommitteeUserInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    login_name = graphene.String(required=False)
    representative_name = graphene.String(required=False)
    organization_name = graphene.String(required=False)
    designation = graphene.String(required=False)
    representative_type = graphene.String(required=False)
    committee_role = graphene.String(required=False)
    phone_number = graphene.String(required=False)
    email = graphene.String(required=False)
    office_address = graphene.String(required=False)
    current_address = graphene.String(required=False)
    related_user_id = graphene.Int(required=False)


class WorkforceCommitteeUserMapInputType(OpenIMISMutation.Input):
    id = graphene.String(required=False)
    committee_id = graphene.UUID(required=True)
    user_id = graphene.Int(required=True)
