# Generated by Django 4.2.16 on 2024-12-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforcefactory',
            old_name='workforce_employer_id',
            new_name='workforce_employer',
        ),
        migrations.RenameField(
            model_name='historicalworkforceorganizationunit',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='workforcefactory',
            old_name='workforce_employer_id',
            new_name='workforce_employer',
        ),
        migrations.RenameField(
            model_name='workforceorganizationunit',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
