# Generated by Django 4.2.16 on 2024-12-31 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_alter_historicalworkforceemployee_email_and_more'),
    ]

    operations = [
        # Drop the old foreign key fields
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='employer_id',
        ),

        # Recreate the fields with UUID-based foreign keys
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='employer_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='workforce.workforceemployer',
            ),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='employer_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='workforce.workforceemployer',
            ),
        ),
    ]
