# Generated by Django 4.2.16 on 2025-01-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_remove_historicalworkforceorganizationemployee_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceorganizationemployeedesignation',
            name='released_by',
        ),
        migrations.RemoveField(
            model_name='workforceorganizationemployeedesignation',
            name='released_by',
        ),
    ]
