# Generated by Django 4.2.16 on 2025-01-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_alter_workforceorganizationemployeedesignation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforceorganizationemployeedesignation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='designations', to='workforce.workforceorganizationemployee'),
        ),
    ]
