# Generated by Django 4.2.16 on 2025-01-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0013_alter_workforceorganizationemployeedesignation_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceemployee',
            old_name='employer_id',
            new_name='workforce_employer',
        ),
        migrations.RenameField(
            model_name='workforceemployee',
            old_name='employer_id',
            new_name='workforce_employer',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='employee_id_lima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='employee_type',
            field=models.CharField(blank=True, db_comment='office/factory employee', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='workforce_office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceoffice'),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='employee_id_lima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='employee_type',
            field=models.CharField(blank=True, db_comment='office/factory employee', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='workforce_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceoffice'),
        ),
    ]
