# Generated by Django 4.2.16 on 2025-01-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_alter_workforceorganizationunitdesignation_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforceorganizationunitdesignation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_designations', to='workforce.workforceorganizationunit'),
        ),
    ]
