# Generated by Django 4.2.16 on 2025-01-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0016_alter_workforceorganizationunitdesignation_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='is_same_company_representative',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceoffice',
            name='is_same_company_representative',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='is_same_company_representative',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceoffice',
            name='is_same_company_representative',
            field=models.CharField(blank=True, null=True),
        ),
    ]
