# Generated by Django 4.2.16 on 2025-01-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0017_historicalworkforcefactory_is_same_company_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcefactory',
            name='is_same_company_representative',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalworkforceoffice',
            name='is_same_company_representative',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='is_same_company_representative',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='is_same_company_representative',
            field=models.SmallIntegerField(default=0),
        ),
    ]
