# Generated by Django 4.2.16 on 2025-02-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0020_add_senior_officer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforceorganizationemployeedesignation',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_designations', to='workforce.workforceorganizationunitdesignation'),
        ),
    ]
