# Generated by Django 4.2.16 on 2025-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0021_alter_workforceorganizationemployeedesignation_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceemployee',
            old_name='fathers_name',
            new_name='father_name_bn',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployee',
            old_name='mothers_name',
            new_name='father_name_en',
        ),
        migrations.RenameField(
            model_name='workforceemployee',
            old_name='fathers_name',
            new_name='father_name_bn',
        ),
        migrations.RenameField(
            model_name='workforceemployee',
            old_name='mothers_name',
            new_name='father_name_en',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='name_bn',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='workforce_employer',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='workforce_factory',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='workforce_office',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='name_bn',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='workforce_employer',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='workforce_factory',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='workforce_office',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='citizenship',
            field=models.CharField(default='Bangladeshi', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='first_name_bn',
            field=models.CharField(blank=True, db_comment='Translatable first name field. May use any language', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='last_name_bn',
            field=models.CharField(blank=True, db_comment='Translatable last name field. May use any language', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='other_name',
            field=models.CharField(blank=True, db_comment='Other name field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='privacy_law',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='spouse_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='spouse_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='citizenship',
            field=models.CharField(default='Bangladeshi', max_length=50),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='first_name_bn',
            field=models.CharField(blank=True, db_comment='Translatable first name field. May use any language', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='last_name_bn',
            field=models.CharField(blank=True, db_comment='Translatable last name field. May use any language', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='other_name',
            field=models.CharField(blank=True, db_comment='Other name field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='privacy_law',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='spouse_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='spouse_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
