# Generated by Django 4.2.16 on 2025-02-16 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0023_bank_historicalbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='insurance_number',
            field=models.CharField(db_index=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='life_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='insurance_number',
            field=models.CharField(max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='life_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
