# Generated by Django 4.2.16 on 2025-02-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0024_historicalworkforceemployee_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceorganization',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceorganization',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
