# Generated by Django 4.2.16 on 2025-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0025_historicalworkforceorganization_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='name_bn',
        ),
        migrations.RenameField(
            model_name='historicalbank',
            old_name='name',
            new_name='name_bn',
        ),
        migrations.AddField(
            model_name='bank',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
