# Generated by Django 4.2.16 on 2025-02-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0026_rename_name_bank_name_bn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='historicalbank',
            name='branch_name',
        ),
    ]
