# Generated by Django 4.2.16 on 2025-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0028_workforceemployeeguardian_workforceemployeedependent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforceemployeeguardian',
            name='permanent_location',
        ),
        migrations.RemoveField(
            model_name='workforceemployeeguardian',
            name='present_location',
        ),
        migrations.RemoveField(
            model_name='workforceemployeeguardian',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='workforceemployeeguardian',
            name='user_updated',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='disability_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='disability_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='eis_insurance_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='eis_insurance_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalWorkforceEmployeeGuardian',
        ),
        migrations.DeleteModel(
            name='WorkforceEmployeeGuardian',
        ),
    ]
