# Generated by Django 4.2.16 on 2025-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0029_remove_workforceemployeeguardian_permanent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
