# Generated by Django 4.2.16 on 2025-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0032_workforceemployeeaccident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccident',
            name='accident_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='accident_time',
            field=models.CharField(),
        ),
    ]
