# Generated by Django 4.2.16 on 2025-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0033_alter_historicalworkforceemployeeaccident_accident_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccident',
            name='duty_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='duty_status',
            field=models.CharField(max_length=30),
        ),
    ]
