# Generated by Django 4.2.16 on 2025-02-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0034_alter_historicalworkforceemployeeaccident_duty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedesignation',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployee'),
        ),
        migrations.AddField(
            model_name='workforceemployeedesignation',
            name='employee_id',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_designation_employee_id', to='workforce.workforceemployee'),
            preserve_default=False,
        ),
    ]
