# Generated by Django 4.2.16 on 2025-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0035_historicalworkforceemployeedesignation_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedesignation',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedesignation',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
