# Generated by Django 4.2.16 on 2025-02-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0036_historicalworkforceemployeedesignation_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceemployeedesignation',
            old_name='employee_id',
            new_name='workforce_employee',
        ),
        migrations.RenameField(
            model_name='workforceemployeedesignation',
            old_name='employee_id',
            new_name='workforce_employee',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedesignation',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedesignation',
            name='factory_id',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedesignation',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedesignation',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedesignation',
            name='factory_id',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedesignation',
            name='office_id',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedesignation',
            name='workforce_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployer'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedesignation',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedesignation',
            name='workforce_office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceoffice'),
        ),
        migrations.AddField(
            model_name='workforceemployeedesignation',
            name='workforce_company',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceemployer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workforceemployeedesignation',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='workforceemployeedesignation',
            name='workforce_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceoffice'),
        ),
    ]
