# Generated by Django 4.2.16 on 2025-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0038_workforceemployeeaccountinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccountinfo',
            name='beneficiary_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='beneficiary_id',
            field=models.CharField(max_length=50),
        ),
    ]
