# Generated by Django 4.2.16 on 2025-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0039_alter_historicalworkforceemployeeaccountinfo_beneficiary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
