# Generated by Django 4.2.16 on 2025-03-10 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0041_workforcetemporaryapplication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalWorkforceTemporaryApplication',
            new_name='HistoricalWorkforceApplication',
        ),
        migrations.RenameModel(
            old_name='WorkforceTemporaryApplication',
            new_name='WorkforceApplication',
        ),
        migrations.AlterModelOptions(
            name='historicalworkforceapplication',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical workforce application', 'verbose_name_plural': 'historical workforce applications'},
        ),
        migrations.AlterModelTable(
            name='workforceapplication',
            table='workforce_applications',
        ),
    ]
