# Generated by Django 4.2.16 on 2025-03-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0041_workforceapplication_historicalworkforceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_bank_application', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeeaccident',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedesignation',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_document_application', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='workforceemployeeaccident',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_employee_accident_application', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_employee_dependent_application', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='workforceemployeedesignation',
            name='workforce_application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_designation_application', to='workforce.workforceapplication'),
        ),
    ]
