# Generated by Django 4.2.16 on 2025-03-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0042_bank_workforce_application_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='historicalbank',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='historicalworkforcedocument',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeeaccident',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedesignation',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='workforcedocument',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='workforceemployeeaccident',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
        migrations.RenameField(
            model_name='workforceemployeedesignation',
            old_name='workforce_application_id',
            new_name='workforce_application',
        ),
    ]
