# Generated by Django 4.2.16 on 2025-03-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0042_rename_historicalWorkforceApplication_historicalworkforceapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganization'),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_application_organization', to='workforce.workforceorganization'),
        ),
    ]
