# Generated by Django 4.2.16 on 2025-03-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0043_rename_workforce_application_id_bank_workforce_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeeaccountinfo',
            name='account_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeeaccountinfo',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.bank'),
        ),
        migrations.AddField(
            model_name='workforceemployeeaccountinfo',
            name='account_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeeaccountinfo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_dependent_branch', to='workforce.bank'),
        ),
    ]
