# Generated by Django 4.2.16 on 2025-03-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0044_historicalworkforceemployeeaccountinfo_account_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_employer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployer'),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeeaccident',
            name='rejoin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceemployer'),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='workforceemployeeaccident',
            name='rejoin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
