# Generated by Django 4.2.16 on 2025-03-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_exportablequerymodel_file_format'),
        ('workforce', '0046_remove_historicalworkforceapplication_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_related_user', to='core.interactiveuser'),
        ),
    ]
