# Generated by Django 4.2.16 on 2025-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0047_alter_historicalworkforceemployee_insurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='application_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='organization_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='application_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='organization_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
