# Generated by Django 4.2.16 on 2025-03-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0048_historicalworkforceapplication_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='is_submitted',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='is_submitted',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
