# Generated by Django 4.2.16 on 2025-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0050_workforcedocumenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='application_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='document_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='document_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='field_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='name_bn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='application_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='document_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='document_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='field_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='name_bn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
