# Generated by Django 4.2.16 on 2025-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0053_workforcedocumentmap_historicalworkforcedocumentmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='path',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='workforce_documents/'),
        ),
    ]
