# Generated by Django 4.2.20 on 2025-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0054_alter_historicalworkforcedocument_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255)),
                ('first_name_en', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(default=' ', max_length=255)),
                ('nid', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'workforce_user',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='verified_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='verified_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
