# Generated by Django 4.2.20 on 2025-05-05 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0054_alter_historicalworkforcedocument_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_bn', models.CharField(max_length=255)),
                ('first_name_en', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(default=' ', max_length=255)),
                ('nid', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'workforce_user',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='verified_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='verified_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
