# Generated by Django 4.2.20 on 2025-05-07 06:34

from django.db import migrations, models
import django.utils.timezone
import uuid
import workforce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0055_workforceuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_bn', models.CharField(max_length=255)),
                ('first_name_en', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(default=' ', max_length=255)),
                ('nid', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp', models.CharField(default=workforce.models.generate_otp, max_length=6)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=workforce.models.expiry_time)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'workforce_otp',
                'managed': True,
            },
        ),
    ]
