# Generated by Django 4.2.20 on 2025-05-07 06:34

from django.db import migrations, models
from django.db import connection
import django.utils.timezone
import uuid
import workforce.models
import os
import datetime
import json


def truncate_locations(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('TRUNCATE TABLE "tblLocations" RESTART IDENTITY CASCADE;')


def seed_locations(apps, schema_editor):
    Location = apps.get_model('location', 'Location')
    file_path = os.path.join(os.path.dirname(__file__), 'combined_locations.json')

    with open(file_path, 'r', encoding='utf-8-sig') as f:
        content = f.read()
        try:
            data = json.loads(content)
        except json.JSONDecodeError as e:
            print("JSON Decode Error:", e)

    # Order matters: divisions → districts → upazillas → unions
    for division in data.get('divisions', []):
        item = {
            "id": division['LocationId'],
            "type": division['LocationType'],
            "code": division['LocationCode'],
            "name": division['LocationName'],
            "audit_user_id": division['AuditUserId'],
            "parent": None,
            "uuid": uuid.uuid4(),
            "validity_from": datetime.datetime.now(),
        }
        Location.objects.create(**item)

    for district in data.get('districts', []):
        item = {
            "id": district['LocationId'],
            "type": district['LocationType'],
            "code": district['LocationCode'],
            "name": district['LocationName'],
            "audit_user_id": district['AuditUserId'],
            "parent": Location.objects.get(id=district['ParentLocationId']),
            "uuid": uuid.uuid4(),
            "validity_from": datetime.datetime.now(),
        }

        Location.objects.create(**item)

    for upazila in data.get('upazilas', []):
        item = {
            "id": upazila['LocationId'],
            "type": upazila['LocationType'],
            "code": upazila['LocationCode'],
            "name": upazila['LocationName'],
            "audit_user_id": upazila['AuditUserId'],
            "parent": Location.objects.get(id=upazila['ParentLocationId']),
            "uuid": uuid.uuid4(),
            "validity_from": datetime.datetime.now(),
        }

        Location.objects.create(**item)
    #
    for union in data.get('unions', []):
        item = {
            "id": union['LocationId'],
            "type": union['LocationType'],
            "code": union['LocationCode'],
            "name": union['LocationName'],
            "audit_user_id": union['AuditUserId'],
            "parent": Location.objects.get(id=union['ParentLocationId']),
            "uuid": uuid.uuid4(),
            "validity_from": datetime.datetime.now(),
        }

        Location.objects.create(**item)


class Migration(migrations.Migration):
    dependencies = [
        ('workforce', '0056_workforceotp'),
    ]

    operations = [
        migrations.RunPython(truncate_locations),
        migrations.RunPython(seed_locations),
    ]
