# Generated by Django 4.2.20 on 2025-05-20 06:01

import core.fields
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0057_add_role_checker_approver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceApplicationMovement',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('is_cc', models.BooleanField(blank=True, null=True)),
                ('is_committee_head', models.BooleanField(blank=True, null=True)),
                ('is_committee_member', models.BooleanField(blank=True, null=True)),
                ('to_employee_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_employee_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_employee_designation_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_designation_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_office_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_office_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_employee_unit_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_unit_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_username', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_id', to='workforce.workforceapplication')),
                ('from_employee_record_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_employee_record_id', to='workforce.workforceorganizationemployee')),
                ('from_office_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_office_id', to='workforce.workforceorganization')),
                ('from_office_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_office_unit_id', to='workforce.workforceorganizationunit')),
                ('from_office_unit_organogram_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_office_unit_organogram_id', to='workforce.workforceorganizationunitdesignation')),
                ('to_employee_record_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_employee_record_id', to='workforce.workforceorganizationemployee')),
                ('to_office_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_office_id', to='workforce.workforceorganization')),
                ('to_office_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_office_unit_id', to='workforce.workforceorganizationunit')),
                ('to_office_unit_organogram_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_office_unit_organogram_id', to='workforce.workforceorganizationunitdesignation')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workforce_application_movement',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkforceApplicationMovement',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('is_cc', models.BooleanField(blank=True, null=True)),
                ('is_committee_head', models.BooleanField(blank=True, null=True)),
                ('is_committee_member', models.BooleanField(blank=True, null=True)),
                ('to_employee_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_employee_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_employee_designation_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_designation_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_office_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_office_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('to_employee_unit_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_unit_name_bng', models.CharField(blank=True, max_length=255, null=True)),
                ('from_employee_username', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication')),
                ('from_employee_record_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationemployee')),
                ('from_office_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganization')),
                ('from_office_unit_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationunit')),
                ('from_office_unit_organogram_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationunitdesignation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_employee_record_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationemployee')),
                ('to_office_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganization')),
                ('to_office_unit_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationunit')),
                ('to_office_unit_organogram_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationunitdesignation')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical workforce application movement',
                'verbose_name_plural': 'historical workforce application movements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
