# Generated by Django 4.2.20 on 2025-05-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0058_workforceapplicationmovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_employee_record_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_employee_record', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_office_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_office', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_office_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_office_unit', to='workforce.workforceorganizationunit'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_office_unit_organogram_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_office_unit_organogram', to='workforce.workforceorganizationunitdesignation'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_employee_record_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_employee_record', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_office_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_office', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_office_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_office_unit', to='workforce.workforceorganizationunit'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_office_unit_organogram_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_office_unit_organogram', to='workforce.workforceorganizationunitdesignation'),
        ),
    ]
