# Generated by Django 4.2.20 on 2025-05-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0059_alter_workforceapplicationmovement_application_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='from_employee_record_id',
            new_name='from_employee_record',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='from_office_id',
            new_name='from_office',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='from_office_unit_id',
            new_name='from_office_unit',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='from_office_unit_organogram_id',
            new_name='from_office_unit_organogram',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='to_employee_record_id',
            new_name='to_employee_record',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='to_office_id',
            new_name='to_office',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='to_office_unit_id',
            new_name='to_office_unit',
        ),
        migrations.RenameField(
            model_name='historicalworkforceapplicationmovement',
            old_name='to_office_unit_organogram_id',
            new_name='to_office_unit_organogram',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='from_employee_record_id',
            new_name='from_employee_record',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='from_office_id',
            new_name='from_office',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='from_office_unit_id',
            new_name='from_office_unit',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='from_office_unit_organogram_id',
            new_name='from_office_unit_organogram',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='to_employee_record_id',
            new_name='to_employee_record',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='to_office_id',
            new_name='to_office',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='to_office_unit_id',
            new_name='to_office_unit',
        ),
        migrations.RenameField(
            model_name='workforceapplicationmovement',
            old_name='to_office_unit_organogram_id',
            new_name='to_office_unit_organogram',
        ),
    ]
