# Generated by Django 4.2.20 on 2025-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0060_rename_application_id_historicalworkforceapplicationmovement_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceapplication',
            name='is_submitted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='is_submitted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
