# Generated by Django 4.2.20 on 2025-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0061_alter_historicalworkforceapplication_is_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
