# Generated by Django 4.2.20 on 2025-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0062_historicalworkforceapplication_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
