# Generated by Django 4.2.20 on 2025-05-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0063_historicalworkforceapplication_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplicationmovement',
            name='is_reverted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationmovement',
            name='revert_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationmovement',
            name='reverted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationmovement',
            name='reverting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationmovement',
            name='is_reverted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationmovement',
            name='revert_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationmovement',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reverted_by', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AddField(
            model_name='workforceapplicationmovement',
            name='reverting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
