# Generated by Django 4.2.20 on 2025-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0064_historicalworkforceapplicationmovement_is_reverted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='path',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='path',
            field=models.CharField(blank=True, null=True),
        ),
    ]
