# Generated by Django 4.2.16 on 2025-05-31

from django.db import migrations
from django.conf import settings
import uuid


def add_more_workforce_document_types(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    try:
        user = User.objects.get(username="Admin")
        user_id = user.id
    except User.DoesNotExist:
        user_id = None

    new_data = [
        {
            "id": uuid.uuid4(),
            "field_id": "medicalAssistance_recommendation_letter",
            "application_type": "medicalAssistance",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "field_id": "financialAssistance_recommendation_letter",
            "application_type": "financialAssistance",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "field_id": "disabilityAssistance_recommendation_letter",
            "application_type": "disabilityAssistance",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "field_id": "scholarship_recommendation_letter",
            "application_type": "scholarship",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "field_id": "medicalDonation_recommendation_letter",
            "application_type": "medicalDonation",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "field_id": "educationGrant_recommendation_letter",
            "application_type": "educationGrant",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
    ]

    for item in new_data:
        WorkforceDocumentType.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0065_alter_historicalworkforcedocument_path_and_more'),
    ]

    operations = [
        migrations.RunPython(add_more_workforce_document_types),
    ]
