# Generated by Django 4.2.20 on 2025-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0067_add_more_workforce_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforceuser',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceuser',
            name='nid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
