# Generated by Django 4.2.20 on 2025-06-02 08:33

from django.db import migrations, models
import workforce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0068_workforceuser_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforceotp',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceotp',
            name='otp',
            field=models.CharField(blank=True, default=workforce.models.generate_otp, max_length=6, null=True),
        ),
    ]
