# Generated by Django 4.2.20 on 2025-06-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0070_workforceapplicationsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='application_summary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceapplicationsummary'),
        ),
    ]
