# Generated by Django 4.2.20 on 2025-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0071_historicalworkforceapplication_application_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplicationsummarymovement',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummarymovement',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
