# Generated by Django 4.2.20 on 2025-06-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0072_historicalworkforceapplicationsummarymovement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplicationsummary',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationsummary',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummary',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummary',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
