# Generated by Django 4.2.16 on 2025-06-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0073_historicalworkforceapplicationsummary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplicationsummary',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationsummary',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummary',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummary',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
