# Generated by Django 4.2.16 on 2025-06-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0074_historicalworkforceapplicationsummary_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceapplication',
            old_name='application_summary',
            new_name='blwf_application_summary',
        ),
        migrations.RemoveField(
            model_name='workforceapplication',
            name='application_summary',
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='cf_application_summary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_application_summary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationsummary',
            name='organization_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='blwf_application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blwf_application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='cf_application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cf_application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eis_application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummary',
            name='organization_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
