# Generated by Django 4.2.20 on 2025-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0075_rename_application_summary_historicalworkforceapplication_blwf_application_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
