# Generated by Django 4.2.20 on 2025-06-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0078_workforcegrantmoney_seeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
