# Generated by Django 4.2.20 on 2025-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0080_more_workforcegrantmoney_seeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='grant_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='grant_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
