# Generated by Django 4.2.16 on 2025-07-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0081_historicalworkforceapplication_grant_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_children_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_children_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
