# Generated by Django 4.2.16 on 2025-07-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_code'),
        ('workforce', '0083_historicalworkforcegrantmoney_application_type_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforceemployee',
            name='permanent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_permanent_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='present_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_present_location', to='location.location'),
        ),
    ]
