# Generated by Django 4.2.16 on 2025-07-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0084_alter_workforceemployee_permanent_location_and_more'),
        ('workforce', '0084_workforcediseases_historicalworkforcediseases'),
    ]

    operations = [
    ]
