# Generated by Django 4.2.20 on 2025-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0085_merge_20250708_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='association_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='association_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
