# Generated by Django 4.2.20 on 2025-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0086_historicalworkforceapplication_association_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcediseases',
            name='disease_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcediseases',
            name='disease_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforcediseases',
            name='disease_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforcediseases',
            name='disease_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
