# Generated by Django 4.2.20 on 2025-07-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0089_seed_more_grantmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocumenttype',
            name='application_for',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumenttype',
            name='document_type_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumenttype',
            name='organization_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumenttype',
            name='application_for',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumenttype',
            name='document_type_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumenttype',
            name='organization_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
