# Generated by Django 4.2.20 on 2025-07-15 06:01

from django.db import migrations, models


def seed_application_type_names(apps, schema_editor):
    WorkforceGrantMoney = apps.get_model('workforce', 'WorkforceGrantMoney')

    cf_mapping = {
        'medicalAssistance': ('চিকিৎসা অনুদান', 'Medical assistance'),
        'scholarship': ('শিক্ষা অনুদান', 'Educational assistance'),
        'financialAssistance': ('মৃত্যুজনিত অনুদান', 'Death grant'),
        'maternityGrant': ('মাতৃত্বজনিত অনুদান', 'Maternity grant'),
        'disabilityAssistance': ('স্থায়ী ও আংশিক অক্ষমতা জনিত আর্থিক সহায়তা', 'Disability assistance'),
    }

    blwf_mapping = {
        'maternityGrant': ('মাতৃত্বজনিত অনুদান', 'Maternity grant'),
        'educationGrant': ('শিক্ষা অনুদান', 'Educational assistance'),
        'deadlyGrant': ('মৃত্যুজনিত অনুদান', 'Death grant'),
        'medicalDonation': ('চিকিৎসা অনুদান', 'Medical assistance'),
    }

    for app_type, (bn, en) in cf_mapping.items():
        WorkforceGrantMoney.objects.filter(
            organization_type='cf',
            application_type=app_type
        ).update(
            application_type_name_bn=bn,
            application_type_name_en=en
        )

    for app_type, (bn, en) in blwf_mapping.items():
        WorkforceGrantMoney.objects.filter(
            organization_type='blwf',
            application_type=app_type
        ).update(
            application_type_name_bn=bn,
            application_type_name_en=en
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0091_seed_updated_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcegrantmoney',
            name='application_type_name_bn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcegrantmoney',
            name='application_type_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforcegrantmoney',
            name='application_type_name_bn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforcegrantmoney',
            name='application_type_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(seed_application_type_names),
    ]
