# Generated by Django 4.2.20 on 2025-07-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0092_seed_historicalworkforcegrantmoney_application_type_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocumenttype',
            name='workforce_disease',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcediseases'),
        ),
        migrations.AddField(
            model_name='workforcedocumenttype',
            name='workforce_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disease', to='workforce.workforcediseases'),
        ),
    ]
