# Generated by Django 4.2.20 on 2025-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0094_add_more_seed_data_workforce_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='document_type',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='holder_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='document_type',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='holder_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
