# Generated by Django 4.2.20 on 2025-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0095_alter_historicalworkforcedocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='association_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='association_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
