# Generated by Django 4.2.20 on 2025-07-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0096_historicalworkforcefactory_association_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory', to='workforce.workforcefactory'),
        ),
    ]
