# Generated by Django 4.2.20 on 2025-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0097_historicalworkforcedocument_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
