# On 2025-07-17

from django.db import migrations
from django.conf import settings
import uuid


def seed_more_workforce_document_types(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    # Get admin user
    user = User.objects.get(username="Admin")
    user_id = user.id

    data = [
        {
            "id": uuid.uuid4(),
            "document_type_no": 260,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "medicalDonation_blwf_self_medical_certificate/prescription/discharge_certificate",
            "document_type": "medical certificate/prescription/discharge certificate",
            "document_count": "single",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট /চিকিৎসা ব্যবস্থাপত্র /চিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "medical certificate/prescription/discharge certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 261,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "medicalDonation_blwf_self_employee_nid",
            "document_type": "employee nid",
            "document_count": "single",
            "name_bn": "শ্রমিকের জাতীয় পরিচয়পত্র",
            "name_en": "employee nid",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 262,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "medicalDonation_blwf_self_employee_birth_cirtificate_copy",
            "document_type": "employee birth cirtificate copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "employee birth cirtificate copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 263,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "medicalDonation_blwf_self_employee_photo",
            "document_type": "employee photo",
            "document_count": "single",
            "name_bn": "শ্রমিকের ছবি",
            "name_en": "employee photo",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 264,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self_institutional",
            "field_id": "medicalDonation_blwf_self_institutional_employee_appointment_letter_copy",
            "document_type": "employee appointment letter copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের নিয়োপত্রের অনুলিপি",
            "name_en": "employee appointment letter",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 265,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "medicalDonation_blwf_self_Institutional_certificate_copy",
            "document_type": "Institutional certificate copy",
            "document_count": "single",
            "name_bn": "কাজের সনদ",
            "name_en": "Institutional certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 266,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self_non_institutional",
            "field_id": "medicalDonation_blwf_self_non_institutional_union_parishad_/_municipality_or_city_corporation",
            "document_type": "union parishad / municipality or city corporation",
            "document_count": "single",
            "name_bn": "ইউনিয়ন পরিষদ /পৌরসভা বা সিটি কর্পোরেশন সাটিফিকেট",
            "name_en": "union parishad / municipality or city corporation cirtificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 267,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "medicalDonation_blwf_dependent_family_nid",
            "document_type": "family nid",
            "document_count": "single",
            "name_bn": "পরিবারবর্গের জাতীয় পরিচয়পত্র",
            "name_en": "family nid",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 268,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "medicalDonation_blwf_dependent_family_birth_cirtificate_copy",
            "document_type": "family birth cirtificate copy",
            "document_count": "single",
            "name_bn": "পরিবারবর্গের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "family birth cirtificate copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 269,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "medicalDonation_blwf_dependent_family_photo",
            "document_type": "family photo",
            "document_count": "single",
            "name_bn": "পরিবারবর্গের ছবি",
            "name_en": "family photo",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 270,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "medicalDonation_blwf_dependent_inheritance_certificate_(main_copy)",
            "document_type": "inheritance certificate (main copy)",
            "document_count": "single",
            "name_bn": "ইউনিয়ন পরিষদ /পৌরসভা বা সিটি কর্পোরেশন হতে ওয়ারিশান সনদ (মূলকপি)",
            "name_en": "inheritance certificate (main copy)",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 271,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_nid_of_the_worker",
            "document_type": "nid of the worker",
            "document_count": "single",
            "name_bn": "শ্রমিকের জাতীয় পরিচয়পত্রের অনুলিপি",
            "name_en": "nid of the worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 272,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_employee_birth_cirtificate_copy",
            "document_type": "employee birth cirtificate copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "employee birth cirtificate copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 273,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_appointment_letter_of_worker",
            "document_type": "appointment letter of worker",
            "document_count": "single",
            "name_bn": "শ্রমিকের নিয়োগপত্রের অনুলিপি",
            "name_en": "appointment letter of worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 274,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_certified_copy_of_educational_certificate",
            "document_type": "certified copy of educational certificate",
            "document_count": "single",
            "name_bn": "শিক্ষা সনদের সত্যায়িত অনুলিপি",
            "name_en": "certified copy of educational certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 275,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_workers_photo",
            "document_type": "workers photo",
            "document_count": "single",
            "name_bn": "শ্রমিকের ছবি",
            "name_en": "photo of worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 276,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_recommendation_letter",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 277,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "educationGrant_blwf_self_last_educational_marksheet_copy",
            "document_type": "last educational marksheet copy",
            "document_count": "single",
            "name_bn": "সর্বশেষ পরীক্ষার মার্কশিটের কপি",
            "name_en": "last educational marksheet copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 278,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_nid_of_the_worker",
            "document_type": "nid of the worker",
            "document_count": "single",
            "name_bn": "শ্রমিকের জাতীয় পরিচয়পত্রের অনুলিপি",
            "name_en": "nid of the worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 279,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_employee_birth_cirtificate_copy",
            "document_type": "employee birth cirtificate copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "employee birth cirtificate copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 280,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_appointment_letter_of_worker",
            "document_type": "appointment letter of worker",
            "document_count": "single",
            "name_bn": "শ্রমিকের নিয়োগপত্রের অনুলিপি",
            "name_en": "appointment letter of worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 281,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_workers_photo",
            "document_type": "workers photo",
            "document_count": "single",
            "name_bn": "শ্রমিকের ছবি",
            "name_en": "photo of worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 282,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_certified_copy_of_educational_certificate",
            "document_type": "certified copy of educational certificate",
            "document_count": "single",
            "name_bn": "শিক্ষা সনদের সত্যায়িত অনুলিপি",
            "name_en": "certified copy of educational certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 283,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_nid_of_the_child_applying_for_education_gran",
            "document_type": "nid of the child applying for education gran",
            "document_count": "single",
            "name_bn": "শিক্ষা অনুদানের জন্য আবেদনকৃত সন্তানের জাতীয় পরিচয়পত্র",
            "name_en": "nid of the child applying for education gran",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 284,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_copy_of_the_birth_certificate_of_the_child_applying_for_education_grant",
            "document_type": "copy of the birth certificate of the child applying for education grant",
            "document_count": "single",
            "name_bn": "শিক্ষা অনুদানের জন্য আবেদনকৃত সন্তানের জন্ম সনদ পত্রের অনুলিপি",
            "name_en": "copy of the birth certificate of the child applying for education grant",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 285,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_1_copy_photo_of_the_child_applying_for_education_grant",
            "document_type": "1 copy photo of the child applying for education grant",
            "document_count": "single",
            "name_bn": "শিক্ষা অনুদানের জন্য আবেদনকৃত সন্তানের ১কপি ছবি",
            "name_en": "1 copy photo of the child applying for education grant",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 286,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_recommendation_letter",
            "document_type": "recommendation letter",
            "document_count": "single",
            "name_bn": "প্রাতিষ্ঠানিক অথবা ইউনিয়ন পরিষদ প্রদত্ত সুপারিশ পত্র",
            "name_en": "recommendation letter from an institution or Union Parishad",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 287,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_last_educational_marksheet_copy",
            "document_type": "last educational marksheet copy",
            "document_count": "single",
            "name_bn": "সর্বশেষ পরীক্ষার মার্কশিটের কপি",
            "name_en": "last educational marksheet copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 288,
            "application_type": "educationGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "educationGrant_blwf_dependent_scholarship_dependent_labour_foundation_grant_information",
            "document_type": "scholarship dependent labour foundation grant information",
            "document_count": "single",
            "name_bn": "শ্রমিকের জন্য স্কলারশিপ ভিত্তিক ফাউন্ডেশন অনুদানের তথ্য",
            "name_en": "scholarship dependent labour foundation grant information",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 289,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "maternityGrant_blwf_self_medical_certificate/prescription/discharge_certificate",
            "document_type": "medical certificate/prescription/discharge certificate",
            "document_count": "single",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট /চিকিৎসা ব্যবস্থাপত্র /চিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "medical certificate/prescription/discharge certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 290,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "maternityGrant_blwf_self_employee_nid",
            "document_type": "employee nid",
            "document_count": "single",
            "name_bn": "শ্রমিকের জাতীয় পরিচয়পত্র",
            "name_en": "employee nid",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 291,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "maternityGrant_blwf_self_employee_birth_cirtificate_copy",
            "document_type": "employee birth cirtificate copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "employee birth cirtificate copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 292,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "maternityGrant_blwf_self_employee_photo",
            "document_type": "employee photo",
            "document_count": "single",
            "name_bn": "শ্রমিকের ছবি",
            "name_en": "employee photo",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 293,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self_institutional",
            "field_id": "maternityGrant_blwf_self_institutional_employee_appointment_letter_copy",
            "document_type": "employee appointment letter copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের নিয়োপত্রের অনুলিপি",
            "name_en": "employee appointment letter",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 294,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "maternityGrant_blwf_self_Institutional_certificate_copy",
            "document_type": "Institutional certificate copy",
            "document_count": "single",
            "name_bn": "কাজের সনদ",
            "name_en": "Institutional certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 295,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_family_nid",
            "document_type": "family nid",
            "document_count": "single",
            "name_bn": "পরিবারবর্গের জাতীয় পরিচয়পত্র",
            "name_en": "family nid",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 296,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_family_birth_cirtificate_copy",
            "document_type": "family birth cirtificate copy",
            "document_count": "single",
            "name_bn": "পরিবারবর্গের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "family birth cirtificate copy",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 297,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_family_photo",
            "document_type": "family photo",
            "document_count": "single",
            "name_bn": "পরিবারবর্গের ছবি",
            "name_en": "family photo",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 298,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "self_non_institutional",
            "field_id": "maternityGrant_blwf_self_non_institutional_union_parishad_/_municipality_or_city_corporation",
            "document_type": "union parishad / municipality or city corporation",
            "document_count": "single",
            "name_bn": "ইউনিয়ন পরিষদ /পৌরসভা বা সিটি কর্পোরেশন সাটিফিকেট",
            "name_en": "union parishad / municipality or city corporation cirtificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 299,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_nid_of_deceased_worker",
            "document_type": "nid of deceased worker",
            "document_count": "single",
            "name_bn": "মৃত শ্রমিকের জাতীয় পরিচয়পত্র",
            "name_en": "nid of the deceased worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 300,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_birth_cirtificate_pf_deceased_worker",
            "document_type": "birth cirtificate pf deceased worker",
            "document_count": "single",
            "name_bn": "মৃত শ্রমিকের জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "birth cirtificate pf deceased worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 301,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_Photo_of_deceased_worker",
            "document_type": "Photo of deceased worker",
            "document_count": "single",
            "name_bn": "মৃত শ্রমিকের  ছবি",
            "name_en": "Photo of the dead worker",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 302,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_death_certificate",
            "document_type": "death certificate",
            "document_count": "single",
            "name_bn": "রেজিস্টার্ড চিকিৎসক / ইউনিয়ন পরিষদ / পৌরসভা বা সিটি কর্পোরেশন কর্তৃক প্রদত্ত মৃত্যু সনদ",
            "name_en": "death certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 303,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_inheritance_certificate",
            "document_type": "inheritance certificate",
            "document_count": "single",
            "name_bn": "ইউনিয়ন পরিষদ /পৌরসভা বা সিটি কর্পোরেশন হতে ওয়ারিশান সনদ",
            "name_en": "inheritance certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 304,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_no_Objection_Letter_",
            "document_type": "no Objection Letter ",
            "document_count": "single",
            "name_bn": "অনাপত্তি পত্র",
            "name_en": "no Objection Letter ",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 305,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_nominee's_nid",
            "document_type": "nominee's nid",
            "document_count": "single",
            "name_bn": "নমিনীর জাতীয় পরিচয়পত্র",
            "name_en": "nominee's national identity card",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 306,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_nominee's_birth_certificate",
            "document_type": "nominee's birth certificate",
            "document_count": "single",
            "name_bn": "নমিনীর জন্মসনদ",
            "name_en": "nominee's birth certificate",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        },
        {
            "id": uuid.uuid4(),
            "document_type_no": 307,
            "application_type": "deadlyGrant",
            "organization_type": "blwf",
            "application_for": "normal_death",
            "field_id": "deadlyGrant_blwf_normal_death_nominee's_photo",
            "document_type": "nominee's photo",
            "document_count": "single",
            "name_bn": "নমিনীর ছবি",
            "name_en": "nominee's photo",
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id
        }
    ]

    for item in data:
        WorkforceDocumentType.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0098_historicalworkforceapplication_submitted_by_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_more_workforce_document_types),
    ]
