# Generated by Django 4.2.23 on 2025-07-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0101_alter_workforceeducation_workforce_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforcedependant',
            name='application',
        ),
        migrations.RemoveField(
            model_name='workforcedependant',
            name='permanent_location',
        ),
        migrations.RemoveField(
            model_name='workforcedependant',
            name='present_location',
        ),
        migrations.RemoveField(
            model_name='workforcedependant',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='workforcedependant',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='workforcedependant',
            name='workforce_employee',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='father_name_bn',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='father_name_en',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='first_name_bn',
            new_name='name_bn',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='last_name_bn',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='father_name_bn',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='father_name_en',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='first_name_bn',
            new_name='name_bn',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='last_name_bn',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedependent',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedependent',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedependent',
            name='mother_name_bn',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceemployeedependent',
            name='mother_name_en',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedependent',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedependent',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedependent',
            name='mother_name_bn',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedependent',
            name='mother_name_en',
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='workforce_dependant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeedependent'),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='life_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='workforce_dependant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='workforce.workforceemployeedependent'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='life_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalWorkforceDependant',
        ),
        migrations.DeleteModel(
            name='WorkforceDependant',
        ),
    ]
