# Generated by Django 4.2.23 on 2025-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0102_remove_workforcedependant_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceemployeedependent',
            name='relation_type',
        ),
        migrations.RemoveField(
            model_name='workforceemployeedependent',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='percentage_of_cf_grant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='percentage_of_cf_grant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
