# Generated by Django 4.2.23 on 2025-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0103_remove_historicalworkforceemployeedependent_relation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
