# Generated by Django 4.2.23 on 2025-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0104_historicalworkforceeducation_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='applicant_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='education_board',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='education_level',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='registration_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='roll_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='applicant_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='education_board',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='education_level',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='registration_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='roll_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
