# Generated by Django 4.2.20 on 2025-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0106_update_cf_financialAssistance_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='child_birth_certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='child_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='child_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='child_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='child_nid_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeducation',
            name='child_study_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='child_birth_certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='child_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='child_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='child_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='child_nid_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceeducation',
            name='child_study_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
