# Generated by Django 4.2.20 on 2025-07-22 09:08

from django.db import migrations, models


def clear_bank_tables(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')
    HistoricalBank = apps.get_model('workforce', 'HistoricalBank')

    # Delete all data from both tables
    Bank.objects.all().delete()
    HistoricalBank.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('workforce', '0107_historicalworkforceeducation_child_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_bank_tables),

        migrations.RemoveField(
            model_name='bank',
            name='headquarter_address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='workforce_application',
        ),
        migrations.RemoveField(
            model_name='historicalbank',
            name='headquarter_address',
        ),
        migrations.RemoveField(
            model_name='historicalbank',
            name='workforce_application',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='district_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='district_name_en',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='branch_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='district_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='district_name_en',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbank',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbank',
            name='routing_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
