# Generated by Django 4.2.20 on 2025-07-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0108_remove_bank_headquarter_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceeducation',
            old_name='child_study_class',
            new_name='study_class',
        ),
        migrations.RenameField(
            model_name='workforceeducation',
            old_name='child_study_class',
            new_name='study_class',
        ),
    ]
