# Generated by Django 4.2.20 on 2025-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0110_seed_main_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='district_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbank',
            name='district_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
