# Generated by Django 4.2.20 on 2025-07-22

from django.db import migrations
import uuid
import json
import os
from django.conf import settings


def seed_branch_banks(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    user = User.objects.get(username="Admin")
    user_id = user.id

    current_dir = os.path.dirname(__file__)
    json_path = os.path.join(current_dir, 'routing_data.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        branch_data = json.load(f)

    for item in branch_data:
        parent_bank = Bank.objects.filter(bank_code=item["bank_code"], type="main").first()
        if not parent_bank:
            raise ValueError(f"No main bank found with bank_code={item['bank_code']} for branch: {item}")

        Bank.objects.create(
            id=uuid.uuid4(),
            name_en=item["branch_name_en"],
            bank_code=item["bank_code"],
            branch_code=item["branch_code"],
            district_code=item["district_code"],
            district_name_en=item["district_name_en"],
            routing_number=item["routing_number"],
            parent=parent_bank,
            user_created_id=user_id,
            user_updated_id=user_id,
            status="active",
            type="branch"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0111_alter_bank_district_name_en_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_branch_banks),
    ]
