# Generated by Django 4.2.20 on 2025-07-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0113_workforceemployeebankinginfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='workforce_document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcedocumenttype'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='workforce_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_type_for_documents', to='workforce.workforcedocumenttype'),
        ),
    ]
