# Generated by Django 4.2.20 on 2025-07-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_code'),
        ('workforce', '0114_historicalworkforcedocument_workforce_document_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='father_name',
            new_name='father_name_bn',
        ),
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='mother_name',
            new_name='father_name_en',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='father_name',
            new_name='father_name_bn',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='mother_name',
            new_name='father_name_en',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='relation_with_worker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='permanent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_dependent_permanent_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='present_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_dependent_present_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='relation_with_worker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
