# Generated by Django 4.2.20 on 2025-07-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0115_rename_father_name_historicalworkforceemployeedependent_father_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='workforce_dependent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeedependent'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='workforce_dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_dependent', to='workforce.workforceemployeedependent'),
        ),
    ]
