# Generated by Django 4.2.20 on 2025-07-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0116_historicalworkforcedocument_workforce_dependent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='holder',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='holder',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
