# Generated by Django 4.2.20 on 2025-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0117_alter_historicalworkforcedocument_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocumenttype',
            name='mandatory_for_applicant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumenttype',
            name='mandatory_for_applicant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
