# Generated by Django 4.2.20 on 2025-07-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('location', '0019_alter_location_code'),
        ('workforce', '0119_seed_fresh_updated_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workforce.bank'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='blwf_application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blwf_application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='cf_application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cf_application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='eis_application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eis_application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='employee_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.workforceemployer'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='employee_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcefactory'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='grant_money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_grant_money', to='workforce.workforcegrantmoney'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_application_organization', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='workforce_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_employee', to='workforce.workforceemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_employee_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_employee_record', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_office', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_office_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_office_unit', to='workforce.workforceorganizationunit'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_office_unit_organogram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_office_unit_organogram', to='workforce.workforceorganizationunitdesignation'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverted_by', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_employee_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_employee_record', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_office', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_office_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_office_unit', to='workforce.workforceorganizationunit'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_office_unit_organogram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_office_unit_organogram', to='workforce.workforceorganizationunitdesignation'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummarymovement',
            name='application_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_summary', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummarymovement',
            name='from_workforce_organization_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_workforce_organization_employee', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummarymovement',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_reverted_by', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummarymovement',
            name='to_workforce_organization_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_workforce_organization_employee', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='core.interactiveuser'),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory', to='workforce.workforcefactory'),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='core.interactiveuser'),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='workforce_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_document_application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='workforce_dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_dependent', to='workforce.workforceemployeedependent'),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='workforce_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_type_for_documents', to='workforce.workforcedocumenttype'),
        ),
        migrations.AlterField(
            model_name='workforcedocumentmap',
            name='mapped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_by', to='core.interactiveuser'),
        ),
        migrations.AlterField(
            model_name='workforcedocumentmap',
            name='workforce_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_document_type', to='workforce.workforcedocumenttype'),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='workforce_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='workforce.workforcediseases'),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='workforce_dependant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='workforce.workforceemployeedependent'),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='workforce_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='workforce.workforceemployee'),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='permanent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_permanent_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='present_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_present_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_related_user', to='core.interactiveuser'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='accident_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_accident_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='workforce.workforceemployee'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='workforce_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_employee_accident_application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_dependent_bank', to='workforce.bank'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_dependent_branch', to='workforce.bank'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='permanent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_permanent_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='present_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_present_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_banking_info_application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_banking_bank', to='workforce.bank'),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='dependant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_banking_dependents', to='workforce.workforceemployeedependent'),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_banking_employee_id', to='workforce.workforceemployee'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='permanent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_dependent_permanent_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='present_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_dependent_present_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='workforce_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_employee_dependent_application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='workforce_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation_application', to='workforce.workforceapplication'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='workforce_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforceemployer'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='workforce_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation_employee_id', to='workforce.workforceemployee'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcefactory'),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='workforce_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.workforceoffice'),
        ),
        migrations.AlterField(
            model_name='workforceemployer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceemployer',
            name='workforce_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcerepresentative'),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='workforce_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforceemployer'),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='workforce_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcerepresentative'),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workforce.workforceoffice'),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='workforce_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforceemployer'),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='workforce_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcerepresentative'),
        ),
        migrations.AlterField(
            model_name='workforceorganization',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceorganization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceorganization',
            name='workforce_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcerepresentative'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployee',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interactiveuser'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployeedesignation',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_designations', to='workforce.workforceorganizationunitdesignation'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployeedesignation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='workforce.workforceorganizationemployee'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workforce.workforceorganizationunit'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunitdesignation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='workforce.workforceorganization'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunitdesignation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workforce.workforceorganizationunitdesignation'),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunitdesignation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_designations', to='workforce.workforceorganizationunit'),
        ),
        migrations.AlterField(
            model_name='workforcerepresentative',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforcerepresentative',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interactiveuser'),
        ),
    ]
