# Generated by Django 4.2.20 on 2025-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0123_alter_bank_location_alter_bank_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='applicant_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='applicant_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
