from django.db import migrations
import uuid
from django.conf import settings
from workforce.models import WorkforceDiseases


def seed_workforce_diseases(apps, schema_editor):
    WorkforceDiseases = apps.get_model('workforce', 'WorkforceDiseases')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Truncate the table (deletes all rows)
    schema_editor = apps.get_model('workforce', 'WorkforceDiseases')
    schema_editor.objects.all().delete()

    data = [
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "ক্যান্সার",
            "disease_no": "1",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "হার্টের বাইপাস সার্জারী",
            "disease_no": "2",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "ব্রেন টিউমার",
            "disease_no": "3",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "ট্রান্সপ্লান্ট সার্জারী (কিডনী,লিভার,অন্যান্য )",
            "disease_no": "4",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "ক্রনিক কিডনি রোগ + ডায়ালাইসিস",
            "disease_no": "5",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "থ্যালাসেমিয়া",
            "disease_no": "6",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "টোটাল হিপ/নি রিপ্লেসমেন্ট",
            "disease_no": "7",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "5",
            "disease_name": "অঙ্গহানী (সম্পূর্ন হাত/পা বিচ্ছিন্ন)",
            "disease_no": "8",
            "minimum_donation_amount": 0,
            "maximum_donation_amount": 100000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "হার্টের অপারেশন (ভাল্ব, পেসমেকার, রিং,ফুটো)",
            "disease_no": "9",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "হেড ইঞ্জুরী",
            "disease_no": "10",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "লিভার সিরোসিস",
            "disease_no": "11",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "এমআই (হার্ট এ্যাটাক)",
            "disease_no": "12",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "হার্ট ফেইলুর",
            "disease_no": "13",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "বাচ্চার জন্মগত জটিল রোগের অপারেশন",
            "disease_no": "14",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "পেরিফেরাল ভাস্কুলার ডিজিজ",
            "disease_no": "15",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "4",
            "disease_name": "প্যাক্রিয়াটাইটিস",
            "disease_no": "16",
            "minimum_donation_amount": 60000,
            "maximum_donation_amount": 80000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "3",
            "disease_name": "পেটের অপারেশন (হার্নিয়া,পিত্তথলির পাথর,এপেন্ডিক্স, জরায়ু, কিডনি/মূত্রনালীর পাথর, প্রোস্টেট,পাইস অপারেশন ইত্যাদি)",
            "disease_no": "17",
            "minimum_donation_amount": 40000,
            "maximum_donation_amount": 60000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "3",
            "disease_name": "আর্থোপেডিক অপারেশন/ইম্প্লাট লাগানো",
            "disease_no": "18",
            "minimum_donation_amount": 40000,
            "maximum_donation_amount": 60000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "3",
            "disease_name": "রক্তনালীর অপারেশন",
            "disease_no": "19",
            "minimum_donation_amount": 40000,
            "maximum_donation_amount": 60000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "3",
            "disease_name": "ক্রনিক কিডনি রোগ (ডায়ালাইসিস ছাড়া)",
            "disease_no": "20",
            "minimum_donation_amount": 40000,
            "maximum_donation_amount": 60000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "3",
            "disease_name": "অন্যান্য বড় অপারেশন",
            "disease_no": "21",
            "minimum_donation_amount": 40000,
            "maximum_donation_amount": 60000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "সেলুলাইটিস",
            "disease_no": "22",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "হাত/পায়ের হাড় ভাঙ্গা (অপারেশন বিহীন)",
            "disease_no": "23",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "কানের অপারেশন",
            "disease_no": "24",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "চোখের অপারেশন( ছানি,রেটিনা, নালী, ইত্যাদি)",
            "disease_no": "25",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "হেপাটাইটিস বি এবং সি",
            "disease_no": "26",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "হাতের আঙ্গুল /পায়ের অঙ্গুল হারানো",
            "disease_no": "27",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "যক্ষা/টিবি",
            "disease_no": "28",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "টাইফয়েড জ্বর",
            "disease_no": "29",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "ডেঙ্গু শক সিন্ড্রোম",
            "disease_no": "30",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "সেপসিস",
            "disease_no": "31",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "বন্ধ্যাত্ব",
            "disease_no": "32",
            "minimum_donation_amount": 30000,
            "maximum_donation_amount": 40000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "2",
            "disease_name": "মাতৃত্ব কল্যাণ",
            "disease_no": "33",
            "minimum_donation_amount": 25000,
            "maximum_donation_amount": 0,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "মাসকুলোস্কেলিটাল ডিজিজ ( কোমর ব্যাথ্য, ঘাড় ব্যাথা, শোল্ডার,এলবো,রিস্ট, নি, এনকেল ব্যাথা, ইত্যাদি)",
            "disease_no": "34",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "ডায়াবেটি ফুট",
            "disease_no": "35",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "নিউমোনিয়া",
            "disease_no": "36",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "ব্রোঙ্কাইটিস",
            "disease_no": "37",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "সিওপিডি",
            "disease_no": "38",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "দৃষ্টি শক্তি",
            "disease_no": "39",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "অ্যাজমা",
            "disease_no": "40",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "পেপটিক আলসার",
            "disease_no": "41",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "পাইলস (অপারেশন বিহীন)",
            "disease_no": "42",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "ফিসার",
            "disease_no": "43",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "ডাইরিয়া",
            "disease_no": "44",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "দাঁতের অপারেশন",
            "disease_no": "45",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "স্ক্রীন ডিজিজ",
            "disease_no": "46",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "সিজোফ্রেনিয়া",
            "disease_no": "47",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "অন্যান্য মানসিক রোগ",
            "disease_no": "48",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "জন্ডিস",
            "disease_no": "49",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "রক্তশূন্যতা",
            "disease_no": "50",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "ডায়াবেটিস",
            "disease_no": "51",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "উচ্চরক্তচাপ",
            "disease_no": "52",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "সাধারণ জ্বর (ডেঙ্গু জ্বর,ভাইরাল জ্বর,ইত্যাদি)",
            "disease_no": "53",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "প্রস্রাব ইনফেকশন",
            "disease_no": "54",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "সিস্ট/লাইকোমা অপারেশন",
            "disease_no": "55",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "হাত/পা কেটে যাওয়া",
            "disease_no": "56",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "টেন্ডন ইঞ্জুরী",
            "disease_no": "57",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "নাকের অপারেশন",
            "disease_no": "58",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "বিইপি (বিনাইন প্রোস্টেটিক হাইপারপ্লাসিয়া) অপারেশন ছাড়া",
            "disease_no": "59",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
        {
            "id": uuid.uuid4(),
            "grade": "1",
            "disease_name": "অন্যান্য সাধারণ রোগ",
            "disease_no": "60",
            "minimum_donation_amount": 20000,
            "maximum_donation_amount": 30000,
            "status": "active",
            "user_created_id": user_id,
            "user_updated_id": user_id,
        },
    ]

    for item in data:
        WorkforceDiseases.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0125_seed_updated_geo_data'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_diseases),
    ]