# Generated by Django 4.2.20 on 2025-07-22

from django.db import migrations
import uuid
from django.conf import settings


def seed_bank_data(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    user = User.objects.get(username="Admin")
    user_id = user.id

    seed_data = [
        {
            "bank_code": "020",
            "bank_name_en": "AB Bank"
        },
        {
            "bank_code": "010",
            "bank_name_en": "Agrani Bank"
        },
        {
            "bank_code": "015",
            "bank_name_en": "Al-Arafah Islami Bank"
        },
        {
            "bank_code": "055",
            "bank_name_en": "BASIC Bank"
        },
        {
            "bank_code": "060",
            "bank_name_en": "BRAC Bank"
        },
        {
            "bank_code": "030",
            "bank_name_en": "Bangladesh Commerce Bank"
        },
        {
            "bank_code": "047",
            "bank_name_en": "Bangladesh Development Bank"
        },
        {
            "bank_code": "035",
            "bank_name_en": "Bangladesh Krishi Bank"
        },
        {
            "bank_code": "065",
            "bank_name_en": "Bank Alfalah"
        },
        {
            "bank_code": "070",
            "bank_name_en": "Bank Asia"
        },
        {
            "bank_code": "075",
            "bank_name_en": "Citibank"
        },
        {
            "bank_code": "00990",
            "bank_name_en": "Citizens Bank"
        },
        {
            "bank_code": "225",
            "bank_name_en": "City Bank"
        },
        {
            "bank_code": "080",
            "bank_name_en": "Commercial Bank of Ceylon"
        },
        {
            "bank_code": "085",
            "bank_name_en": "Dhaka Bank"
        },
        {
            "bank_code": "090",
            "bank_name_en": "Dutch-Bangla Bank"
        },
        {
            "bank_code": "100",
            "bank_name_en": "EXIM Bank"
        },
        {
            "bank_code": "095",
            "bank_name_en": "Eastern Bank"
        },
        {
            "bank_code": "105",
            "bank_name_en": "First Security Islami Bank"
        },
        {
            "bank_code": "300",
            "bank_name_en": "Global Islami Bank"
        },
        {
            "bank_code": "115",
            "bank_name_en": "HSBC Bank"
        },
        {
            "bank_code": "110",
            "bank_name_en": "Habib Bank"
        },
        {
            "bank_code": "230",
            "bank_name_en": "ICB Islamic Bank"
        },
        {
            "bank_code": "120",
            "bank_name_en": "IFIC Bank"
        },
        {
            "bank_code": "125",
            "bank_name_en": "Islami Bank"
        },
        {
            "bank_code": "130",
            "bank_name_en": "Jamuna Bank"
        },
        {
            "bank_code": "135",
            "bank_name_en": "Janata Bank"
        },
        {
            "bank_code": "275",
            "bank_name_en": "Meghna Bank"
        },
        {
            "bank_code": "140",
            "bank_name_en": "Mercantile Bank"
        },
        {
            "bank_code": "285",
            "bank_name_en": "Midland Bank"
        },
        {
            "bank_code": "295",
            "bank_name_en": "Modhumoti Bank"
        },
        {
            "bank_code": "145",
            "bank_name_en": "Mutual Trust Bank"
        },
        {
            "bank_code": "160",
            "bank_name_en": "NCC Bank"
        },
        {
            "bank_code": "290",
            "bank_name_en": "NRB Bank"
        },
        {
            "bank_code": "260",
            "bank_name_en": "NRB Commercial Bank"
        },
        {
            "bank_code": "150",
            "bank_name_en": "National Bank"
        },
        {
            "bank_code": "155",
            "bank_name_en": "National Bank of Pakistan"
        },
        {
            "bank_code": "165",
            "bank_name_en": "One Bank"
        },
        {
            "bank_code": "00",
            "bank_name_en": "Padma Bank"
        },
        {
            "bank_code": "235",
            "bank_name_en": "Premier Bank"
        },
        {
            "bank_code": "170",
            "bank_name_en": "Prime Bank"
        },
        {
            "bank_code": "175",
            "bank_name_en": "Pubali Bank"
        },
        {
            "bank_code": "180",
            "bank_name_en": "Rajshahi Krishi Unnayan Bank"
        },
        {
            "bank_code": "185",
            "bank_name_en": "Rupali Bank"
        },
        {
            "bank_code": "270",
            "bank_name_en": "SBAC Bank"
        },
        {
            "bank_code": "190",
            "bank_name_en": "Shahjalal Islami Bank"
        },
        {
            "bank_code": "195",
            "bank_name_en": "Social Islami Bank"
        },
        {
            "bank_code": "200",
            "bank_name_en": "Sonali Bank"
        },
        {
            "bank_code": "205",
            "bank_name_en": "Southeast Bank"
        },
        {
            "bank_code": "210",
            "bank_name_en": "Standard Bank"
        },
        {
            "bank_code": "215",
            "bank_name_en": "Standard Chartered Bank"
        },
        {
            "bank_code": "220",
            "bank_name_en": "State Bank of India"
        },
        {
            "bank_code": "240",
            "bank_name_en": "Trust Bank"
        },
        {
            "bank_code": "265",
            "bank_name_en": "Union Bank"
        },
        {
            "bank_code": "245",
            "bank_name_en": "United Commercial Bank"
        },
        {
            "bank_code": "250",
            "bank_name_en": "Uttara Bank"
        },
        {
            "bank_code": "255",
            "bank_name_en": "Woori Bank"
        }
    ]

    for item in seed_data:
        Bank.objects.create(
            id=uuid.uuid4(),
            bank_code=item["bank_code"],
            name_en=item["bank_name_en"],
            user_created_id=user_id,
            user_updated_id=user_id,
            status="active",
            type="main"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0126_reseed_diseases'),  # Update to match your latest migration
    ]

    operations = [
        migrations.RunPython(seed_bank_data),
    ]
