# Generated by Django 4.2.20 on 2025-07-31 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0130_reseed_fresh_updated_document_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalbank',
            name='location',
        ),
    ]
