# Generated by Django 4.2.20 on 2025-07-31

from django.db import migrations
import uuid
import json
import os
from django.conf import settings


def reseed_all_banks(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    user = User.objects.get(username="Admin")
    user_id = user.id

    # Clear existing banks
    Bank.objects.all().delete()

    # Load JSON file
    current_dir = os.path.dirname(__file__)
    json_path = os.path.join(current_dir, 'updated_banks.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        bank_data = json.load(f)

    # First pass: Create all banks without setting parent
    uuid_to_bank_obj = {}

    for item in bank_data:
        obj = Bank.objects.create(
            id=uuid.UUID(item["UUID"]),
            name_en=item["name_en"],
            name_bn=item.get("name_bn") or None,
            bank_code=item.get("bank_code") or None,
            branch_code=item.get("branch_code") or None,
            district_code=item.get("district_code") or None,
            district_name_en=item.get("district_name_en") or None,
            routing_number=item.get("routing_number") or None,
            parent=None,  # Set in second pass
            user_created_id=user_id,
            user_updated_id=user_id,
            status="active",
            type=item.get("type") or "main",
        )
        uuid_to_bank_obj[item["UUID"]] = obj

    # Second pass: Set parent relationships
    for item in bank_data:
        parent_uuid = item.get("parent_id")
        if parent_uuid:
            bank = uuid_to_bank_obj[item["UUID"]]
            parent = uuid_to_bank_obj.get(parent_uuid)
            if parent:
                bank.parent = parent
                bank.save(update_fields=["parent"])


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0131_remove_bank_location_remove_historicalbank_location'),
    ]

    operations = [
        migrations.RunPython(reseed_all_banks),
    ]
