# Generated by Django 4.2.20 on 2025-08-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0134_update_document_type_for_temporary_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
