# Generated by Django 4.2.20 on 2025-07-31

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    WorkforceDiseases = apps.get_model('workforce', 'WorkforceDiseases')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Delete specific document_type_no = 109 if it exists
    WorkforceDocumentType.objects.filter(document_type_no=109).delete()

    # Update existing records if found
    update_entries = {
        74: {
            "application_type": "maternityGrant",
            "organization_type": "cf",
            "application_for": "dependent",
            "field_id": "maternityGrant_dependent_family_nid",
            "document_type": "wife's nid",
            "document_count": "single",
            "name_bn": "স্ত্রীর জাতীয় পরিচয়পত্র",
            "name_en": "wife's nid",
            "status": "active",
            "mandatory_for_applicant": True
        },
        75: {
            "application_type": "maternityGrant",
            "organization_type": "cf",
            "application_for": "dependent",
            "field_id": "maternityGrant_dependent_family_birth_certificate_copy",
            "document_type": "wife's birth certificate copy",
            "document_count": "single",
            "name_bn": "স্ত্রীর জন্ম সনদের সত্যায়িত অনুলিপি",
            "name_en": "wife's birth certificate copy",
            "status": "active",
            "mandatory_for_applicant": True
        },
        76: {
            "application_type": "maternityGrant",
            "organization_type": "cf",
            "application_for": "dependent",
            "field_id": "maternityGrant_dependent_family_photo",
            "document_type": "wife's photo",
            "document_count": "single",
            "name_bn": "স্ত্রীর ছবি",
            "name_en": "wife's photo",
            "status": "active",
            "mandatory_for_applicant": True
        },
        99: {
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "disabled_employee_disability_certificate",
            "document_type": "medical certificate/prescription/test report/discharge certificate",
            "document_count": "single",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট /চিকিৎসা ব্যবস্থাপত্র /টেস্ট রিপোর্টের কপি/চিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "medical certificate/prescription/test report/discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        104: {
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "disabled_employee_online_database_copy",
            "document_type": "copy of the online database",
            "document_count": "single",
            "name_bn": "অনলাইন ডেটাবেজের কপি",
            "name_en": "copy of the online database",
            "status": "active",
            "mandatory_for_applicant": False
        },
        105: {
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_isability",
            "field_id": "disabled_employee_six_months_pay_slip",
            "document_type": "last salary copy",
            "document_count": "single",
            "name_bn": "সর্বশেষ বেতন শীটের অনুলিপি",
            "name_en": "last salary copy",
            "status": "active",
            "mandatory_for_applicant": False
        },
    }

    for doc_no, update_data in update_entries.items():
        try:
            doc = WorkforceDocumentType.objects.get(document_type_no=doc_no)
            for key, value in update_data.items():
                setattr(doc, key, value)
            doc.user_updated_id = user_id
            doc.save()
        except WorkforceDocumentType.DoesNotExist:
            print(f"Document type {doc_no} not found. Skipping update.")

    # Add new entries
    new_entries = [
        {
            "document_type_no": 308,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "permanent_disability_applicants_bank_info",
            "document_type": "applicants bank info",
            "document_count": "single",
            "name_bn": "আবেদনকারী ব্যাংক হিসাবের বিবরণী",
            "name_en": "applicants bank info",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 309,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "permanent_disability_applicants_bank_check_copy",
            "document_type": "applicants bank check copy",
            "document_count": "single",
            "name_bn": "আবেদনকারীর ব্যাংক হিসাবের চেকের পাতার ফটোকপি",
            "name_en": "applicants bank check copy",
            "status": "active",
            "mandatory_for_applicant": True
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=entry["mandatory_for_applicant"],
            user_created_id=user_id,
            user_updated_id=user_id,
        )

        # Fix typo: permanent_isability → permanent_disability
        typo_entries = WorkforceDocumentType.objects.filter(application_for="permanent_isability")
        for entry in typo_entries:
            entry.application_for = "permanent_disability"
            entry.user_updated_id = user_id
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0140_fresh_updated_document_types'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
