# Generated by Django 4.2.20 on 2025-07-30

from django.db import migrations
import uuid
from django.utils import timezone
from django.conf import settings


def seed_grant_money(apps, schema_editor):
    WorkforceGrantMoney = apps.get_model('workforce', 'WorkforceGrantMoney')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    user = User.objects.get(username="Admin")
    user_id = user.id

    now = timezone.now()

    seed_data = [
        {
            "organization_type": "cf",
            "application_type": "medicalAssistance",
            "grant_money": 20000,
            "application_type_no": "01",
            "application_type_name_bn": "চিকিৎসা অনুদান",
            "application_type_name_en": "Medical assistance",
        },
        {
            "organization_type": "cf",
            "application_type": "scholarship",
            "grant_money": 20000,
            "application_type_no": "03",
            "application_type_name_bn": "শিক্ষা অনুদান",
            "application_type_name_en": "Educational assistance",
        },
        {
            "organization_type": "cf",
            "application_type": "financialAssistance",
            "grant_money": 200000,
            "application_type_no": "04",
            "application_type_name_bn": "মৃত্যুজনিত অনুদান",
            "application_type_name_en": "Death grant",
        },
        {
            "organization_type": "cf",
            "application_type": "maternityGrant",
            "grant_money": 25000,
            "application_type_no": "09",
            "application_type_name_bn": "মাতৃত্বজনিত অনুদান",
            "application_type_name_en": "Maternity grant",
        },
        {
            "organization_type": "cf",
            "application_type": "disabilityAssistance",
            "grant_money": 200000,
            "application_type_no": "02",
            "application_type_name_bn": "স্থায়ী ও আংশিক অক্ষমতা জনিত আর্থিক সহায়তা",
            "application_type_name_en": "Disability assistance",
        },
        {
            "organization_type": "blwf",
            "application_type": "maternityGrant",
            "grant_money": 25000,
            "application_type_no": "05",
            "application_type_name_bn": "মাতৃত্বজনিত অনুদান",
            "application_type_name_en": "Maternity grant",
        },
        {
            "organization_type": "blwf",
            "application_type": "educationGrant",
            "grant_money": 20000,
            "application_type_no": "06",
            "application_type_name_bn": "শিক্ষা অনুদান",
            "application_type_name_en": "Educational assistance",
        },
        {
            "organization_type": "blwf",
            "application_type": "deadlyGrant",
            "grant_money": 25000,
            "application_type_no": "07",
            "application_type_name_bn": "মৃত্যুজনিত অনুদান",
            "application_type_name_en": "Death grant",
        },
        {
            "organization_type": "blwf",
            "application_type": "medicalDonation",
            "grant_money": 20000,
            "application_type_no": "08",
            "application_type_name_bn": "চিকিৎসা অনুদান",
            "application_type_name_en": "Medical assistance",
        },
    ]

    for item in seed_data:
        WorkforceGrantMoney.objects.create(
            id=uuid.uuid4(),
            organization_type=item["organization_type"],
            application_type=item["application_type"],
            grant_money=item["grant_money"],
            status="active",
            user_created_id=user_id,
            user_updated_id=user_id,
            application_type_no=item["application_type_no"],
            application_type_name_bn=item["application_type_name_bn"],
            application_type_name_en=item["application_type_name_en"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0144_fresh_seed_diseases'),
    ]

    operations = [
        migrations.RunPython(seed_grant_money),
    ]
