# Generated by Django 4.2.20 on 2025-07-31

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    WorkforceDiseases = apps.get_model('workforce', 'WorkforceDiseases')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Delete specific document_type_no = 98 if it exists
    WorkforceDocumentType.objects.filter(document_type_no=98).delete()

    # Update existing records if found
    update_entries = {
        88: {
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "medicalAssistance_employee_nid",
            "document_type": "medical certificate/prescription/test report/discharge certificate",
            "document_count": "single",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট /চিকিৎসা ব্যবস্থাপত্র /টেস্ট রিপোর্টের কপি/চিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "medical certificate/prescription/test report/discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        93: {
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "medicalAssistance_employee_birth_certificate_copy",
            "document_type": "copy of the online database",
            "document_count": "single",
            "name_bn": "অনলাইন ডেটাবেজের কপি",
            "name_en": "copy of the online database",
            "status": "active",
            "mandatory_for_applicant": False
        },
        94: {
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "medicalAssistance_employee_photo",
            "document_type": "last salary copy",
            "document_count": "single",
            "name_bn": "সর্বশেষ বেতন শীটের অনুলিপি",
            "name_en": "last salary copy",
            "status": "active",
            "mandatory_for_applicant": False
        }
    }

    for doc_no, update_data in update_entries.items():
        try:
            doc = WorkforceDocumentType.objects.get(document_type_no=doc_no)
            for key, value in update_data.items():
                setattr(doc, key, value)
            doc.user_updated_id = user_id
            doc.save()
        except WorkforceDocumentType.DoesNotExist:
            print(f"Document type {doc_no} not found. Skipping update.")

    # Add new entries
    new_entries = [
        {
            "document_type_no": 310,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "medicalAssistance_biometric_copy",
            "document_type": "applicants bank info",
            "document_count": "single",
            "name_bn": "আবেদনকারী ব্যাংক হিসাবের বিবরণী",
            "name_en": "applicants bank info",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 311,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "medicalAssistance_medical_certificate_or_prescription_or_discharge_certificate",
            "document_type": "applicants bank check copy",
            "document_count": "single",
            "name_bn": "আবেদনকারীর ব্যাংক হিসাবের চেকের পাতার ফটোকপি",
            "name_en": "applicants bank check copy",
            "status": "active",
            "mandatory_for_applicant": True
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=entry["mandatory_for_applicant"],
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0148_update_document_type_data'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
