# Generated by Django 4.2.20 on 2025-08-07

from django.db import migrations
from django.conf import settings
from django.db import connection


def update_nid_and_delete_birth_docs(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # TRUNCATE workforce_document table (cascading to dependent data if any)
    with connection.cursor() as cursor:
        cursor.execute("TRUNCATE TABLE workforce_documents CASCADE;")

    # DELETE: where document_type contains "birth"
    WorkforceDocumentType.objects.filter(document_type__icontains="birth").delete()

    # UPDATE: where document_type contains "nid"
    nid_docs = WorkforceDocumentType.objects.filter(document_type__icontains="nid")
    for doc in nid_docs:
        if not doc.name_bn.endswith(" অথবা জন্ম-নিবন্ধন সার্টিফিকেট"):
            doc.name_bn = f"{doc.name_bn.strip()} অথবা জন্ম-নিবন্ধন সার্টিফিকেট"
        if not doc.name_en.endswith(" or birth certificate"):
            doc.name_en = f"{doc.name_en.strip()} or birth certificate"
        doc.user_updated_id = user_id
        doc.save()



class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0155_seed_drop_and_recreate_blwf_documents_in_documnet_types'),
    ]

    operations = [
        migrations.RunPython(update_nid_and_delete_birth_docs),
    ]
