# Generated by Django 4.2.20 on 2025-08-08

from django.db import migrations

def update_document_name_bn(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')

    try:
        doc = WorkforceDocumentType.objects.get(document_type_no=321)
        doc.name_bn = "শিক্ষাপ্রতিষ্ঠানের বিভাগীয় প্রধানের প্রত্যায়নপত্র"
        doc.save()
    except WorkforceDocumentType.DoesNotExist:
        print("Document with document_type_no=321 not found. Skipping update.")

class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0156_seed_update_document_type_remove_birth_certificate_update_nid'),
    ]

    operations = [
        migrations.RunPython(update_document_name_bn),
    ]
