# Generated by Django 4.2.20 on 2025-08-10

from django.db import migrations
from django.conf import settings
import uuid


def update_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    # Get admin user for audit fields
    user = User.objects.get(username="Admin")
    user_id = user.id

    # 1. Delete document_type_no = 295 with cascade
    WorkforceDocumentType.objects.filter(document_type_no=295).delete()

    # 2. Update document_type_no 330 → 339, 331 → 340
    updates_map = {
        330: 339,
        331: 340
    }
    for old_no, new_no in updates_map.items():
        try:
            doc = WorkforceDocumentType.objects.get(document_type_no=old_no)
            doc.document_type_no = new_no
            doc.user_updated_id = user_id
            doc.save()
        except WorkforceDocumentType.DoesNotExist:
            print(f"Document type {old_no} not found. Skipping update.")

    # 3. Add new entries
    new_entries = [
        {
            "document_type_no": 334,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_medical_certificate/prescription/discharge_certificate",
            "document_type": "medical certificate/prescription/test report/discharge certificate",
            "document_count": "single",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট /চিকিৎসা ব্যবস্থাপত্র /টেস্ট রিপোর্টের কপি/চিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "medical certificate/prescription/test report/discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 335,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_employee_photo",
            "document_type": "employee photo",
            "document_count": "single",
            "name_bn": "শ্রমিকের ছবি",
            "name_en": "employee photo",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 336,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_employee_photo",
            "document_type": "workers wife's photo",
            "document_count": "single",
            "name_bn": "শ্রমিকের স্ত্রীর ছবি",
            "name_en": "workers wife's photo",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 337,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_self_employee_nid",
            "document_type": "employee nid",
            "document_count": "single",
            "name_bn": "শ্রমিকের জাতীয় পরিচয়পত্র অথবা জন্ম-নিবন্ধন সার্টিফিকেট",
            "name_en": "employee nid or birth certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 338,
            "application_type": "maternityGrant",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "maternityGrant_blwf_dependent_employee_nid",
            "document_type": "employee nid",
            "document_count": "single",
            "name_bn": "শ্রমিকের স্ত্রীর জাতীয় পরিচয়পত্র অথবা জন্ম-নিবন্ধন সার্টিফিকেট",
            "name_en": "workers wife's nid or birth certificate",
            "status": "active",
            "mandatory_for_applicant": True
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=entry["mandatory_for_applicant"],
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0157_update_blwf_educational_field_name'),
    ]

    operations = [
        migrations.RunPython(update_workforce_documents),
    ]
