# Generated by Django 4.2.20 on 2025-08-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0158_seed_update_blwf_dependen_data_and_add_some_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcefactory',
            name='workforce_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceemployer'),
        ),
    ]
