# Generated by Django 4.2.20 on 2025-08-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0159_alter_workforcefactory_workforce_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcefactory',
            name='workforce_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforcerepresentative'),
        ),
    ]
