# Generated by Django 4.2.23 on 2025-08-14 18:26

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0020_location_zip_code_w_id'),
        ('workforce', '0161_workforcesignature_historicalworkforcesignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceFactoryRegistration',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('employer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_id_lima', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(db_comment='Translatable name field. May use any language', max_length=255)),
                ('name_en', models.CharField(db_comment='English name field', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('is_same_company_representative', models.SmallIntegerField(default=0)),
                ('association_type', models.CharField(blank=True, max_length=50, null=True)),
                ('representative_type', models.CharField(max_length=255)),
                ('representative_name_bn', models.CharField(db_comment='Translatable name field. May use any language', max_length=255)),
                ('representative_name_en', models.CharField(db_comment='English name field', max_length=255)),
                ('representative_address', models.TextField(blank=True, null=True)),
                ('representative_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('representative_email', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_nid', models.CharField(blank=True, max_length=30, null=True)),
                ('representative_passport_no', models.CharField(blank=True, max_length=30, null=True)),
                ('representative_birth_date', models.DateField(blank=True, null=True)),
                ('representative_position', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_status', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_location', to='location.location')),
                ('representative_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='representative_location', to='location.location')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
                ('workforce_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceemployer')),
            ],
            options={
                'db_table': 'workforce_employer_registrable_factories',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkforceFactoryRegistration',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('employer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_id_lima', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(db_comment='Translatable name field. May use any language', max_length=255)),
                ('name_en', models.CharField(db_comment='English name field', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('is_same_company_representative', models.SmallIntegerField(default=0)),
                ('association_type', models.CharField(blank=True, max_length=50, null=True)),
                ('representative_type', models.CharField(max_length=255)),
                ('representative_name_bn', models.CharField(db_comment='Translatable name field. May use any language', max_length=255)),
                ('representative_name_en', models.CharField(db_comment='English name field', max_length=255)),
                ('representative_address', models.TextField(blank=True, null=True)),
                ('representative_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('representative_email', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_nid', models.CharField(blank=True, max_length=30, null=True)),
                ('representative_passport_no', models.CharField(blank=True, max_length=30, null=True)),
                ('representative_birth_date', models.DateField(blank=True, null=True)),
                ('representative_position', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_status', models.CharField(blank=True, max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location')),
                ('representative_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workforce_employer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployer')),
            ],
            options={
                'verbose_name': 'historical workforce factory registration',
                'verbose_name_plural': 'historical workforce factory registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
