# Generated by Django 4.2.23 on 2025-08-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('location', '0020_location_zip_code_w_id'),
        ('workforce', '0161_workforcesignature_historicalworkforcesignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceFactoryRegistration',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_id_lima', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(db_comment='Translatable name field. May use any language', max_length=255)),
                ('name_en', models.CharField(db_comment='English name field', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('is_same_company_representative', models.SmallIntegerField(default=0)),
                ('association_type', models.CharField(blank=True, max_length=50, null=True)),
                ('representative_type', models.CharField(max_length=255)),
                ('representative_name_bn', models.CharField(db_comment='Translatable name field. May use any language', max_length=255)),
                ('representative_name_en', models.CharField(db_comment='English name field', max_length=255)),
                ('representative_address', models.TextField(blank=True, null=True)),
                ('representative_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('representative_email', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_nid', models.CharField(blank=True, max_length=30, null=True)),
                ('representative_passport_no', models.CharField(blank=True, max_length=30, null=True)),
                ('representative_birth_date', models.DateField(blank=True, null=True)),
                ('representative_position', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_status', models.CharField(blank=True, max_length=30, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=30, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_registration_approved', to='core.interactiveuser')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_location', to='location.location')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_registration_modified', to='core.interactiveuser')),
                ('representative_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='representative_location', to='location.location')),
                ('workforce_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforceemployer')),
            ],
            options={
                'db_table': 'workforce_employer_registrable_factories',
                'managed': True,
            },
        ),
    ]
