# Generated by Django 4.2.23 on 2025-08-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0162_workforcefactoryregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcefactoryregistration',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.workforcefactory'),
        ),
    ]
