# Generated by Django 4.2.23 on 2025-08-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_location_zip_code_w_id'),
        ('workforce', '0163_workforcefactoryregistration_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcefactoryregistration',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforcefactoryregistration',
            name='name_bn',
            field=models.CharField(db_comment='Translatable name field. May use any language', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforcefactoryregistration',
            name='representative_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='representative_location', to='location.location'),
        ),
    ]
