# Generated by Django 4.2.23 on 2025-08-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0164_alter_workforcefactoryregistration_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcefactoryregistration',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactoryregistration',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
    ]
