# Generated by Django 4.2.20 on 2025-08-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_location_zip_code_w_id'),
        ('workforce', '0165_workforcefactoryregistration_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforcePostoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(blank=True, max_length=512, null=True)),
                ('post_office', models.CharField(blank=True, max_length=512, null=True)),
                ('name_en', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('w_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='w_code_postoffice', to='location.location')),
            ],
            options={
                'db_table': 'workforce_postoffice',
                'managed': True,
            },
        ),
    ]
