# Generated by Django 4.2.20 on 2025-08-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0166_workforcepostoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcepostoffice',
            name='name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
