# Generated by Django 4.2.20 on 2025-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0167_workforcepostoffice_name_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='marital_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='marital_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
