# Generated by Django 4.2.20 on 2025-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0169_seed_postoffice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplicationsummary',
            name='section_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplicationsummary',
            name='section_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
