# Generated by Django 4.2.20 on 2025-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0170_historicalworkforceapplicationsummary_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='district_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalbank',
            name='district_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
