# Generated by Django 4.2.20 on 2025-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0171_bank_district_name_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='citizenship',
            field=models.CharField(default='BD', max_length=50),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='citizenship',
            field=models.CharField(default='BD', max_length=50),
        ),
    ]
