# Generated by Django 4.2.20 on 2025-08-19

from django.db import migrations


def update_district_names(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')

    # Update Bank model
    Bank.objects.filter(district_name_en='Kalampur').update(district_name_en='Dhaka')
    Bank.objects.filter(district_name_en='Chapainawabganj').update(district_name_en='Chapai Nawabganj')
    Bank.objects.filter(district_name_en='Dinaipur').update(district_name_en='Dinajpur')
    Bank.objects.filter(district_name_en='Kishorganj').update(district_name_en='Kishoreganj')


def reverse_district_names(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')

    # Reverse Bank model changes
    Bank.objects.filter(district_name_en='Kalampur').update(district_name_en='Dhaka')
    Bank.objects.filter(district_name_en='Chapainawabganj').update(district_name_en='Chapai Nawabganj')
    Bank.objects.filter(district_name_en='Dinaipur').update(district_name_en='Dinajpur')
    Bank.objects.filter(district_name_en='Kishorganj').update(district_name_en='Kishoreganj')


class Migration(migrations.Migration):
    dependencies = [
        ('workforce', '0172_alter_historicalworkforceemployee_citizenship_and_more'),
    ]

    operations = [
        migrations.RunPython(update_district_names, reverse_district_names),
    ]