# Generated by Django 4.2.20 on 2025-08-19

import json
import os
from django.db import migrations


def add_district_bn_data(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')

    # Get the directory of this migration file
    migration_dir = os.path.dirname(os.path.abspath(__file__))
    json_file_path = os.path.join(migration_dir, 'banks_district_name_en_bn.json')

    # Read district mapping data from JSON file
    with open(json_file_path, 'r', encoding='utf-8') as f:
        district_data = json.load(f)

    # Create mapping dictionary
    district_mapping = {item['district_name_en']: item['district_name_bn'] for item in district_data}

    # Update Bank model
    for en_name, bn_name in district_mapping.items():
        Bank.objects.filter(district_name_en=en_name).update(district_name_bn=bn_name)


def remove_district_bn_data(apps, schema_editor):
    Bank = apps.get_model('workforce', 'Bank')

    # Get the directory of this migration file
    migration_dir = os.path.dirname(os.path.abspath(__file__))
    json_file_path = os.path.join(migration_dir, 'banks_district_name_en_bn.json')

    # Read district names from JSON file
    with open(json_file_path, 'r', encoding='utf-8') as f:
        district_data = json.load(f)

    district_en_names = [item['district_name_en'] for item in district_data]

    # Clear district_name_bn for these districts
    Bank.objects.filter(district_name_en__in=district_en_names).update(district_name_bn=None)


class Migration(migrations.Migration):
    dependencies = [
        ('workforce', '0173_fix_bank_data_typo'),
    ]

    operations = [
        migrations.RunPython(add_district_bn_data, remove_district_bn_data),
    ]