# Generated by Django 4.2.20 on 2025-08-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('workforce', '0174_seed_district_name_bn_in_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplicationmovement',
            name='application_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.interactiveuser'),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplicationmovement',
            name='application_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.interactiveuser'),
        ),
        migrations.AddField(
            model_name='workforceapplicationmovement',
            name='application_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_application_from', to='core.interactiveuser'),
        ),
        migrations.AddField(
            model_name='workforceapplicationmovement',
            name='application_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movement_application_to', to='core.interactiveuser'),
        ),
    ]
