# Generated by Django 4.2.20 on 2025-08-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0175_historicalworkforceapplicationmovement_application_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocumenttype',
            name='form_step_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumenttype',
            name='form_step_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
