# Generated by Django 4.2.20 on 2025-08-21

from django.db import migrations
from django.conf import settings
import uuid
import json
import os


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocument = apps.get_model('workforce', 'WorkforceDocument')
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    WorkforceDiseases = apps.get_model('workforce', 'WorkforceDiseases')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    # Use Admin user
    try:
        user = User.objects.get(username="Admin")
        user_id = user.id
    except User.DoesNotExist:
        raise Exception("Admin user not found. Please create one before running migration.")

    WorkforceDocument.objects.all().delete()
    WorkforceDocumentType.objects.filter(organization_type="cf").delete()

    current_dir = os.path.dirname(__file__)
    json_path = os.path.join(current_dir, "updated_document_type_21-08-25_cf_only.json")

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    for entry in data:
        disease = None

        if entry.get("disease_no"):
            try:
                disease = WorkforceDiseases.objects.get(disease_no=str(entry["disease_no"]))
            except WorkforceDiseases.DoesNotExist:
                print(f"Warning: WorkforceDisease with disease_no {entry['disease_no']} not found.")

        mandatory_flag = entry.get("mandatory_for_applicant", "false").lower() == "true"

        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            form_step_no=int(entry["form_step_no"]),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=str(uuid.uuid4()),
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=mandatory_flag,
            user_created_id=user_id,
            user_updated_id=user_id,
            workforce_disease=disease
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0176_historicalworkforcedocumenttype_form_step_no_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
