# Generated by Django 4.2.23 on 2025-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0177_fresh_updated_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='form_step_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='form_step_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
