# Generated by Django 4.2.20 on 2025-07-31

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Add new entries
    new_entries = [
        {
            "document_type_no": 1,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "self",
            "field_id": "employee_appointment_letter_cf",
            "document_type": "employee appointment letter copy",
            "document_count": "single",
            "name_bn": "শ্রমিকের নিয়োপত্রের অনুলিপি",
            "name_en": "employee appointment letter",
            "status": "active",
            "mandatory_for_applicant": False
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=entry["mandatory_for_applicant"],
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0179_fresh_updated_document_types'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
