# Generated by Django 4.2.20 on 2025-08-25

from django.db import migrations
from django.conf import settings


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Update existing records if found
    update_entries = {
        336: {
            "form_step_no": "educations",
        },
        337: {
            "form_step_no": "educations",
        },
        338: {
            "form_step_no": "educations",
        },
        339: {
            "form_step_no": "educations",
        },
        340: {
            "form_step_no": "educations",
        }
    }

    for doc_no, update_data in update_entries.items():
        try:
            doc = WorkforceDocumentType.objects.get(document_type_no=doc_no, organization_type="cf")
            for key, value in update_data.items():
                setattr(doc, key, value)
            doc.user_updated_id = user_id
            doc.save()
        except WorkforceDocumentType.DoesNotExist:
            print(f"Document type {doc_no} not found. Skipping update.")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0181_remove_historicalworkforceapplicationmovement_from_employee_designation_bng_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
