# Generated by Django 4.2.20 on 2025-08-25

from django.db import migrations
from django.conf import settings


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')

    WorkforceDocumentType.objects.filter(
        application_for__in=["self_disease", "dependent_disease"]
    ).update(is_deleted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0183_seed_update_doucment_type_where_document_no_1'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
