# Generated by Django 4.2.20 on 2025-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0184_update_document_type_set_is_deleted_true_for_disease_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='application_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='application_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
