# Generated by Django 4.2.20 on 2025-08-28

from django.db import migrations
from django.conf import settings
import uuid
import json
import os


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocument = apps.get_model('workforce', 'WorkforceDocument')
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    # Use Admin user
    try:
        user = User.objects.get(username="Admin")
        user_id = user.id
    except User.DoesNotExist:
        raise Exception("Admin user not found. Please create one before running migration.")

    # Explicitly loop through blwf document types and delete related docs
    for doc_type in WorkforceDocumentType.objects.filter(organization_type="blwf"):
        WorkforceDocument.objects.filter(workforce_document_type_id=doc_type.id).delete()
        doc_type.delete()

    current_dir = os.path.dirname(__file__)
    json_path = os.path.join(current_dir, "updated_document_type_08-09-25_blwf_only.json")

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    for entry in data:
        mandatory_flag = str(entry.get("mandatory_for_applicant", "false")).lower() == "true"

        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            form_step_no=entry["form_step_no"],
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count="single",
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status="active",
            mandatory_for_applicant=mandatory_flag,
            user_created_id=user_id,
            user_updated_id=user_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0187_seed_update_form_step_no_blwf'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
