# Generated by Django 4.2.20 on 2025-09-09

from django.db import migrations
from django.conf import settings


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Update existing records if found
    update_entries = {
        25: {
            "application_for": "dependent",
        },
        26: {
            "application_for": "dependent",
        }
    }

    for doc_no, update_data in update_entries.items():
        try:
            doc = WorkforceDocumentType.objects.get(document_type_no=doc_no, organization_type="blwf")
            for key, value in update_data.items():
                setattr(doc, key, value)
            doc.user_updated_id = user_id
            doc.save()
        except WorkforceDocumentType.DoesNotExist:
            print(f"Document type {doc_no} not found. Skipping update.")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0188_fresh_updated_document_types_blwf_only'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
