# Generated by Django 4.2.16 on 2025-09-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0188_fresh_updated_document_types_blwf_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='institution_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='institution_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
