# Generated by Django 4.2.16 on 2025-09-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0189_historicalworkforceapplication_institution_info_and_more'),
        ('workforce', '0190_seed_update_blwf_educationGrant_document'),
    ]

    operations = [
    ]
