# Generated by Django 4.2.20 on 2025-09-25

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Add new entries
    new_entries = [
        {
            "application_type": "section_admin",
            "field_id": "section_admin_board_approved_application_list",
            "document_type": "section_admin_board_approved_application_list",
            "document_count": "single",
            "name_bn": "বোর্ড কর্তৃক অনুমোদিত আবেদনের তালিকা",
            "name_en": "Board approved application list",
            "status": "active",
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            application_type=entry["application_type"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0191_merge_20250922_1518'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
