# Generated by Django 4.2.20 on 2025-09-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0192_seed_document_type_add_section_admin_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='application_summary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplicationsummary'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='application_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_application_summary', to='workforce.workforceapplicationsummary'),
        ),
    ]
