# Generated by Django 4.2.16 on 2025-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0193_historicalworkforcedocument_application_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='workforce_factory_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='workforce_factory_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
