# Generated by Django 4.2.20 on 2025-10-08

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    WorkforceDiseases = apps.get_model('workforce', 'WorkforceDiseases')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # # Delete specific documents if exists
    # WorkforceDocumentType.objects.filter(document_type_no__in=[5, 53, 63, 166, 404, 415]).delete()

    # Update existing records if found
    update_entries = {
        5: {
            "field_id": "43719cf6-3927-4568-b19c-f639277568e9",
            "document_type": "medical certificate",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট",
            "name_en": "medical certificate",
        },
        53: {

            "field_id": "bfc546cc-1588-4e21-8546-cc1588ae21b4",
            "document_type": "medical certificate",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট",
            "name_en": "medical certificate",
        },
        63: {
            "field_id": "2f1062b5-cfef-4605-9062-b5cfefe605cb",
            "document_type": "medical certificate",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট",
            "name_en": "medical certificate",
        },
        166: {
            "field_id": "0f00d6a2-6841-4f76-80d6-a268416f7699",
            "document_type": "medical certificate",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট",
            "name_en": "medical certificate",
        },
        404: {
            "field_id": "f7aa41bd-aee9-426a-aa41-bdaee9726a1c",
            "document_type": "medical certificate",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট",
            "name_en": "medical certificate",
        },
        415: {
            "field_id": "200b3009-d3c6-4008-8b30-09d3c6200896",
            "document_type": "medical certificate",
            "name_bn": "রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট",
            "name_en": "medical certificate",
        }
    }

    for doc_no, update_data in update_entries.items():
        updated_count = WorkforceDocumentType.objects.filter(
            document_type_no=doc_no,
            form_step_no='employeeAccidentInfo'
        ).update(
            **update_data,
            user_updated_id=user_id
        )
        if updated_count == 0:
            print(f"Document type {doc_no} with form_step_no='employeeAccidentInfo' not found. Skipping update.")

    # Add new entries
    new_entries = [
        {
            "document_type_no": 5,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "self",
            "field_id": "c582dc40-a31f-47c8-82dc-40a31ff7c8fc",
            "document_type": "prescription",
            "document_count": "single",
            "name_bn": "চিকিৎসা ব্যবস্থাপত্র",
            "name_en": "prescription",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 5,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "self",
            "field_id": "b90b3efa-7710-42a7-8b3e-fa771042a7b4",
            "document_type": "test report",
            "document_count": "single",
            "name_bn": "টেস্ট রিপোর্টের কপি",
            "name_en": "test report",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 5,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "self",
            "field_id": "34d59dc5-baf5-465e-959d-c5baf5b65ec9",
            "document_type": "discharge certificate",
            "document_count": "single",
            "name_bn": "রচিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 53,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "a790bbcb-451c-4ccd-90bb-cb451c1ccd14",
            "document_type": "prescription",
            "document_count": "single",
            "name_bn": "চিকিৎসা ব্যবস্থাপত্র",
            "name_en": "prescription",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 53,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "a48c9842-e0e9-41a0-8c98-42e0e9b1a0ab",
            "document_type": "test report",
            "document_count": "single",
            "name_bn": "টেস্ট রিপোর্টের কপি",
            "name_en": "test report",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 53,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "self",
            "field_id": "f1fb4459-f1e9-41e8-bb44-59f1e931e831",
            "document_type": "discharge certificate",
            "document_count": "single",
            "name_bn": "রচিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 63,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "e409ce56-851a-4c39-89ce-56851abc3944",
            "document_type": "prescription",
            "document_count": "single",
            "name_bn": "চিকিৎসা ব্যবস্থাপত্র",
            "name_en": "prescription",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 63,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "93862b2b-00cb-423b-862b-2b00cbb23b69",
            "document_type": "test report",
            "document_count": "single",
            "name_bn": "টেস্ট রিপোর্টের কপি",
            "name_en": "test report",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 63,
            "application_type": "medicalDonation",
            "organization_type": "blwf",
            "application_for": "dependent",
            "field_id": "2bf4a355-ba36-4ecd-b4a3-55ba36fecdae",
            "document_type": "discharge certificate",
            "document_count": "single",
            "name_bn": "রচিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 166,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "dependent",
            "field_id": "90e8cc32-bb94-4131-a8cc-32bb9451314a",
            "document_type": "prescription",
            "document_count": "single",
            "name_bn": "চিকিৎসা ব্যবস্থাপত্র",
            "name_en": "prescription",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 166,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "dependent",
            "field_id": "f7fb5a4d-34ec-4aaf-bb5a-4d34ecdaafc1",
            "document_type": "test report",
            "document_count": "single",
            "name_bn": "টেস্ট রিপোর্টের কপি",
            "name_en": "test report",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 166,
            "application_type": "medicalAssistance",
            "organization_type": "cf",
            "application_for": "dependent",
            "field_id": "8ccefed0-527b-42aa-8efe-d0527b02aac4",
            "document_type": "discharge certificate",
            "document_count": "single",
            "name_bn": "রচিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 404,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "516a9d77-82ee-4767-aa9d-7782ee8767e7",
            "document_type": "prescription",
            "document_count": "single",
            "name_bn": "চিকিৎসা ব্যবস্থাপত্র",
            "name_en": "prescription",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 404,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "b4a001fc-18b4-46c5-a001-fc18b4a6c506",
            "document_type": "test report",
            "document_count": "single",
            "name_bn": "টেস্ট রিপোর্টের কপি",
            "name_en": "test report",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 404,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "temporary_disability",
            "field_id": "ffb3f85d-7915-41f6-b3f8-5d7915d1f658",
            "document_type": "discharge certificate",
            "document_count": "single",
            "name_bn": "রচিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 415,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "2ed13941-688b-4f73-9139-41688bbf7350",
            "document_type": "prescription",
            "document_count": "single",
            "name_bn": "চিকিৎসা ব্যবস্থাপত্র",
            "name_en": "prescription",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 415,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "1e35689e-6ee7-42a3-b568-9e6ee792a328",
            "document_type": "test report",
            "document_count": "single",
            "name_bn": "টেস্ট রিপোর্টের কপি",
            "name_en": "test report",
            "status": "active",
            "mandatory_for_applicant": True
        },
        {
            "document_type_no": 415,
            "application_type": "disabilityAssistance",
            "organization_type": "cf",
            "application_for": "permanent_disability",
            "field_id": "5be61354-05cb-46c1-a613-5405cb96c131",
            "document_type": "discharge certificate",
            "document_count": "single",
            "name_bn": "রচিকিৎসা ছাড়পত্রের অনুলিপি",
            "name_en": "discharge certificate",
            "status": "active",
            "mandatory_for_applicant": True
        },
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=entry["mandatory_for_applicant"],
            user_created_id=user_id,
            user_updated_id=user_id,
            form_step_no="employeeAccidentInfo"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0193_historicalworkforcedocument_application_summary_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
