# Generated by Django 4.2.20 on 2025-10-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0194_historicalworkforceemployee_workforce_factory_id_and_more'),
        ('workforce', '0194_update_document_type_for_medical_documents_and_add_new'),
    ]

    operations = [
    ]
