# Generated by Django 4.2.20 on 2025-10-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0195_merge_20251008_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceemployee',
            name='workforce_factory_id',
        ),
        migrations.RemoveField(
            model_name='workforceemployee',
            name='workforce_factory_id',
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='workforce_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_employee_factory', to='workforce.workforcefactory'),
        ),
    ]
