# Generated by Django 4.2.20 on 2025-10-08

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # # Delete specific documents if exists
    # WorkforceDocumentType.objects.filter(document_type_no__in=[5, 53, 63, 166, 404, 415]).delete()

    # Update existing records if found
    update_entries = {
        5: {
            "name_bn": "চিকিৎসা ছাড়পত্রের অনুলিপি",
        },
        53: {
            "name_bn": "চিকিৎসা ছাড়পত্রের অনুলিপি",
        },
        63: {
            "name_bn": "চিকিৎসা ছাড়পত্রের অনুলিপি",
        },
        166: {
            "name_bn": "চিকিৎসা ছাড়পত্রের অনুলিপি",
        },
        404: {
            "name_bn": "চিকিৎসা ছাড়পত্রের অনুলিপি",
        },
        415: {
            "name_bn": "চিকিৎসা ছাড়পত্রের অনুলিপি",
        }
    }

    for doc_no, update_data in update_entries.items():
        updated_count = WorkforceDocumentType.objects.filter(
            document_type_no=doc_no,
            form_step_no='employeeAccidentInfo'
        ).update(
            **update_data,
            user_updated_id=user_id
        )
        if updated_count == 0:
            print(f"Document type {doc_no} with form_step_no='employeeAccidentInfo' not found. Skipping update.")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0196_remove_historicalworkforceemployee_workforce_factory_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
