# Generated by Django 4.2.20 on 2025-10-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0197_update_document_type_spelling_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_diagnosis',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_flag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_recommended_donation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='last_base_salary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_diagnosis',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_flag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_recommended_donation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='last_base_salary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
