# Generated by Django 4.2.20 on 2025-10-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('workforce', '0198_historicalworkforceapplication_doctors_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceapplicationmovement',
            name='from_role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.role'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='from_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_role', to='core.role'),
        ),
    ]
