# Generated by Django 4.2.20 on 2025-10-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0199_alter_historicalworkforceapplicationmovement_from_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceapplicationmovement',
            name='to_role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.role'),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='to_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_role', to='core.role'),
        ),
    ]
