# Generated by Django 4.2.20 on 2025-10-21

from django.db import migrations
from django.db.models import Count


def clear_to_role(apps, schema_editor):
    """Set all WorkforceApplicationMovement.to_role = NULL"""
    WorkforceApplicationMovement = apps.get_model('workforce', 'WorkforceApplicationMovement')
    WorkforceApplicationMovement.objects.update(to_role=None)


def clean_duplicate_roles(apps, schema_editor):
    """Remove duplicate Roles, keeping only the one where validity_to is NULL (if any)."""
    Role = apps.get_model('core', 'Role')

    duplicates = (
        Role.objects.values('name')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        role_name = dup['name']
        roles = Role.objects.filter(name=role_name)

        keep = roles.filter(validity_to__isnull=True).first()
        if keep:
            roles.exclude(id=keep.id).delete()
        else:
            keep = roles.first()
            roles.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0200_alter_historicalworkforceapplicationmovement_to_role_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_to_role),
        migrations.RunPython(clean_duplicate_roles),
    ]
