# Generated by Django 4.2.20 on 2025-07-30

from django.db import migrations
import uuid
from django.utils import timezone
from django.conf import settings


def seed_grant_money(apps, schema_editor):
    WorkforceGrantMoney = apps.get_model('workforce', 'WorkforceGrantMoney')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    user = User.objects.get(username="Admin")
    user_id = user.id

    now = timezone.now()

    seed_data = [
        {
            "organization_type": "eis",
            "application_type": "financialAssistance",
            "application_type_no": "10",
            "application_type_name_bn": "মৃত্যুজনিত অনুদান",
            "application_type_name_en": "Death grant",
        },
        {
            "organization_type": "eis",
            "application_type": "disabilityAssistance",
            "application_type_no": "11",
            "application_type_name_bn": "স্থায়ী ও আংশিক অক্ষমতা জনিত আর্থিক সহায়তা",
            "application_type_name_en": "Disability assistance",
        }
    ]

    for item in seed_data:
        WorkforceGrantMoney.objects.create(
            id=uuid.uuid4(),
            organization_type=item["organization_type"],
            application_type=item["application_type"],
            status="active",
            user_created_id=user_id,
            user_updated_id=user_id,
            application_type_no=item["application_type_no"],
            application_type_name_bn=item["application_type_name_bn"],
            application_type_name_en=item["application_type_name_en"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0201_clean_workforce_application_movement__to_role_id_set_all_to_null'),
    ]

    operations = [
        migrations.RunPython(seed_grant_money),
    ]
