# Generated by Django 4.2.20 on 2025-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0202_seed_add_eis_grantmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_flag_note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_flag_note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
