# Generated by Django 4.2.20 on 2025-10-21

from django.db import migrations
import uuid


def copy_cf_documents_to_eis(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')

    # Filter source records
    cf_docs = WorkforceDocumentType.objects.filter(
        organization_type='cf',
        application_type__in=['financialAssistance', 'disabilityAssistance']
    )

    if not cf_docs.exists():
        print("No matching 'cf' documents found — skipping copy.")
        return

    copied_count = 0

    for doc in cf_docs:

        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            field_id=uuid.uuid4(),
            application_type=doc.application_type,
            document_type=doc.document_type,
            document_count=doc.document_count,
            name_bn=doc.name_bn,
            name_en=doc.name_en,
            status=doc.status,
            application_for=doc.application_for,
            document_type_no=doc.document_type_no,
            organization_type='eis',
            mandatory_for_applicant=doc.mandatory_for_applicant,
            form_step_no=doc.form_step_no,
            user_created_id=doc.user_created_id,
            user_updated_id=doc.user_updated_id,
        )
        copied_count += 1

    print(f"Copied {copied_count} WorkforceDocumentType records from 'cf' to 'eis'.")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0203_historicalworkforceapplication_doctors_flag_note_and_more'),  # adjust if needed
    ]

    operations = [
        migrations.RunPython(copy_cf_documents_to_eis),
    ]
