# Generated by Django 4.2.20 on 2025-10-21

from django.db import migrations


def update_name_bn(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')

    eng_to_bn = {
        'medical certificate': 'রেজিস্টার্ড চিকিৎসক কর্তৃক প্রদত্ত মেডিকেল সার্টিফিকেট',
        'prescription': 'চিকিৎসা ব্যবস্থাপত্র',
        'test report': 'টেস্ট রিপোর্টের কপি',
        'discharge certificate': 'চিকিৎসা ছাড়পত্রের অনুলিপি',
    }

    normalized_map = {k.strip().lower(): v for k, v in eng_to_bn.items()}

    qs = WorkforceDocumentType.objects.filter(name_bn='চিকিৎসা ছাড়পত্রের অনুলিপি')

    updated_count = 0
    for doc in qs:
        if not doc.name_en:
            continue

        name_en_norm = doc.name_en.strip().lower()
        if name_en_norm in normalized_map:
            new_bn = normalized_map[name_en_norm]

            if doc.name_bn != new_bn:
                doc.name_bn = new_bn
                doc.save(update_fields=['name_bn'])
                updated_count += 1

    print(f"Updated {updated_count} WorkforceDocumentType records (filtered by name_bn='চিকিৎসা ছাড়পত্রের অনুলিপি').")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0204_seed_document_type_add_eis_documents'),
    ]

    operations = [
        migrations.RunPython(update_name_bn),
    ]
