# Generated by Django 4.2.20 on 2025-10-26

from django.db import migrations
from django.conf import settings
import uuid


def seed_grant_money(apps, schema_editor):
    WorkforceAssociation = apps.get_model('workforce', 'WorkforceAssociation')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    seed_data = [
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, ঢাকা",
            "office_name_en": "Deputy Inspector Generals office, Dhaka",
            "jurisdiction_locations": "29962",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, গাজীপুর",
            "office_name_en": "Deputy Inspector Generals office, Gazipur",
            "jurisdiction_locations": "33973",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, নারায়ণগঞ্জ",
            "office_name_en": "Deputy Inspector Generals office, Narayanganj",
            "jurisdiction_locations": "45737",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, মুন্সিগঞ্জ",
            "office_name_en": "Deputy Inspector Generals office, Munshiganj",
            "jurisdiction_locations": "43862",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, ফরিদপুর",
            "office_name_en": "Deputy Inspector Generals office, Faridpur",
            "jurisdiction_locations": "32098,49283",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, নরসিংদী",
            "office_name_en": "Deputy Inspector Generals office, Narsingdi",
            "jurisdiction_locations": "46803",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, কিশোরগঞ্জ",
            "office_name_en": "Deputy Inspector Generals office, Kishoreganj",
            "jurisdiction_locations": "39079",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, ময়মনসিংহ",
            "office_name_en": "Deputy Inspector Generals office, Mymensingh",
            "jurisdiction_locations": "73366,76833",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, টাঙ্গাইল",
            "office_name_en": "Deputy Inspector Generals office, Tangail",
            "jurisdiction_locations": "51337",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, চট্টগ্রাম",
            "office_name_en": "Deputy Inspector Generals office, Chattogram",
            "jurisdiction_locations": "14782",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, কুমিল্লা",
            "office_name_en": "Deputy Inspector Generals office, Cumilla",
            "jurisdiction_locations": "18556,11631",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, সিলেট",
            "office_name_en": "Deputy Inspector Generals office, Sylhet",
            "jurisdiction_locations": "111038,109421",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, মৌলভীবাজার",
            "office_name_en": "Deputy Inspector Generals office, Moulvibazar",
            "jurisdiction_locations": "107678,106096",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, খুলনা",
            "office_name_en": "Deputy Inspector Generals office, Khulna",
            "jurisdiction_locations": "62882,55104,68288",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, যশোর",
            "office_name_en": "Deputy Inspector Generals office, Jashore",
            "jurisdiction_locations": "58258,67129,66182,61277",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, কুষ্টিয়া",
            "office_name_en": "Deputy Inspector Generals office, Kushtia",
            "jurisdiction_locations": "64495,66761,57489",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, বরিশাল",
            "office_name_en": "Deputy Inspector Generals office, Barishal",
            "jurisdiction_locations": "1322,5155,3045,2,4128,7376",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, রাজশাহী",
            "office_name_en": "Deputy Inspector Generals office, Rajshahi",
            "jurisdiction_locations": "89984,83539",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, পাবনা",
            "office_name_en": "Deputy Inspector Generals office, Pabna",
            "jurisdiction_locations": "88322,87187",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, সিরাজগঞ্জ",
            "office_name_en": "Deputy Inspector Generals office, Sirajganj",
            "jurisdiction_locations": "91762",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, বগুড়া",
            "office_name_en": "Deputy Inspector Generals office, Bogura",
            "jurisdiction_locations": "80858",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, রংপুর",
            "office_name_en": "Deputy Inspector Generals office, Rangpur",
            "jurisdiction_locations": "103124,96761,98927,100375,100972",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, দিনাজপুর",
            "office_name_en": "Deputy Inspector Generals office, Dinajpur",
            "jurisdiction_locations": "94548,105014,102373",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, ফেনী",
            "office_name_en": "Deputy Inspector Generals office, Feni",
            "jurisdiction_locations": "22893,26668,24368",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, কক্সবাজার",
            "office_name_en": "Deputy Inspector Generals office, Cox’s Bazar",
            "jurisdiction_locations": "21925",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, রাঙ্গামাটি",
            "office_name_en": "Deputy Inspector Generals office, Rangamati",
            "jurisdiction_locations": "29696,8713,24121",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, ব্রাহ্মণবাড়িয়া",
            "office_name_en": "Deputy Inspector Generals office, Brahmanbaria",
            "jurisdiction_locations": "8834",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, নওগাঁ",
            "office_name_en": "Deputy Inspector Generals office, Naogaon",
            "jurisdiction_locations": "85064,84577",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, জামালপুর",
            "office_name_en": "Deputy Inspector Generals office, Jamalpur",
            "jurisdiction_locations": "70637,79171",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, গোপালগঞ্জ",
            "office_name_en": "Deputy Inspector Generals office, Gopalganj",
            "jurisdiction_locations": "36601,40826,50144",
            "association_type": "dife",
        },
        {
            "office_name_bn": "উপমহাপরিদর্শকের কার্যালয়, মানিকগঞ্জ",
            "office_name_en": "Deputy Inspector Generals office, Manikganj",
            "jurisdiction_locations": "42490",
            "association_type": "dife",
        },
        {
            "office_name_bn": "বিভাগীয় শ্রম দপ্তর, ঢাকা",
            "office_name_en": "Divisional Labour Office, Dhaka",
            "jurisdiction_locations": "29962,33973,42490,51337",
            "association_type": "dol",
        },
        {
            "office_name_bn": "বিভাগীয় শ্রম দপ্তর, নারায়ণগঞ্জ",
            "office_name_en": "Divisional Labour Office, Narayanganj",
            "jurisdiction_locations": "43862,45737,46803",
            "association_type": "dol",
        },
        {
            "office_name_bn": "বিভাগীয় শ্রম দপ্তর, চট্টগ্রাম",
            "office_name_en": "Divisional Labour Office, Chattogram",
            "jurisdiction_locations": "14782,8713,21925,29696,24121",
            "association_type": "dol",
        },
        {
            "office_name_bn": "বিভাগীয় শ্রম দপ্তর, রাজশাহী",
            "office_name_en": "Divisional Labour Office, Rajshahi",
            "jurisdiction_locations": "89984,83539,87187,88322",
            "association_type": "dol",
        },
        {
            "office_name_bn": "বিভাগীয় শ্রম দপ্তর, খুলনা",
            "office_name_en": "Divisional Labour Office, Khulna",
            "jurisdiction_locations": "62882,68288,58258,55104,66182,67129",
            "association_type": "dol",
        },
        {
            "office_name_bn": "বিভাগীয় শ্রম দপ্তর, মৌলভীবাজার",
            "office_name_en": "Divisional Labour Office, Moulvibazar",
            "jurisdiction_locations": "107678,106096",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, সিলেট",
            "office_name_en": "Regional Labour Office, Sylhet",
            "jurisdiction_locations": "111038,109421,8834",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, রংপুর",
            "office_name_en": "Regional Labour Office, Rangpur",
            "jurisdiction_locations": "103124,100972,98927,100375",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, দিনাজপুর",
            "office_name_en": "Regional Labour Office, Dinajpur",
            "jurisdiction_locations": "94548,105014,102373",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, বগুড়া",
            "office_name_en": "Regional Labour Office, Bogura",
            "jurisdiction_locations": "80858,96761,84577,91762,85064",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, কুষ্টিয়া",
            "office_name_en": "Regional Labour Office, Kushtia",
            "jurisdiction_locations": "64495,57489,61277,66761",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, বরিশাল",
            "office_name_en": "Regional Labour Office, Barishal",
            "jurisdiction_locations": "1322,4128,7376,5155,2,3045",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, ফরিদপুর",
            "office_name_en": "Regional Labour Office, Faridpur",
            "jurisdiction_locations": "32098,49283,36601,50144,40826",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, ময়মনসিংহ",
            "office_name_en": "Regional Labour Office, Mymensingh",
            "jurisdiction_locations": "73366,39079,79171,76833,70637",
            "association_type": "dol",
        },
        {
            "office_name_bn": "আঞ্চলিক শ্রম দপ্তর, কুমিল্লা",
            "office_name_en": "Regional Labour Office, Cumilla",
            "jurisdiction_locations": "18556,11631,24368,22893,26668",
            "association_type": "dol",
        }
    ]

    for item in seed_data:
        WorkforceAssociation.objects.create(
            id=uuid.uuid4(),
            office_name_bn=item["office_name_bn"],
            office_name_en=item["office_name_en"],
            jurisdiction_locations=item["jurisdiction_locations"],
            association_type=item["association_type"],
            status="active",
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0206_workforceassociation_historicalworkforceassociation'),
    ]

    operations = [
        migrations.RunPython(seed_grant_money),
    ]
