# Generated by Django 4.2.20 on 2025-10-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0207_seed_association_office_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceorganizationemployee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workforceorganizationemployee',
            name='location',
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationemployee',
            name='name_bn',
            field=models.CharField(blank=True, db_comment='Translatable name field. May use any language', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationemployee',
            name='name_en',
            field=models.CharField(blank=True, db_comment='English name field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployee',
            name='name_bn',
            field=models.CharField(blank=True, db_comment='Translatable name field. May use any language', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployee',
            name='name_en',
            field=models.CharField(blank=True, db_comment='English name field', max_length=255, null=True),
        ),
    ]
