# Generated by Django 4.2.23 on 2025-10-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0207_seed_association_office_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='isEligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='isEligible',
            field=models.BooleanField(default=False),
        ),
    ]
