# Generated by Django 4.2.25 on 2025-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0208_historicalworkforceemployeedependent_iseligible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='disability_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='disability_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
