# Generated by Django 4.2.20 on 2025-10-27
import uuid
import datetime
from django.db import migrations
from django.conf import settings


def seed_interactive_users_and_employees_for_association_admin(apps, schema_editor):
    WorkforceAssociation = apps.get_model('workforce', 'WorkforceAssociation')
    WorkforceOrganizationEmployee = apps.get_model('workforce', 'WorkforceOrganizationEmployee')
    InteractiveUser = apps.get_model('core', 'InteractiveUser')
    Role = apps.get_model('core', 'Role')
    UserRole = apps.get_model('core', 'UserRole')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    admin_user = User.objects.filter(username="Admin").first()
    role_instance = Role.objects.get(name='blwf_dol_dife')

    def create_interactive_user(last_name, other_names, login_name, role_id):
        interactive_user = InteractiveUser.objects.create(
            language_id="fr",
            last_name=last_name,
            other_names=other_names,
            login_name=login_name,
            audit_user_id=1,
            role_id=role_id,
            private_key="C1C224B03CD9BC7B6A86D77F5DACE40191766C485CD55DC48CAF9AC873335D6F",
            password="59E66831C680C19E8736751D5480A7C3291BD8775DF47C19C4D0361FBC1C3438",
        )

        # Create core User
        user_core = User.objects.create(
            username=interactive_user.login_name,
            i_user_id=interactive_user.id,
        )

        # Create UserRole (skip if already exists)
        if not UserRole.objects.filter(user_id=interactive_user.id, role_id=role_id).exists():
            UserRole.objects.create(
                user_id=interactive_user.id,
                role_id=role_id,
                validity_from=datetime.date.today(),
                audit_user_id=1,
            )

        return interactive_user

    def generate_login_name(office_name_en):
        name = office_name_en.strip()
        parts = [p.strip() for p in name.split(",", 1)]
        before_comma = parts[0].lower()
        after_comma = parts[1].lower() if len(parts) > 1 else ""

        prefix = ""
        if "deputy inspector general" in before_comma:
            prefix = "dig"
        elif "divisional labour office" in before_comma:
            prefix = "dlo"
        elif "regional labour office" in before_comma:
            prefix = "rlo"

        suffix = after_comma.replace(" ", "_").replace("’", "").replace("'", "")
        return f"{prefix}_{suffix}" if suffix else prefix

    associations = WorkforceAssociation.objects.all()

    for assoc in associations:
        office_name_en = assoc.office_name_en.strip()
        office_name_bn = assoc.office_name_bn.strip()
        login_name = generate_login_name(office_name_en)

        if InteractiveUser.objects.filter(login_name=login_name).exists():
            continue

        user = create_interactive_user(
            last_name=office_name_en,
            other_names=office_name_bn,
            login_name=login_name,
            role_id=role_instance.id,
        )

        WorkforceOrganizationEmployee.objects.create(
            id=uuid.uuid4(),
            name_bn=office_name_bn,
            name_en=office_name_en,
            related_user_id=user.id,
            status="active",
            user_created_id=admin_user.id,
            user_updated_id=admin_user.id,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('workforce', '0208_remove_historicalworkforceorganizationemployee_location_and_more'),
    ]

    operations = [
        migrations.RunPython(
            seed_interactive_users_and_employees_for_association_admin,
        ),
    ]
