# Generated by Django 4.2.20 on 2025-10-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0209_seed_workforce_organization_employee_dol_dife_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceorganizationemployee',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
        migrations.AddField(
            model_name='workforceorganizationemployee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
    ]
