# Generated by Django 4.2.25 on 2025-11-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0209_historicalworkforceemployeedependent_disability_type_and_more'),
        ('workforce', '0210_historicalworkforceorganizationemployee_location_and_more'),
    ]

    operations = [
    ]
