# Generated by Django 4.2.20 on 2025-11-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0211_merge_20251102_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceorganizationemployee',
            name='association',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceassociation'),
        ),
        migrations.AddField(
            model_name='workforceorganizationemployee',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_employee_association', to='workforce.workforceassociation'),
        ),
    ]
