# Generated by Django 4.2.20 on 2025-11-02

from django.db import migrations


def populate_employee_association(apps, schema_editor):
    WorkforceOrganizationEmployee = apps.get_model('workforce', 'WorkforceOrganizationEmployee')
    WorkforceAssociation = apps.get_model('workforce', 'WorkforceAssociation')

    for employee in WorkforceOrganizationEmployee.objects.filter(association__isnull=True, name_en__isnull=False):
        try:
            # Match employee name_en with association office_name_en
            association = WorkforceAssociation.objects.get(office_name_en=employee.name_en)
            employee.association_id = association.id
            employee.save(update_fields=['association'])
            print(f"Linked employee '{employee.name_en}' to association '{association.office_name_en}'")
        except WorkforceAssociation.DoesNotExist:
            print(f"No association found for employee '{employee.name_en}'")
        except WorkforceAssociation.MultipleObjectsReturned:
            print(f"Multiple associations found for employee '{employee.name_en}' — skipped.")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0212_historicalworkforceorganizationemployee_association_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_employee_association),
    ]
