# Generated by Django 4.2.20 on 2025-11-03

from django.db import migrations
from django.conf import settings


def update_form_step_no(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    try:
        user = User.objects.get(username="Admin")
        user_id = user.id
    except User.DoesNotExist:
        user_id = None
        print("Admin user not found. Proceeding without user_updated_id.")

    # Fetch all records to update
    docs = WorkforceDocumentType.objects.filter(form_step_no="institutionalInfo")
    count = docs.count()

    for doc in docs:
        doc.form_step_no = "institutionInfo"
        if user_id:
            doc.user_updated_id = user_id
        doc.save()

    print(f"Updated {count} WorkforceDocumentType records from 'institutionalInfo' to 'institutionInfo'.")


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0213_seed_relate_fk_relation_of_workforce_organization_employee_and_workforce_association'),
    ]

    operations = [
        migrations.RunPython(update_form_step_no),
    ]
