# Generated by Django 4.2.25 on 2025-11-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0213_seed_relate_fk_relation_of_workforce_organization_employee_and_workforce_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_calculated_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_number_of_payment_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.bank'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='bank_account_no',
            field=models.BigIntegerField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='eis_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='eis_calculated_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='eis_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='parent_dependent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeedependent'),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_calculated_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_number_of_payment_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_banks', to='workforce.bank'),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='bank_account_no',
            field=models.BigIntegerField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='eis_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='eis_calculated_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='eis_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='parent_dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='workforce.workforceemployeedependent'),
        ),
    ]
