# Generated by Django 4.2.20 on 2025-11-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0214_historicalworkforceapplication_eis_approved_amount_and_more'),
        ('workforce', '0214_seed_update_document_type_change_form_step_no'),
    ]

    operations = [
    ]
