# Generated by Django 4.2.20 on 2025-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0215_merge_20251104_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='deceased_worker_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='deceased_worker_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
