# Generated by Django 4.2.20 on 2025-11-10

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Add new entries
    new_entries = [
        {
            "application_type": "financialAssistance",
            "field_id": "aca0b050-5958-4733-a0b0-50595807334b",
            "organization_type": "eis",
            "form_step_no": "employeeDependentInfo",
            "application_for": "dependent",
            "document_type_no": "420",
            "document_type": "disability_certificate",
            "document_count": "single",
            "name_bn": "প্রতিবন্ধী সনদ",
            "name_en": "Disability Certificate",
            "status": "active",
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            application_type=entry["application_type"],
            field_id=entry["field_id"],
            organization_type=entry["organization_type"],
            form_step_no=entry["form_step_no"],
            application_for=["application_for"],
            document_type=entry["document_type"],
            document_type_no=entry["document_type_no"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            status=entry["status"],
            mandatory_for_applicant=True,
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0216_historicalworkforceapplication_deceased_worker_info_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
