# Generated by Django 4.2.25 on 2025-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0217_workforceeispaymentprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
