# Generated by Django 4.2.20 on 2025-11-11

from django.db import migrations
from django.conf import settings
import uuid


def seed_workforce_documents(apps, schema_editor):
    WorkforceDocumentType = apps.get_model('workforce', 'WorkforceDocumentType')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    # Update existing records if found
    update_entries = {
        420: {
            "application_for": "normal_death"
        }
    }

    for doc_no, update_data in update_entries.items():
        try:
            doc = WorkforceDocumentType.objects.get(document_type_no=doc_no, organization_type='eis')
            for key, value in update_data.items():
                setattr(doc, key, value)
            doc.user_updated_id = user_id
            doc.save()
        except WorkforceDocumentType.DoesNotExist:
            print(f"Document type {doc_no} not found. Skipping update.")

    # Add new entries
    new_entries = [
        {
            "document_type_no": 421,
            "application_type": "financialAssistance",
            "field_id": "e5264347-886e-49aa-a643-47886e39aab0",
            "organization_type": "eis",
            "form_step_no": "employeeDependentInfo",
            "application_for": "accidental_death",
            "document_type": "disability_certificate",
            "document_count": "single",
            "name_bn": "প্রতিবন্ধী সনদ",
            "name_en": "Disability Certificate",
            "status": "active",
            "mandatory_for_applicant": True
        }
    ]

    for entry in new_entries:
        WorkforceDocumentType.objects.create(
            id=uuid.uuid4(),
            document_type_no=entry["document_type_no"],
            application_type=entry["application_type"],
            organization_type=entry["organization_type"],
            application_for=entry["application_for"],
            field_id=entry["field_id"],
            document_type=entry["document_type"],
            document_count=entry["document_count"],
            name_bn=entry["name_bn"],
            name_en=entry["name_en"],
            form_step_no=entry["form_step_no"],
            status=entry["status"],
            mandatory_for_applicant=entry["mandatory_for_applicant"],
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0217_seed_document_type_add_disability_document'),
    ]

    operations = [
        migrations.RunPython(seed_workforce_documents),
    ]
