# Generated by Django 4.2.20 on 2025-11-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0218_seed_document_type_add_and_update_disability_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='disability_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='eis_insurance_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='email',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='gender',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='life_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='marital_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='nid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='occupation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='relation_with_worker',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='disability_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='eis_insurance_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='email',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='gender',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='life_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='marital_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='name_bn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='nid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='occupation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='relation_with_worker',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
