# Generated by Django 4.2.25 on 2025-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0218_historicalworkforceeispaymentdisbursement_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentprocess',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursement',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentprocess',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
