# Generated by Django 4.2.25 on 2025-11-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0219_alter_historicalworkforceeispaymentdisbursement_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceemployeedependent',
            old_name='isEligible',
            new_name='is_eligible',
        ),
        migrations.RenameField(
            model_name='workforceemployeedependent',
            old_name='isEligible',
            new_name='is_eligible',
        ),
    ]
