# Generated by Django 4.2.25 on 2025-11-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0217_seed_document_type_add_disability_document'),
        ('workforce', '0220_rename_iseligible_historicalworkforceemployeedependent_is_eligible_and_more'),
    ]

    operations = [
    ]
