# Generated by Django 4.2.25 on 2025-11-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0221_merge_20251111_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='initial_replacement_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='pv_factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='initial_replacement_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='pv_factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
