# Generated by Django 4.2.25 on 2025-11-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0222_historicalworkforceemployeedependent_eis_initial_monthly_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceapplication',
            name='eis_number_of_payment_months',
        ),
        migrations.RemoveField(
            model_name='workforceapplication',
            name='eis_number_of_payment_months',
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='initial_replacement_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='pv_factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='initial_replacement_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='pv_factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
