# Generated by Django 4.2.26 on 2025-11-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0223_remove_historicalworkforceapplication_eis_number_of_payment_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
