# Generated by Django 4.2.20 on 2025-11-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0219_alter_historicalworkforceemployeedependent_birth_certificate_no_and_more'),
        ('workforce', '0224_alter_historicalworkforceemployeedependent_bank_account_no_and_more'),
    ]

    operations = [
    ]
