# Generated by Django 4.2.20 on 2025-11-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0225_merge_20251116_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeebankinginfo',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeebankinginfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeebankinginfo',
            name='nid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeebankinginfo',
            name='relation_with_dependent',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='banking_info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeebankinginfo'),
        ),
        migrations.AddField(
            model_name='workforceemployeebankinginfo',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeebankinginfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeebankinginfo',
            name='nid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeebankinginfo',
            name='relation_with_dependent',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='banking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependent_employee_banking_info', to='workforce.workforceemployeebankinginfo'),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='eis_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
