# Generated by Django 4.2.25 on 2025-11-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_location_zip_code_w_id'),
        ('workforce', '0226_historicalworkforceemployeebankinginfo_bank_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='License_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='approximate_number_of_employee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='business_sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='date_of_eis_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='date_of_factory_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='future_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='group_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='license_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='lima_registration_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='membership_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='office_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='License_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='approximate_number_of_employee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='business_sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='date_of_eis_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='date_of_factory_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='future_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='group_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='license_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='lima_registration_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='membership_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='office_location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='historicalworkforcefactory',
            name='name_bn',
            field=models.TextField(db_comment='Translatable name field. May use any language'),
        ),
        migrations.AlterField(
            model_name='historicalworkforcefactory',
            name='name_en',
            field=models.TextField(db_comment='English name field'),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='location.location'),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='name_bn',
            field=models.TextField(db_comment='Translatable name field. May use any language'),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='name_en',
            field=models.TextField(db_comment='English name field'),
        ),
    ]
