# Generated by Django 4.2.25 on 2025-11-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0227_historicalworkforcefactory_license_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforcefactory',
            old_name='License_no',
            new_name='license_no',
        ),
        migrations.RenameField(
            model_name='workforcefactory',
            old_name='License_no',
            new_name='license_no',
        ),
    ]
