# Generated by Django 4.2.25 on 2025-11-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0228_rename_license_no_historicalworkforcefactory_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeebankinginfo',
            name='account_holder_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeebankinginfo',
            name='parent_dependent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeedependent'),
        ),
        migrations.AddField(
            model_name='workforceemployeebankinginfo',
            name='account_holder_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeebankinginfo',
            name='parent_dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_banking_parent_dependent', to='workforce.workforceemployeedependent'),
        ),
    ]
