# Generated by Django 4.2.25 on 2025-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0229_historicalworkforceemployeebankinginfo_account_holder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='account_holder_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='account_holder_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
