# Generated by Django 4.2.25 on 2025-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0230_historicalworkforceemployeedependent_account_holder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='account_holder_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='account_holder_nid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='account_holder_relation_with_dependent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='account_holder_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='account_holder_nid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='account_holder_relation_with_dependent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
