# Generated by Django 4.2.20 on 2025-12-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0231_historicalworkforceemployeedependent_account_holder_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforcedocument',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='workforcedocument',
            name='holder',
        ),
    ]
