# Generated by Django 4.2.20 on 2025-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0233_historicalworkforcedocument_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_entry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_entry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
