# Generated by Django 4.2.25 on 2025-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0234_historicalworkforceapplication_doctors_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
