# Generated by Django 4.2.20 on 2025-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0235_historicalworkforceemployeedependent_dummy_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='beneficiary_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='beneficiary_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
