# Generated by Django 4.2.26 on 2025-12-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0236_historicalworkforceeispaymentprocess_beneficiary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceassociation',
            name='minimum_salary',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceassociation',
            name='minimum_salary',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True),
        ),
    ]
