# Generated by Django 4.2.26 on 2025-12-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0237_historicalworkforceassociation_minimum_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='minimum_salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='minimum_salary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
    ]
