# Generated by Django 4.2.25 on 2025-12-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0239_alter_historicalworkforceemployeedependent_permanent_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceemployeebankinginfo',
            old_name='bank',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='workforceemployeebankinginfo',
            old_name='bank',
            new_name='branch',
        ),
    ]
