# Generated by Django 4.2.20 on 2025-12-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0240_rename_bank_historicalworkforceemployeebankinginfo_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='workforce_employee_banking_info',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeebankinginfo'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='workforce_employee_banking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_banking_info_for_documents', to='workforce.workforceemployeebankinginfo'),
        ),
    ]
