# Generated by Django 4.2.25 on 2025-12-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0241_historicalworkforcedocument_workforce_employee_banking_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='eis_initial_monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
    ]
