# Generated by Django 4.2.20 on 2025-12-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0242_historicalworkforceeispaymentdisbursement_eis_initial_monthly_amount_and_more'),
        ('workforce', '0242_workforceallassociation_and_more'),
    ]

    operations = [
    ]
