# Generated by Django 4.2.25 on 2025-12-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0242_historicalworkforceeispaymentdisbursement_eis_initial_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='eis_initial_replacement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='eis_initial_replacement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='eis_initial_replacement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='eis_initial_replacement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
