# Generated by Django 4.2.25 on 2025-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0243_historicalworkforceeispaymentdisbursement_eis_initial_replacement_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
