# Custom migration on 2025-12-23

from django.db import migrations
from django.conf import settings
import uuid


def seed_all_association(apps, schema_editor):
    WorkforceAllAssociation = apps.get_model('workforce', 'WorkforceAllAssociation')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    user = User.objects.get(username="Admin")
    user_id = user.id

    seed_data = [
      {
        "no": "1",
        "association_name_en": "Association of Export Oriented Ship Building Industries of Bangladesh",
        "association_name_bn": "বাংলাদেশ রপ্তানিমুখী জাহাজ নির্মাণ শিল্প সমিতি",
        "short_name_en": "AEOSBIB",
        "short_name_bn": "এইওএসবিব",
        "address": "03 Motijheel C/A, Dhaka-1000.",
        "phone": "9.5672E+20",
      },
      {
        "no": "2",
        "association_name_en": "Bangladesh Agro-Processors’ Association",
        "association_name_bn": "বাংলাদেশ কৃষি প্রক্রিয়াজাতকারক সমিতি",
        "short_name_en": "BAPA",
        "short_name_bn": "বাপা",
        "address": "House # 15 (1st Floor West Side) Road # 16 (New) 27(Old) Dhanmondi R/A, Dhaka-1209",
        "phone": "8144536, 01730-302198, 01711-647585",
      },
      {
        "no": "3",
        "association_name_en": "Bangladesh Association of Software & Information Services",
        "association_name_bn": "বাংলাদেশ অ্যাসোসিয়েশন অব সফটওয়্যার অ্যান্ড ইনফরমেশন সার্ভিসেস (বেসিস)",
        "short_name_en": "BASIS",
        "short_name_bn": "বেসিস",
        "address": "BDBL Bhaban (5th floor-West) 12 Kawran Bazar, Dhaka-1215.",
        "phone": "8151196-7, 8144708-9",
      },
      {
        "no": "4",
        "association_name_en": "Bangladesh Aushad Shilpa Samity",
        "association_name_bn": "বাংলাদেশ ঔষধ শিল্প সমিতি",
        "short_name_en": "BASS",
        "short_name_bn": "বাস",
        "address": "House # 41 (Level-1) Road # 4, Block-F Banani, Dhaka-1213",
        "phone": "8816767, 9889731, 8824163",
      },
      {
        "no": "5",
        "association_name_en": "Bangladesh Ayurvedic Medicine Manufacturers Association",
        "association_name_bn": "বাংলাদেশ আয়ুর্বেদিক ঔষধ প্রস্তুতকারক সমিতি",
        "short_name_en": "BAMMA",
        "short_name_bn": "বামা",
        "address": "BPL Bhaban (3rd Floor) 89- 89/1, Arambagh Motijheel C/A, Dhaka-1000",
        "phone": "7445525, 01714-171769",
      },
      {
        "no": "6",
        "association_name_en": "Bangladesh Backward Linkage Manufacturers and Exporters Association",
        "association_name_bn": "বাংলাদেশ ব্যাকওয়ার্ড লিংকেজ ম্যানুফ্যাকচারার্স অ্যান্ড এক্সপোর্টার্স অ্যাসোসিয়েশন",
        "short_name_en": "BBLMEA",
        "short_name_bn": "বিবিএলএমইএ",
        "address": "House # 15, Road # 12, Block # F Niketan, Gulshan-1, Dhaka-1212",
        "phone": "8836015-7(O), 8836075, 8113661",
      },
      {
        "no": "7",
        "association_name_en": "Bangladesh Betel Leafs(Pan) Exporters’ Association",
        "association_name_bn": "বাংলাদেশ পান (পাতা) রপ্তানিকারক সমিতি",
        "short_name_en": "BBLEA",
        "short_name_bn": "বিবিএলইএ",
        "address": "Ispahani Building (8th Floor) 14-15 Motijheel C.A., Dhaka-1000.",
        "phone": "01713-005125",
      },
      {
        "no": "8",
        "association_name_en": "Bangladesh Bi-cycle & Parts Manufacturers’ and Exporters Association",
        "association_name_bn": "বাংলাদেশ বাইসাইকেল ও যন্ত্রাংশ প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BBPMEA",
        "short_name_bn": "বিবিবিপিএমইএ",
        "address": "187-188/8 Tejgaon I.A, Dhaka.",
        "phone": "8817611,8817611-4",
      },
      {
        "no": "9",
        "association_name_en": "Bangladesh Button Manufacturer & Exporters Association",
        "association_name_bn": "বাংলাদেশ বোতাম প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BBMEA",
        "short_name_bn": "বিবিএমইএ",
        "address": "House # 180, Road # 02, New DOHS, Mohakhali, Dhaka-1212",
        "phone": "01711-521276",
      },
      {
        "no": "10",
        "association_name_en": "Bangladesh C.R. Coil Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ সিআর কয়েল প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BCRCMEA",
        "short_name_bn": "বিসিআরসিএমইএ",
        "address": "255, Nasirabad Industrial Area Chittagong.",
        "phone": "031-681240-44, 01817-053811",
      },
      {
        "no": "11",
        "association_name_en": "Bangladesh Ceramic Wares Manufacturers Association",
        "association_name_bn": "বাংলাদেশ সিরামিক ওয়্যারস প্রস্তুতকারক সমিতি",
        "short_name_en": "BCWMA",
        "short_name_bn": "বিসিডব্লিউএমএ",
        "address": "TMC Building (8th floor) 52, New Eskaton Road, Dhaka-1000.",
        "phone": "9340991-3, 01913-535149",
      },
      {
        "no": "12",
        "association_name_en": "Bangladesh Cha Sangsad",
        "association_name_bn": "বাংলাদেশ চা সংসদ",
        "short_name_en": "Tea Association of Bangladesh",
        "short_name_bn": "টি এ বি",
        "address": "Progressive Tower (4th Floor) 1837, Sk. Mujib Road Badamtoli, Agrabad C/A, Chittagong-4100",
        "phone": "716407,502536(O), 8827389(R)",
      },
      {
        "no": "13",
        "association_name_en": "Bangladesh Cigarette Manufacturers’ Association",
        "association_name_bn": "বাংলাদেশ সিগারেট প্রস্তুতকারক সমিতি",
        "short_name_en": "BCMA",
        "short_name_bn": "বিসিএমএ",
        "address": "KichukhanBhaban (3rd floor) 43/1, Ullan Road, Rampura, Dhaka-1219",
        "phone": "9122895-7(Off)",
      },
      {
        "no": "14",
        "association_name_en": "Bangladesh Cosmetics & Toiletries Manufacturers Association",
        "association_name_bn": "বাংলাদেশ কসমেটিকস ও টয়লেট্রিজ প্রস্তুতকারক সমিতি",
        "short_name_en": "BCTMA",
        "short_name_bn": "বিসিটিএমএ",
        "address": "Square Centre, 48 Mohakhali C/A Dhaka-1212, Bangladesh",
        "phone": "880-2-8817729, +880-2-8827729",
      },
      {
        "no": "15",
        "association_name_en": "Bangladesh Dyed Yarn Exporters Association",
        "association_name_bn": "বাংলাদেশ রঞ্জিত সুতা রপ্তানিকারক সমিতি",
        "short_name_en": "BDYEA",
        "short_name_bn": "বিডিওয়াইইএ",
        "address": "Erectors House (9th floor) 18, Kamal Ataturk Avenue Banani C/A, Dhaka-1213",
        "phone": "9821418-9",
      },
      {
        "no": "16",
        "association_name_en": "Bangladesh Electronics Manufacturers Association",
        "association_name_bn": "বাংলাদেশ ইলেকট্রনিক্স প্রস্তুতকারক সমিতি",
        "short_name_en": "BEMA",
        "short_name_bn": "বেমা",
        "address": "94 Malibagh DIT Road, Dhaka-1217",
        "phone": "9552078, 9557967",
      },
      {
        "no": "17",
        "association_name_en": "Bangladesh Engineering Shilpa Malik Samity",
        "association_name_bn": "বাংলাদেশ ইঞ্জিনিয়ারিং শিল্প মালিক সমিতি",
        "short_name_en": "BESMS",
        "short_name_bn": "বেসমস",
        "address": "38, Tipu Sultan Road, Dhaka",
        "phone": "7173403, 01713-047627",
      },
      {
        "no": "18",
        "association_name_en": "Bangladesh Finished Leather, Leather Goods &Footwear Exporters Association",
        "association_name_bn": "বাংলাদেশ সমাপ্ত চামড়া, চামড়াজাত পণ্য ও জুতা রপ্তানিকারক সমিতি",
        "short_name_en": "BFLLFEA",
        "short_name_bn": "বিএফএলএলএফইএ",
        "address": "House No. 32/A, Road No. 2, Flat No. B-2 Dhanmondi R/A, Dhaka-1209",
        "phone": "8622167-8",
      },
      {
        "no": "19",
        "association_name_en": "Bangladesh Fish Exporters & Importers Association",
        "association_name_bn": "বাংলাদেশ মৎস্য রপ্তানিকারক ও আমদানিকারক সমিতি",
        "short_name_en": "BFEIA",
        "short_name_bn": "বিএফইআইএ",
        "address": "ElishBhaban, Fish Market, Court Road, Barisal",
        "phone": "0431-63866, 01715-168006",
      },
      {
        "no": "20",
        "association_name_en": "Bangladesh Flower Growers and Exporters Association",
        "association_name_bn": "বাংলাদেশ ফুল চাষি ও রপ্তানিকারক সমিতি",
        "short_name_en": "BFGEA",
        "short_name_bn": "বিএফজিইএ",
        "address": "625/1, BaitulAman Housing Society (4th floor), Road No. 4, Mohammadpur, Dhaka",
        "phone": "8120434, 9141750, 9132452",
      },
      {
        "no": "21",
        "association_name_en": "Bangladesh Frozen Foods Exporters Association",
        "association_name_bn": "বাংলাদেশ হিমায়িত খাদ্য রপ্তানিকারক সমিতি",
        "short_name_en": "BFFEA",
        "short_name_bn": "বিএফএফইএ",
        "address": "Skylark Point (10th Floor) 24/A Bejoy Nagar, North South Road, Dhaka",
        "phone": "8316882, 8354857, 8317531",
      },
      {
        "no": "22",
        "association_name_en": "Bangladesh Fruits, Vegetables & AlliedProducts Exporters’ Association",
        "association_name_bn": "বাংলাদেশ ফল, শাকসবজি ও সহযোগী পণ্য রপ্তানিকারক সমিতি",
        "short_name_en": "BFVAEA",
        "short_name_bn": "বিএফভিএইএ",
        "address": "Rahmania Int’l Complex (5th Floor) Room # 11, 28/1/C, Toynbee Circular Road Motijheel, Dhaka-1000.",
        "phone": "9560506 (Ext: 101, 102, 103 & 105)",
      },
      {
        "no": "23",
        "association_name_en": "Bangladesh Furniture Exporters Association",
        "association_name_bn": "বাংলাদেশ আসবাবপত্র রপ্তানিকারক সমিতি",
        "short_name_en": "BFEA",
        "short_name_bn": "বিএফইএ",
        "address": "B-220-224, Shopping Centre (3rd floor) Gulshan-1, Dhaka-1212",
        "phone": "9895121, 01712-666942, 01711-522568",
      },
      {
        "no": "24",
        "association_name_en": "Bangladesh Garment Manufacturers & Exporters’ Association",
        "association_name_bn": "বাংলাদেশ তৈরি পোশাক প্রস্তুতকারক ও রপ্তানিকারক সমিতি (বিজিএমইএ)",
        "short_name_en": "BGMEA",
        "short_name_bn": "বিজিএমইএ",
        "address": "23/1, Panthapath Link Road, Karwan Bazar, Dhaka 1215",
        "phone": "028140310-20, 028140310, 01711-520099",
      },
      {
        "no": "25",
        "association_name_en": "Bangladesh Garments Accessories & Packaging Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ গার্মেন্টস এক্সেসরিজ ও প্যাকেজিং প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BGAPMEA",
        "short_name_bn": "বিজিএপিএমইএ",
        "address": "“Sonatari Tower” (9th Floor) Plot No.12, Biponon C/A Sonargaon Link Road, Dhaka",
        "phone": "880-2-9666763, 8621200",
      },
      {
        "no": "26",
        "association_name_en": "Bangladesh Handicrafts Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ হস্তশিল্প প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BANGLACRAFT",
        "short_name_bn": "বাংলা ক্রাফট",
        "address": "BTMC Bhaban 7-9 Kawran Bazar (4th Floor), Dhaka-1215",
        "phone": "9119090, 01713-013608",
      },
      {
        "no": "27",
        "association_name_en": "Bangladesh Herbal Products Manufacturing Association",
        "association_name_bn": "বাংলাদেশ হারবাল পণ্য প্রস্তুতকারক সমিতি",
        "short_name_en": "BHPMA",
        "short_name_bn": "বিহেপিএমএ",
        "address": "Atlantic Wazuddin Tower (3rd floor) 168, Elephant Road, Hatirpool, Dhaka-1205",
        "phone": "9669543, 01711-529179",
      },
      {
        "no": "28",
        "association_name_en": "Bangladesh Homeopathic Medicine Manufacturers’ Association",
        "association_name_bn": "বাংলাদেশ হোমিওপ্যাথিক ঔষধ প্রস্তুতকারক সমিতি",
        "short_name_en": "BHMMA",
        "short_name_bn": "বিহেএমএমএ",
        "address": "32, NayaPaltan (3rd Floor) DIT Extension Road, Dhaka 1000.",
        "phone": "9358279, 01711-540901",
      },
      {
        "no": "29",
        "association_name_en": "Bangladesh Jamdani Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ জামদানি প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BJMEA",
        "short_name_bn": "বিজেএমইএ",
        "address": "Feroza Tower (1st floor) 42/A/2, Hatkhola Road Tikatuli, Dhaka-1203",
        "phone": "01718-259521",
      },
      {
        "no": "30",
        "association_name_en": "Bangladesh Jewelry Manufacturers, Exporters & Merchants Association",
        "association_name_bn": "বাংলাদেশ জুয়েলারি প্রস্তুতকারক, রপ্তানিকারক ও ব্যবসায়ী সমিতি",
        "short_name_en": "BJMEMA",
        "short_name_bn": "বিজেএমইএমএ",
        "address": "88, Anarkali Super Market (4th floor) Mowchak, Siddeshwari, Dhaka.",
        "phone": "9357539, 8322314",
      },
      {
        "no": "31",
        "association_name_en": "Bangladesh Jute Association",
        "association_name_bn": "বাংলাদেশ পাট সমিতি",
        "short_name_en": "BJA",
        "short_name_bn": "বিজেএ",
        "address": "77, Motijheel C/A, Dhaka. Tel: 9552916 Ext: 111",
        "phone": "9552916 Ext: 111",
      },
      {
        "no": "32",
        "association_name_en": "Bangladesh Jute Goods Exporters Association",
        "association_name_bn": "বাংলাদেশ পাটজাত পণ্য রপ্তানিকারক সমিতি",
        "short_name_en": "BJGEA",
        "short_name_bn": "বিজেজিইএ",
        "address": "9/G,Motijheel C/A, Dhaka 1000.",
        "phone": "952910, 9553428, 7176935",
      },
      {
        "no": "33",
        "association_name_en": "Bangladesh Jute Mills Association",
        "association_name_bn": "বাংলাদেশ পাটকল সমিতি",
        "short_name_en": "BJMA",
        "short_name_bn": "বিজেএমএ",
        "address": "Adamjee Court (4th Floor) 115-120 Motijheel C/A, Dhaka-1000",
        "phone": "9566472, 9555798(O)",
      },
      {
        "no": "34",
        "association_name_en": "Bangladesh Jute Mills Corporation",
        "association_name_bn": "বাংলাদেশ পাটকল কর্পোরেশন",
        "short_name_en": "BJMC",
        "short_name_bn": "বিজেএমসি",
        "address": "Adamjee Court Annex-1, 115-120 Motijheel, Dhaka",
        "phone": "02-9558182",
      },
      {
        "no": "35",
        "association_name_en": "Bangladesh Jute Spinners Association",
        "association_name_bn": "বাংলাদেশ পাট সুতা উৎপাদক সমিতি",
        "short_name_en": "BJSA",
        "short_name_bn": "বিজেএসএ",
        "address": "55/A, PuranaPaltan (3rd Floor), Dhaka.",
        "phone": "9551317",
      },
      {
        "no": "36",
        "association_name_en": "Bangladesh Knitwear Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ নিটওয়্যার প্রস্তুতকারক ও রপ্তানিকারক সমিতি (বিকেএমইএ)",
        "short_name_en": "BKMEA",
        "short_name_bn": "বিকেএমইএ",
        "address": "Press Club Bhaban (1st& 3rd floor) 233/1, B.B. Road, Narayanganj-1400",
        "phone": "7640535, 7641295, 7641857, 8620377",
      },
      {
        "no": "37",
        "association_name_en": "Bangladesh Live & Chilled Food Exporters Association",
        "association_name_bn": "বাংলাদেশ লাইভ ও চিলড ফুড রপ্তানিকারক সমিতি",
        "short_name_en": "BLCFEA",
        "short_name_bn": "বিসিএলসিএফইএ",
        "address": "House-41 (3/B), SonargaonJanapath, Sector-12, Uttara, Dhaka-1230.",
        "phone": "8.80168E+12",
      },
      {
        "no": "38",
        "association_name_en": "Bangladesh Marine Fisheries Association",
        "association_name_bn": "বাংলাদেশ সামুদ্রিক মৎস্য সমিতি",
        "short_name_en": "BMFA",
        "short_name_bn": "বিএমএফএ",
        "address": "13/A Centre Point Concord Suit No. 13/A (13th Floor), Farmgate, Dhaka",
        "phone": "9120234, 031-637009",
      },
      {
        "no": "39",
        "association_name_en": "Bangladesh MudranShilpaSamity",
        "association_name_bn": "বাংলাদেশ মুদ্রণ শিল্প সমিতি",
        "short_name_en": "BMSS",
        "short_name_bn": "বিএমএসএস",
        "address": "City Heart (4th Floor) 67, NayaPaltan, Dhaka.",
        "phone": "9351728, 8321023",
      },
      {
        "no": "40",
        "association_name_en": "Bangladesh Paper Mills Association",
        "association_name_bn": "বাংলাদেশ কাগজকল সমিতি",
        "short_name_en": "BPMA",
        "short_name_bn": "বিপিএমএ",
        "address": "Plot # 335 (1st floor), Block-D Bashundhara R/A, Dhaka-1229",
        "phone": "8401806, 01730-018370",
      },
      {
        "no": "41",
        "association_name_en": "Bangladesh Pet Bottle Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ পেট বোতল প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BPFMEA",
        "short_name_bn": "বিপিএফএমইএ",
        "address": "City Heart, Suit # 5/8 (4th floor) 67, NayaPaltan, VIP Road, Dhaka-1000",
        "phone": "9348198, 01711-530077",
      },
      {
        "no": "42",
        "association_name_en": "Bangladesh Plastic Goods Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ প্লাস্টিক পণ্য প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BPGMEA",
        "short_name_bn": "বিপিজিএমইএ",
        "address": "Paltan Tower, Suite No. 603 & 604 87, PuranaPaltan Lane (6th Floor), Dhaka",
        "phone": "8350192, 01711-523423, 01819-458250",
      },
      {
        "no": "43",
        "association_name_en": "Bangladesh Potato Exporters Association",
        "association_name_bn": "বাংলাদেশ আলু রপ্তানিকারক সমিতি",
        "short_name_en": "BPEA",
        "short_name_bn": "বিপিইএ",
        "address": "67, PuranaPaltan Line Dhaka-1000",
        "phone": "9338562, 8332698",
      },
      {
        "no": "44",
        "association_name_en": "Bangladesh Rubber Bagan Owner Association",
        "association_name_bn": "বাংলাদেশ রাবার বাগান মালিক সমিতি",
        "short_name_en": "BRBOA",
        "short_name_bn": "বিআরবিওএ",
        "address": "Brothers Mension (1st floor) 8, Kalabagan, First Lane, Dhaka-1205.",
        "phone": "01713-003766, 01819-389470",
      },
      {
        "no": "45",
        "association_name_en": "Bangladesh Specialized Textile Mills &PowerloomIndustries Association",
        "association_name_bn": "বাংলাদেশ বিশেষায়িত টেক্সটাইল মিল ও পাওয়ারলুম শিল্প সমিতি",
        "short_name_en": "BSTMPIA",
        "short_name_bn": "বিসিটিএমপিআইএ",
        "address": "Suite # 204, Paltan Tower (2nd floor) 87, Purana PaltanLane, Dhaka-1000",
        "phone": "9360736, 8351973, 9553467, 9667029, 01911-393750, 01938-162500",
      },
      {
        "no": "46",
        "association_name_en": "Bangladesh Terry Towel & Linen Manufacturers & Exporters Association",
        "association_name_bn": "বাংলাদেশ টেরি টাওয়েল ও লিনেন প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "BTTLMEA",
        "short_name_bn": "বিটিটিএলএমইএ",
        "address": "Paltan Tower(5th fl.),Suit#507 87, PuranaPaltan Line, Dhaka-1000",
        "phone": "9.35182E+20",
      },
      {
        "no": "47",
        "association_name_en": "Bangladesh Textile and Garments Waste Processors & Exporters Association",
        "association_name_bn": "বাংলাদেশ টেক্সটাইল ও গার্মেন্টস বর্জ্য প্রক্রিয়াজাতকরণ ও রপ্তানিকারক সমিতি",
        "short_name_en": "BTGWPEA",
        "short_name_bn": "বিটিজিডব্লিউপিইএ",
        "address": "House # 15, Road # 7, Sector # 4 Uttara, Dhaka.",
        "phone": "8920413, 01731-317155",
      },
      {
        "no": "48",
        "association_name_en": "Bangladesh Textile Mills Association",
        "association_name_bn": "বাংলাদেশ টেক্সটাইল মিলস সমিতি",
        "short_name_en": "BTMA",
        "short_name_bn": "বিটিএমএ",
        "address": "8 Panthapath, Kawran Bazar Dhaka-1215",
        "phone": "9143461, 9130969, 8112361 (Off)",
      },
      {
        "no": "49",
        "association_name_en": "Exporters Association of Bangladesh",
        "association_name_bn": "বাংলাদেশ রপ্তানিকারক সমিতি",
        "short_name_en": "EAB",
        "short_name_bn": "ইএবি",
        "address": "406-B, Khilgaon, Chowdhury Para, Dhaka.",
        "phone": "7217403, 7214912, 01711-525717, 01977-222222",
      },
      {
        "no": "50",
        "association_name_en": "Homeopathic Medicine & Medicinal Plant Importer & Exporter Association of Bangladesh",
        "association_name_bn": "বাংলাদেশ হোমিওপ্যাথিক ঔষধ ও ঔষধি উদ্ভিদ আমদানিকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "HMMPIEAB",
        "short_name_bn": "এইচএমএমপিআইইএবি",
        "address": "9/7, Secretariat Road, Fulbaria, Dhaka.",
        "phone": "9571788, 01715-151649",
      },
      {
        "no": "51",
        "association_name_en": "Leather Goods andFootwear Manufacturers and Exporters Association of Bangladesh",
        "association_name_bn": "বাংলাদেশ চামড়াজাত পণ্য ও জুতা প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "LFMEAB",
        "short_name_bn": "এলএফএমইএবি",
        "address": "Erectors House (9th Floor) 18 Kemal Ataturk Avenue Banani C/A, Dhaka-1213",
        "phone": "9880102-5",
      },
      {
        "no": "52",
        "association_name_en": "Packaging Industries Association of Bangladesh",
        "association_name_bn": "বাংলাদেশ প্যাকেজিং শিল্প সমিতি",
        "short_name_en": "PIAB",
        "short_name_bn": "পিআইএবি",
        "address": "68, Dilkusha C.A.(Ground Floor) GPO Box No.535, Dhaka-1000.",
        "phone": "9557275, 9557271, 9552591-2, 01711522258",
      },
      {
        "no": "53",
        "association_name_en": "Silk Manufacturers’& Exporters Association of Bangladesh",
        "association_name_bn": "বাংলাদেশ সিল্ক প্রস্তুতকারক ও রপ্তানিকারক সমিতি",
        "short_name_en": "SMEAB",
        "short_name_bn": "এসএমইএবি",
        "address": "Suite No. 2 (4th floor), Highway Homes Ka-32/6 PragotiSaroni Shahjadpur, Gulshan, Dhaka-1212",
        "phone": "8827112",
      },
      {
        "no": "54",
        "association_name_en": "Tour Operators Association of Bangladesh",
        "association_name_bn": "বাংলাদেশ ট্যুর অপারেটরস অ্যাসোসিয়েশন",
        "short_name_en": "TOAB",
        "short_name_bn": "টিওএবি",
        "address": "5/8, Monipuripara Sangshad Avenue, Dhaka-1215",
        "phone": "9136554, 9862205",
      }
    ]
    for item in seed_data:
        WorkforceAllAssociation.objects.create(
            id=uuid.uuid4(),
            name_en=item["association_name_en"],
            name_bn=item["association_name_bn"],
            address=item["address"],
            short_name_bn=item["short_name_bn"],
            short_name_en=item["short_name_en"],
            status="active",
            user_created_id=user_id,
            user_updated_id=user_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0243_merge_20251223_0806'),
    ]

    operations = [
        migrations.RunPython(seed_all_association),
    ]
