# Generated by Django 4.2.20 on 2025-12-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0245_seed_workforce_organization_employee_all_association_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceallassociation',
            name='association_admin',
        ),
        migrations.RemoveField(
            model_name='workforceallassociation',
            name='association_admin',
        ),
        migrations.AddField(
            model_name='historicalworkforceorganizationemployee',
            name='all_association',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceallassociation'),
        ),
        migrations.AddField(
            model_name='workforceorganizationemployee',
            name='all_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_organization_employee_association', to='workforce.workforceallassociation'),
        ),
    ]
