# Generated by Django 4.2.25 on 2025-12-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0244_historicalworkforceeispaymentprocess_is_approved_and_more'),
        ('workforce', '0247_seed_workforce_organization_employee_all_association_admins_relation'),
    ]

    operations = [
    ]
