# Generated by Django 4.2.20 on 2025-12-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0247_seed_workforce_organization_employee_all_association_admins_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='all_association',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceallassociation'),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='all_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factory_all_association', to='workforce.workforceallassociation'),
        ),
    ]
