# Generated by Django 4.2.20 on 2025-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0248_historicalworkforcefactory_all_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
