# Generated by Django 4.2.25 on 2025-12-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0248_historicalworkforcefactory_all_association_and_more'),
        ('workforce', '0248_merge_20251223_1645'),
    ]

    operations = [
    ]
