# Generated by Django 4.2.20 on 2025-12-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0249_historicalworkforceemployeedependent_attachments_and_more'),
        ('workforce', '0249_merge_20251224_1157'),
    ]

    operations = [
    ]
