# Generated by Django 4.2.25 on 2025-12-24 13:05

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0249_merge_20251224_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceOtherCompensationInfo',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('entry_by', models.CharField(blank=True, db_comment='factory, officer', max_length=50, null=True)),
                ('date_of_compensation', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('status_of_payment', models.CharField(blank=True, db_comment='paid, unpaid', max_length=30, null=True)),
                ('is_eis_benefit_adjustment_eligible', models.BooleanField(db_comment='for entry_by officer only', default=False)),
                ('remarks', models.TextField(blank=True, db_comment='for entry_by officer only', null=True)),
                ('payment_type', models.CharField(blank=True, db_comment='monthly, yearly, one time, installment', max_length=50, null=True)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
                ('workforce_application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_application_other_compensation_info', to='workforce.workforceapplication')),
            ],
            options={
                'db_table': 'workforce_other_compensation_info',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkforceOtherCompensationInfo',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('entry_by', models.CharField(blank=True, db_comment='factory, officer', max_length=50, null=True)),
                ('date_of_compensation', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('status_of_payment', models.CharField(blank=True, db_comment='paid, unpaid', max_length=30, null=True)),
                ('is_eis_benefit_adjustment_eligible', models.BooleanField(db_comment='for entry_by officer only', default=False)),
                ('remarks', models.TextField(blank=True, db_comment='for entry_by officer only', null=True)),
                ('payment_type', models.CharField(blank=True, db_comment='monthly, yearly, one time, installment', max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workforce_application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication')),
            ],
            options={
                'verbose_name': 'historical workforce other compensation info',
                'verbose_name_plural': 'historical workforce other compensation infos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
