# Generated by Django 4.2.16 on 2025-12-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0250_merge_20251224_0708'),
        ('workforce', '0250_workforceothercompensationinfo_and_more'),
    ]

    operations = [
    ]
