# Generated by Django 4.2.26 on 2025-12-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0251_merge_20251224_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceeispaymentprocess',
            name='is_approved',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentprocess',
            name='is_approved',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
