# Generated by Django 4.2.26 on 2025-12-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0252_alter_historicalworkforceeispaymentprocess_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceeispaymentprocess',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='workforceeispaymentprocess',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
