# Generated by Django 4.2.25 on 2025-12-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0253_rename_is_approved_historicalworkforceeispaymentprocess_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceothercompensationinfo',
            name='received_from_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceothercompensationinfo',
            name='received_from_organization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
