# Generated by Django 4.2.25 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0254_historicalworkforceothercompensationinfo_received_from_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceothercompensationinfo',
            name='is_eis_benefit_adjustment_eligible',
            field=models.CharField(db_comment='for entry_by officer only, value=yes, no, empty', default='No', max_length=6),
        ),
        migrations.AlterField(
            model_name='workforceothercompensationinfo',
            name='is_eis_benefit_adjustment_eligible',
            field=models.CharField(db_comment='for entry_by officer only, value=yes, no, empty', default='No', max_length=6),
        ),
    ]
