# Generated by Django 4.2.20 on 2026-01-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0255_alter_historicalworkforceothercompensationinfo_is_eis_benefit_adjustment_eligible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforcesignature',
            name='related_user',
        ),
        migrations.RemoveField(
            model_name='workforcesignature',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='workforcesignature',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='HistoricalWorkforceSignature',
        ),
        migrations.DeleteModel(
            name='WorkforceSignature',
        ),
    ]
