# Generated by Django 4.2.25 on 2026-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0256_remove_workforcesignature_related_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployeedependent',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployeedependent',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
