# Generated by Django 4.2.25 on 2026-01-06 14:55

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0257_historicalworkforceemployeedependent_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='beneficiary_status',
            field=models.CharField(db_comment='hold, closed, eligible', default='eligible', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='decrement_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='increment_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='last_live_check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='remarriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='remarried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='total_adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='beneficiary_status',
            field=models.CharField(db_comment='hold, closed, eligible', default='eligible', max_length=25),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='decrement_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='increment_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='last_live_check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='remarriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='remarried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='total_adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.CreateModel(
            name='WorkforceEisPaymentDisbursementStage',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('eis_payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('eis_calculated_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('eis_approved_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('eis_initial_replacement_rate', models.FloatField(blank=True, null=True)),
                ('eis_initial_monthly_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('eis_monthly_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('increment_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('decrement_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('total_adjustment_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('month_index', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('approved', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiary_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_payment_stage_bank', to='workforce.bank')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_payment_stage_processed_by', to='core.interactiveuser')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
                ('workforce_application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_payment_stage_application', to='workforce.workforceapplication')),
                ('workforce_application_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_payment_stage_application_summary', to='workforce.workforceapplicationsummary')),
                ('workforce_employee_dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_payment_stage_employee_dependent', to='workforce.workforceemployeedependent')),
            ],
            options={
                'db_table': 'workforce_eis_payment_disbursement_stage',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkforceEisPaymentDisbursementStage',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('eis_payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('eis_calculated_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('eis_approved_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('eis_initial_replacement_rate', models.FloatField(blank=True, null=True)),
                ('eis_initial_monthly_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('eis_monthly_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('increment_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('decrement_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('total_adjustment_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True)),
                ('month_index', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('approved', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiary_id', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.bank')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.interactiveuser')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workforce_application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication')),
                ('workforce_application_summary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplicationsummary')),
                ('workforce_employee_dependent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceemployeedependent')),
            ],
            options={
                'verbose_name': 'historical workforce eis payment disbursement stage',
                'verbose_name_plural': 'historical workforce eis payment disbursement stages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
