# Generated by Django 4.2.25 on 2026-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0258_historicalworkforceeispaymentprocess_beneficiary_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='workforce_application',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='workforce_application_summary',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentdisbursementstage',
            name='workforce_employee_dependent',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='beneficiary_status',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='decrement_amount',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='increment_amount',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='is_dead',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='last_live_check_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='remarriage_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='remarried',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='total_adjustment_amount',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='beneficiary_status',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='decrement_amount',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='increment_amount',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='is_dead',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='last_live_check_date',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='remarriage_date',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='remarried',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='total_adjustment_amount',
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='applicant_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='applicant_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='deceased_worker_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='deceased_worker_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_entry_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='doctors_entry_verification_remarks',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_accident_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_accident_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_bank_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_bank_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_children_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_children_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_dependent_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='employee_dependent_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='institution_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='institution_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='metadata_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='metadata_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='workforce_employee_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='workforce_employee_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='applicant_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='applicant_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='deceased_worker_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='deceased_worker_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_entry_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='doctors_entry_verification_remarks',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_accident_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_accident_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_bank_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_bank_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_children_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_children_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_dependent_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='employee_dependent_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='institution_info_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='institution_info_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='metadata_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='metadata_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='workforce_employee_verification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='workforce_employee_verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalWorkforceEisPaymentDisbursementStage',
        ),
        migrations.DeleteModel(
            name='WorkforceEisPaymentDisbursementStage',
        ),
    ]
