# Generated by Django 4.2.25 on 2026-01-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0259_remove_workforceeispaymentdisbursementstage_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceallassociation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceallassociation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
