# Generated by Django 4.2.25 on 2026-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0261_historicalworkforceeispaymentprocess_beneficiary_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceeispaymentprocess',
            old_name='remarriage_date',
            new_name='remarriage_or_death_date',
        ),
        migrations.RenameField(
            model_name='workforceeispaymentprocess',
            old_name='remarriage_date',
            new_name='remarriage_or_death_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='is_dead',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='remarried',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='is_dead',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='remarried',
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='closing_reason',
            field=models.CharField(blank=True, db_comment='Remarried, Died', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='closing_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='hold_reason',
            field=models.CharField(blank=True, db_comment='live_check, others', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='hold_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='closing_reason',
            field=models.CharField(blank=True, db_comment='Remarried, Died', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='closing_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='hold_reason',
            field=models.CharField(blank=True, db_comment='live_check, others', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='hold_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
