# Generated by Django 4.2.25 on 2026-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0262_rename_remarriage_date_historicalworkforceeispaymentprocess_remarriage_or_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='live_check_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='live_check_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
