# Generated by Django 4.2.26 on 2026-01-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0263_historicalworkforceeispaymentprocess_live_check_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
