# Generated by Django 4.2.25 on 2026-01-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0264_historicalworkforceeispaymentprocess_is_eligible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforceeispaymentprocess',
            old_name='closing_remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='workforceeispaymentprocess',
            old_name='closing_remarks',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='closing_reason',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='hold_reason',
        ),
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='hold_remarks',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='closing_reason',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='hold_reason',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='hold_remarks',
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='reason',
            field=models.CharField(blank=True, db_comment='Remarried, Died, live_check_denied', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='reason',
            field=models.CharField(blank=True, db_comment='Remarried, Died, live_check_denied', max_length=50, null=True),
        ),
    ]
