# Generated by Django 4.2.25 on 2026-01-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0266_historicalworkforceeispaymentprocess_decrement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='decrement_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='decrement_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
