# Generated by Django 4.2.25 on 2026-01-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0267_historicalworkforceeispaymentprocess_decrement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
