# Generated by Django 4.2.25 on 2026-01-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0268_historicalworkforceeispaymentprocess_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='workforce_eis_payment_process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceeispaymentprocess'),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='workforce_eis_payment_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_eis_payment_stage_relation', to='workforce.workforceeispaymentprocess'),
        ),
    ]
