# Generated by Django 4.2.25 on 2026-01-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0270_historicalworkforceeispaymentdisbursementstage_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='beneficiary_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='beneficiary_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
