# Generated by Django 4.2.25 on 2026-01-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0271_historicalworkforceeispaymentdisbursement_beneficiary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='workforce_eis_payment_disbursement_stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceeispaymentdisbursementstage'),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='workforce_eis_payment_disbursement_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_payment_disbursement_stage_disbursement', to='workforce.workforceeispaymentdisbursementstage'),
        ),
    ]
