# Generated by Django 4.2.25 on 2026-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0272_historicalworkforceeispaymentdisbursement_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
