# Generated by Django 4.2.25 on 2026-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0273_historicalworkforceeispaymentdisbursementstage_disbursement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='onetime_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='payment_type_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='trimonthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='onetime_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='payment_type_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='trimonthly_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
    ]
