# Generated by Django 4.2.25 on 2026-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0274_historicalworkforceeispaymentprocess_onetime_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
    ]
