# Generated by Django 4.2.26 on 2026-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0275_historicalworkforceeispaymentprocess_payable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
