# Generated by Django 4.2.26 on 2026-02-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0277_workforceassociationusermap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceorganizationemployee',
            name='workforce_employer_factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcefactory'),
        ),
        migrations.AddField(
            model_name='workforceorganizationemployee',
            name='workforce_employer_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_employee_factory', to='workforce.workforcefactory'),
        ),
    ]
