# Generated by Django 4.2.26 on 2026-02-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0278_historicalworkforceorganizationemployee_workforce_employer_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='all_association',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceallassociation'),
        ),
        migrations.AddField(
            model_name='historicalworkforceemployee',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='all_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_employee_association', to='workforce.workforceallassociation'),
        ),
        migrations.AddField(
            model_name='workforceemployee',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
