# Generated by Django 4.2.25 on 2026-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0279_historicalworkforceemployee_all_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_approval_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='eis_approved_by_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_approval_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='eis_approved_by_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
