# Generated by Django 4.2.25 on 2026-03-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0282_workforceeisbankadvice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='workforce_eis_bank_advice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceeisbankadvice'),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='workforce_eis_bank_advice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_eis_bank_advice_payment_stage', to='workforce.workforceeisbankadvice'),
        ),
    ]
