# Generated by Django 4.2.25 on 2026-03-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0283_historicalworkforceeispaymentdisbursementstage_workforce_eis_bank_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='accident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='accident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
