# Generated by Django 4.2.26 on 2026-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0284_historicalworkforceapplication_accident_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceothercompensationinfo',
            name='is_eis_benefit_adjustment_eligible',
            field=models.CharField(blank=True, db_comment='for entry_by officer only, value=yes, no, empty', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='workforceothercompensationinfo',
            name='is_eis_benefit_adjustment_eligible',
            field=models.CharField(blank=True, db_comment='for entry_by officer only, value=yes, no, empty', max_length=6, null=True),
        ),
    ]
