# Generated by Django 4.2.25 on 2026-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0284_historicalworkforceapplication_accident_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workforcedocument',
            constraint=models.UniqueConstraint(fields=('path', 'url'), name='unique_document_source'),
        ),
    ]
