# Generated by Django 4.2.25 on 2026-03-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0285_workforcedocument_unique_document_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workforcedocument',
            name='unique_document_source',
        ),
    ]
