# Generated by Django 4.2.25 on 2026-03-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0285_alter_historicalworkforceothercompensationinfo_is_eis_benefit_adjustment_eligible_and_more'),
        ('workforce', '0286_remove_workforcedocument_unique_document_source'),
    ]

    operations = [
    ]
