# Generated by Django 4.2.25 on 2026-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0287_merge_20260312_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='arrear_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='arrear_payment_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='arrear_payment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='arrear_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='arrear_payment_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='arrear_payment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
