# Generated by Django 4.2.25 on 2026-03-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0288_historicalworkforceeispaymentprocess_arrear_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceeispaymentprocess',
            name='arrear_payment_year',
        ),
        migrations.RemoveField(
            model_name='workforceeispaymentprocess',
            name='arrear_payment_year',
        ),
    ]
