# Generated by Django 4.2.25 on 2026-03-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0289_remove_historicalworkforceeispaymentprocess_arrear_payment_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='arrear_payment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='arrear_payment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
