# Generated by Django 4.2.26 on 2026-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0290_historicalworkforceeispaymentprocess_arrear_payment_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeisbankadvice',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeisbankadvice',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
