# Generated by Django 4.2.25 on 2026-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0292_workforcecommittee_workforcecommitteeusermap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcecommittee',
            name='associations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcecommittee',
            name='associations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
