# Generated by Django 4.2.25 on 2026-04-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0294_alter_workforcecommitteeusermap_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforcecommitteeuser',
            old_name='related_user_id',
            new_name='related_user',
        ),
        migrations.RenameField(
            model_name='workforcecommitteeuser',
            old_name='related_user_id',
            new_name='related_user',
        ),
    ]
