# Generated by Django 4.2.25 on 2026-04-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('workforce', '0295_rename_related_user_id_historicalworkforcecommitteeuser_related_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforcedocumentmap',
            old_name='mapped_by',
            new_name='verified_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkforcedocumentmap',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalworkforcedocumentmap',
            name='workforce_document_type',
        ),
        migrations.RemoveField(
            model_name='workforcedocumentmap',
            name='mapped_by',
        ),
        migrations.RemoveField(
            model_name='workforcedocumentmap',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workforcedocumentmap',
            name='workforce_document_type',
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumentmap',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumentmap',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumentmap',
            name='verified_by_role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.interactiveuser'),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumentmap',
            name='workforce_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='historicalworkforcedocumentmap',
            name='workforce_document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcedocument'),
        ),
        migrations.AddField(
            model_name='workforcedocumentmap',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumentmap',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcedocumentmap',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_verifier', to='core.interactiveuser'),
        ),
        migrations.AddField(
            model_name='workforcedocumentmap',
            name='verified_by_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_verifier_role', to='core.interactiveuser'),
        ),
        migrations.AddField(
            model_name='workforcedocumentmap',
            name='workforce_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_document_map_application', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='workforcedocumentmap',
            name='workforce_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_document_map_document_id', to='workforce.workforcedocument'),
        ),
    ]
