# Generated by Django 4.2.25 on 2026-04-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0296_rename_mapped_by_historicalworkforcedocumentmap_verified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforcecommitteeuser',
            name='committee_role',
        ),
        migrations.RemoveField(
            model_name='workforcecommitteeuser',
            name='committee_role',
        ),
        migrations.AddField(
            model_name='historicalworkforcecommitteeusermap',
            name='role_in_committee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcecommitteeusermap',
            name='workforce_committee_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforcecommitteeuser'),
        ),
        migrations.AddField(
            model_name='workforcecommitteeusermap',
            name='role_in_committee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workforcecommitteeusermap',
            name='workforce_committee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_user_map_committee_user_id', to='workforce.workforcecommitteeuser'),
        ),
    ]
