# Generated by Django 4.2.26 on 2026-04-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0299_workforcenotification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkforcenotification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workforcenotification',
            old_name='user_id',
            new_name='user',
        ),
    ]
