# Generated by Django 4.2.26 on 2026-04-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0300_rename_user_id_historicalworkforcenotification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcenotification',
            name='notification_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcenotification',
            name='notification_bn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
