# Generated by Django 4.2.26 on 2026-04-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0301_historicalworkforcenotification_notification_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcenotification',
            name='workforce_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workforce.workforceapplication'),
        ),
        migrations.AddField(
            model_name='workforcenotification',
            name='workforce_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_notification_application_id', to='workforce.workforceapplication'),
        ),
    ]
