# Generated by Django 4.2.25 on 2026-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0302_historicalworkforcenotification_workforce_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcefactory',
            name='association_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforcefactory',
            name='association_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
