# Generated by Django 4.2.25 on 2026-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0303_historicalworkforcefactory_association_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforcefactory',
            name='association_number',
        ),
        migrations.RemoveField(
            model_name='workforcefactory',
            name='association_number',
        ),
        migrations.AddField(
            model_name='historicalworkforceallassociation',
            name='association_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceallassociation',
            name='association_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
