# Generated by Django 4.2.29 on 2026-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0305_alter_historicalworkforceallassociation_association_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceallassociation',
            name='association_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforceallassociation',
            name='association_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
