# Generated by Django 4.2.29 on 2026-05-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0306_alter_historicalworkforceallassociation_association_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcecommitteebankadvicemap',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committee_bank_advice_map_committee_id', to='workforce.workforcecommittee'),
        ),
        migrations.AlterModelTable(
            name='workforcecommitteebankadvicemap',
            table='workforce_committee_bank_advice_map',
        ),
    ]
