# Generated by Django 4.2.29 on 2026-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0307_alter_workforcecommitteebankadvicemap_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='committee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='committee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
