# Generated by Django 4.2.29 on 2026-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0308_historicalworkforceapplication_committee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcecommittee',
            name='approval_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforcecommittee',
            name='organization_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcecommittee',
            name='approval_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcecommittee',
            name='organization_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
