# Generated by Django 4.2.29 on 2026-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0309_historicalworkforcecommittee_approval_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcecommitteeusermap',
            name='is_Representative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforcecommitteeusermap',
            name='is_Representative',
            field=models.BooleanField(default=False),
        ),
    ]
