# Generated by Django 4.2.29 on 2026-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0310_historicalworkforcecommitteeusermap_is_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcecommitteeusermap',
            name='is_Representative',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeusermap',
            name='is_Representative',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
