# Generated by Django 4.2.25 on 2026-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0312_websitelegalguideline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebsitelegalguideline',
            name='workforce_document',
        ),
        migrations.RemoveField(
            model_name='websitelegalguideline',
            name='workforce_document',
        ),
        migrations.AddField(
            model_name='historicalwebsitelegalguideline',
            name='document_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebsitelegalguideline',
            name='document_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitelegalguideline',
            name='document_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitelegalguideline',
            name='document_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
