# Generated by Django 4.2.25 on 2026-05-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0313_remove_historicalwebsitelegalguideline_workforce_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitelegalguideline',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='websitelegalguideline',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='HistoricalWebsiteLegalGuideline',
        ),
        migrations.DeleteModel(
            name='WebsiteLegalGuideline',
        ),
    ]
