# Generated by Django 4.2.25 on 2026-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0316_websitevisitormessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
