# Generated by Django 4.2.25 on 2026-06-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0317_historicalworkforceeispaymentdisbursement_user_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='noa_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='noa_sms_sent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='noa_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='noa_sms_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
