# Generated by Django 4.2.25 on 2026-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0318_historicalworkforceeispaymentprocess_noa_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='noa_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='noa_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
