# Generated by Django 4.2.25 on 2026-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0319_historicalworkforceeispaymentprocess_noa_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='nid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='nid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
