# Generated by Django 4.2.29 on 2026-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0320_alter_historicalworkforceemployee_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkforcecommittee',
            name='name_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommittee',
            name='name_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
