# Generated by Django 4.2.29 on 2026-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0322_historicalworkforceeispaymentdisbursement_routing_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='committee_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='committee_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
