# Generated by Django 4.2.29 on 2026-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0323_historicalworkforceapplication_committee_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceapplication',
            name='rejected_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceapplication',
            name='rejected_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
