# Generated by Django 4.2.29 on 2026-07-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0324_historicalworkforceapplication_rejected_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforceapplication',
            name='rejected_ids',
        ),
        migrations.RemoveField(
            model_name='workforceapplication',
            name='rejected_ids',
        ),
    ]
