# Generated by Django 4.2.25 on 2026-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0326_historicalworkforceapplication_rejected_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='pay_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='pay_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='pay_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='pay_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
