# Generated by Django 4.2.30 on 2026-08-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_verification', '0007_remove_biometricembedding_insuree_and_more'),
        ('workforce', '0328_alter_bank_date_created_alter_bank_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforcedocument',
            name='biometric_embedding',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biometric_verification.biometricembedding'),
        ),
        migrations.AddField(
            model_name='workforcedocument',
            name='biometric_embedding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='biometric_embedding_for_documents', to='biometric_verification.biometricembedding'),
        ),
    ]
