# Generated by Django 4.2.25 on 2026-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0329_historicalworkforcedocument_biometric_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkforcedocument',
            name='biometric_embedding',
        ),
        migrations.RemoveField(
            model_name='workforcedocument',
            name='biometric_embedding',
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkforceeispaymentprocess',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursement',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentprocess',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
