# Generated by Django 4.2.25 on 2026-08-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0330_remove_historicalworkforcedocument_biometric_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbank',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentprocess',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeebankinginfo',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursement',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursementstage',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentprocess',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
