# Generated by Django 4.2.25 on 2026-08-20 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0332_alter_bank_date_created_alter_bank_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceeispaymentdisbursementstage',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbank',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbank',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwebsitelegalguideline',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwebsitelegalguideline',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwebsitevisitormessage',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwebsitevisitormessage',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceallassociation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceallassociation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplication',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplication',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplicationmovement',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplicationmovement',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplicationsummary',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplicationsummary',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplicationsummarymovement',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceapplicationsummarymovement',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceassociation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceassociation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceassociationusermap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceassociationusermap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommittee',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommittee',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteeassociationmap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteeassociationmap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteebankadvicemap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteebankadvicemap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteeuser',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteeuser',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteeusermap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcecommitteeusermap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcediseases',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcediseases',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocument',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumentmap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumentmap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcedocumenttype',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeducation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeisbankadvice',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeisbankadvice',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursement',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentdisbursementstage',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentprocess',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceeispaymentprocess',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployee',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccident',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccident',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccountinfo',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeeaccountinfo',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeebankinginfo',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeebankinginfo',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedependent',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedesignation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployeedesignation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployer',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceemployer',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcefactory',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcefactory',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcegrantmoney',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcegrantmoney',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcenotification',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcenotification',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceoffice',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceoffice',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganization',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganization',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationemployee',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationemployee',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationemployeedesignation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationemployeedesignation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationunit',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationunit',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationunitdesignation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceorganizationunitdesignation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceothercompensationinfo',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforceothercompensationinfo',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcerepresentative',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkforcerepresentative',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='websitelegalguideline',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='websitelegalguideline',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='websitevisitormessage',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='websitevisitormessage',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceallassociation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceallassociation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplication',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplicationmovement',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummary',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummary',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummarymovement',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceapplicationsummarymovement',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceassociation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceassociation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceassociationusermap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceassociationusermap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommittee',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommittee',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeassociationmap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeassociationmap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteebankadvicemap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteebankadvicemap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeuser',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeuser',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeusermap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcecommitteeusermap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcediseases',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcediseases',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocument',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumentmap',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumentmap',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcedocumenttype',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeducation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeisbankadvice',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeisbankadvice',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursement',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursement',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursementstage',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentdisbursementstage',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentprocess',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceeispaymentprocess',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployee',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccident',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeeaccountinfo',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeebankinginfo',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedependent',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployeedesignation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployer',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceemployer',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcefactory',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcegrantmoney',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcegrantmoney',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcenotification',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcenotification',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceoffice',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganization',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganization',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployee',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployee',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployeedesignation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationemployeedesignation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunit',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunit',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunitdesignation',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceorganizationunitdesignation',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceothercompensationinfo',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforceothercompensationinfo',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcerepresentative',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='workforcerepresentative',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
    ]
